// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_views.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteBoardView = `-- name: DeleteBoardView :exec
DELETE FROM board_views WHERE id = $1
`

func (q *Queries) DeleteBoardView(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardView, id)
	return err
}

const getBoardView = `-- name: GetBoardView :one
SELECT id, board_id, user_id, name, config, created_at, updated_at FROM board_views WHERE id = $1
`

func (q *Queries) GetBoardView(ctx context.Context, id uuid.UUID) (BoardView, error) {
	row := q.db.QueryRow(ctx, getBoardView, id)
	var i BoardView
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBoardViews = `-- name: ListBoardViews :many
SELECT id, board_id, user_id, name, config, created_at, updated_at FROM board_views WHERE board_id = $1 AND user_id = $2 ORDER BY name
`

type ListBoardViewsParams struct {
	BoardID uuid.UUID `json:"board_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ListBoardViews(ctx context.Context, arg ListBoardViewsParams) ([]BoardView, error) {
	rows, err := q.db.Query(ctx, listBoardViews, arg.BoardID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardView
	for rows.Next() {
		var i BoardView
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.UserID,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBoardView = `-- name: UpsertBoardView :one
INSERT INTO board_views (board_id, user_id, name, config, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (board_id, user_id, name) DO UPDATE
SET config = EXCLUDED.config, updated_at = now()
RETURNING id, board_id, user_id, name, config, created_at, updated_at
`

type UpsertBoardViewParams struct {
	BoardID uuid.UUID `json:"board_id"`
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	Config  []byte    `json:"config"`
}

// UpsertBoardView creates a view or overwrites the user's same-named one.
func (q *Queries) UpsertBoardView(ctx context.Context, arg UpsertBoardViewParams) (BoardView, error) {
	row := q.db.QueryRow(ctx, upsertBoardView,
		arg.BoardID,
		arg.UserID,
		arg.Name,
		arg.Config,
	)
	var i BoardView
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
