// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const boardSlugExistsInProject = `-- name: BoardSlugExistsInProject :one
SELECT EXISTS(SELECT 1 FROM boards WHERE project_id = $1 AND slug = $2)
`

type BoardSlugExistsInProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) BoardSlugExistsInProject(ctx context.Context, arg BoardSlugExistsInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, boardSlugExistsInProject, arg.ProjectID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const boardsMissingSlug = `-- name: BoardsMissingSlug :many
SELECT id, project_id, name FROM boards WHERE slug = ''
`

type BoardsMissingSlugRow struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) BoardsMissingSlug(ctx context.Context) ([]BoardsMissingSlugRow, error) {
	rows, err := q.db.Query(ctx, boardsMissingSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardsMissingSlugRow
	for rows.Next() {
		var i BoardsMissingSlugRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (project_id, name, slug, position)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode
`

type CreateBoardParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Position  float64   `json:"position"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Position,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneColumnID,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IconMode,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO board_columns (board_id, name, name_key, color, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, board_id, name, color, position, created_at, updated_at, name_key
`

type CreateColumnParams struct {
	BoardID  uuid.UUID `json:"board_id"`
	Name     string    `json:"name"`
	NameKey  *string   `json:"name_key"`
	Color    string    `json:"color"`
	Position float64   `json:"position"`
}

// CreateColumn takes an optional name_key alongside the display name: the four
// columns seeded with a new board pass their key ('todo', 'in_progress', …) so
// clients can caption them in the reader's language, a column the user adds
// himself passes NULL and is shown verbatim.
func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.BoardID,
		arg.Name,
		arg.NameKey,
		arg.Color,
		arg.Position,
	)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM board_columns WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteColumn, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode FROM boards WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneColumnID,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IconMode,
	)
	return i, err
}

const getBoardBySlug = `-- name: GetBoardBySlug :one
SELECT id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode FROM boards WHERE slug = $1 LIMIT 1
`

// GetBoardBySlug returns the first board with this slug (legacy global lookup,
// best-effort: board slugs are unique only per project now).
func (q *Queries) GetBoardBySlug(ctx context.Context, slug string) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardBySlug, slug)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneColumnID,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IconMode,
	)
	return i, err
}

const getBoardInProjectBySlug = `-- name: GetBoardInProjectBySlug :one
SELECT id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode FROM boards WHERE project_id = $1 AND slug = $2
`

type GetBoardInProjectBySlugParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) GetBoardInProjectBySlug(ctx context.Context, arg GetBoardInProjectBySlugParams) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardInProjectBySlug, arg.ProjectID, arg.Slug)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneColumnID,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IconMode,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one
SELECT id, board_id, name, color, position, created_at, updated_at, name_key FROM board_columns WHERE id = $1
`

func (q *Queries) GetColumn(ctx context.Context, id uuid.UUID) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode FROM boards WHERE project_id = $1 ORDER BY position
`

func (q *Queries) ListBoards(ctx context.Context, projectID uuid.UUID) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DoneColumnID,
			&i.Slug,
			&i.Icon,
			&i.Color,
			&i.IconMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumns = `-- name: ListColumns :many
SELECT id, board_id, name, color, position, created_at, updated_at, name_key FROM board_columns WHERE board_id = $1 ORDER BY position
`

func (q *Queries) ListColumns(ctx context.Context, boardID uuid.UUID) ([]BoardColumn, error) {
	rows, err := q.db.Query(ctx, listColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardColumn
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NameKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxBoardPosition = `-- name: MaxBoardPosition :one
SELECT coalesce(max(position), 0)::double precision FROM boards WHERE project_id = $1
`

func (q *Queries) MaxBoardPosition(ctx context.Context, projectID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxBoardPosition, projectID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const maxColumnPosition = `-- name: MaxColumnPosition :one
SELECT coalesce(max(position), 0)::double precision FROM board_columns WHERE board_id = $1
`

func (q *Queries) MaxColumnPosition(ctx context.Context, boardID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxColumnPosition, boardID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const setBoardDoneColumn = `-- name: SetBoardDoneColumn :one
UPDATE boards
SET done_column_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode
`

type SetBoardDoneColumnParams struct {
	ID           uuid.UUID  `json:"id"`
	DoneColumnID *uuid.UUID `json:"done_column_id"`
}

func (q *Queries) SetBoardDoneColumn(ctx context.Context, arg SetBoardDoneColumnParams) (Board, error) {
	row := q.db.QueryRow(ctx, setBoardDoneColumn, arg.ID, arg.DoneColumnID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneColumnID,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IconMode,
	)
	return i, err
}

const setBoardSlug = `-- name: SetBoardSlug :exec
UPDATE boards SET slug = $2 WHERE id = $1
`

type SetBoardSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) SetBoardSlug(ctx context.Context, arg SetBoardSlugParams) error {
	_, err := q.db.Exec(ctx, setBoardSlug, arg.ID, arg.Slug)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = $2, position = $3, icon = $4, color = $5, icon_mode = $6, updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, position, created_at, updated_at, done_column_id, slug, icon, color, icon_mode
`

type UpdateBoardParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Position float64   `json:"position"`
	Icon     string    `json:"icon"`
	Color    string    `json:"color"`
	IconMode string    `json:"icon_mode"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.Icon,
		arg.Color,
		arg.IconMode,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DoneColumnID,
		&i.Slug,
		&i.Icon,
		&i.Color,
		&i.IconMode,
	)
	return i, err
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE board_columns
SET name = $2,
    name_key = CASE WHEN name = $2 THEN name_key ELSE NULL END,
    color = $3, position = $4, updated_at = now()
WHERE id = $1
RETURNING id, board_id, name, color, position, created_at, updated_at, name_key
`

type UpdateColumnParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Color    string    `json:"color"`
	Position float64   `json:"position"`
}

// UpdateColumn drops name_key when the name actually changes: a column the user
// renamed must keep that name in every language. Re-saving the same text (a
// colour edit or a reorder both go through here) is not a rename, so the key
// survives those.
func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Position,
	)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NameKey,
	)
	return i, err
}
