// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conference_recordings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeConferenceRecording = `-- name: ActiveConferenceRecording :one
SELECT r.id, r.conference_id, r.file_path, r.file_name, r.size_bytes, r.duration_sec, r.started_at, r.expires_at, r.created_at, r.egress_id, r.status, r.error, r.started_by, r.ended_at, u.name AS started_by_name
FROM conference_recordings r
LEFT JOIN users u ON u.id = r.started_by
WHERE r.conference_id = $1 AND r.status = 'active'
`

type ActiveConferenceRecordingRow struct {
	ID            uuid.UUID  `json:"id"`
	ConferenceID  uuid.UUID  `json:"conference_id"`
	FilePath      string     `json:"file_path"`
	FileName      string     `json:"file_name"`
	SizeBytes     int64      `json:"size_bytes"`
	DurationSec   int32      `json:"duration_sec"`
	StartedAt     time.Time  `json:"started_at"`
	ExpiresAt     *time.Time `json:"expires_at"`
	CreatedAt     time.Time  `json:"created_at"`
	EgressID      string     `json:"egress_id"`
	Status        string     `json:"status"`
	Error         string     `json:"error"`
	StartedBy     *uuid.UUID `json:"started_by"`
	EndedAt       *time.Time `json:"ended_at"`
	StartedByName *string    `json:"started_by_name"`
}

// ActiveConferenceRecording is the row behind the red "recording" indicator, and
// the same query that refuses a second start. Joining the name here keeps the
// room-state snapshot one statement: the indicator says who is recording, and an
// anonymous one would defeat its purpose.
func (q *Queries) ActiveConferenceRecording(ctx context.Context, conferenceID uuid.UUID) (ActiveConferenceRecordingRow, error) {
	row := q.db.QueryRow(ctx, activeConferenceRecording, conferenceID)
	var i ActiveConferenceRecordingRow
	err := row.Scan(
		&i.ID,
		&i.ConferenceID,
		&i.FilePath,
		&i.FileName,
		&i.SizeBytes,
		&i.DurationSec,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EgressID,
		&i.Status,
		&i.Error,
		&i.StartedBy,
		&i.EndedAt,
		&i.StartedByName,
	)
	return i, err
}

const conferenceForRecording = `-- name: ConferenceForRecording :one
SELECT c.id, c.workspace_id, c.task_id, c.created_by, c.title, c.description, c.scheduled_at, c.started_at, c.ended_at, c.status, c.recording_ttl_days, c.created_at, c.updated_at
FROM conference_recordings r
JOIN conferences c ON c.id = r.conference_id
WHERE r.id = $1
`

// ConferenceForRecording resolves the conference a recording belongs to, so the
// download route can authorize by workspace membership in one round trip —
// the same shape as ConferenceForMessageAttachment next door.
func (q *Queries) ConferenceForRecording(ctx context.Context, id uuid.UUID) (Conference, error) {
	row := q.db.QueryRow(ctx, conferenceForRecording, id)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.RecordingTtlDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConferenceRecording = `-- name: CreateConferenceRecording :one

INSERT INTO conference_recordings (conference_id, egress_id, file_path, file_name, started_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, conference_id, file_path, file_name, size_bytes, duration_sec, started_at, expires_at, created_at, egress_id, status, error, started_by, ended_at
`

type CreateConferenceRecordingParams struct {
	ConferenceID uuid.UUID  `json:"conference_id"`
	EgressID     string     `json:"egress_id"`
	FilePath     string     `json:"file_path"`
	FileName     string     `json:"file_name"`
	StartedBy    *uuid.UUID `json:"started_by"`
}

// Server-side recordings of a conference (#2864, subtask #2877).
//
// A row is created the moment LiveKit accepts the egress job, not when the file
// appears: until then the recording exists only inside the egress worker, and a
// row is what lets us stop it, show the red dot to everyone in the room, and
// notice that it died. Size, duration and expiry are filled in later by the
// poller — see FinishConferenceRecording.
// CreateConferenceRecording opens the in-flight row. The unique partial index on
// (conference_id) WHERE status = 'active' does the "one at a time" check for us:
// two hosts pressing record simultaneously means the loser gets a unique
// violation here rather than a second egress worker nobody is tracking.
func (q *Queries) CreateConferenceRecording(ctx context.Context, arg CreateConferenceRecordingParams) (ConferenceRecording, error) {
	row := q.db.QueryRow(ctx, createConferenceRecording,
		arg.ConferenceID,
		arg.EgressID,
		arg.FilePath,
		arg.FileName,
		arg.StartedBy,
	)
	var i ConferenceRecording
	err := row.Scan(
		&i.ID,
		&i.ConferenceID,
		&i.FilePath,
		&i.FileName,
		&i.SizeBytes,
		&i.DurationSec,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EgressID,
		&i.Status,
		&i.Error,
		&i.StartedBy,
		&i.EndedAt,
	)
	return i, err
}

const deleteConferenceRecording = `-- name: DeleteConferenceRecording :exec
DELETE FROM conference_recordings WHERE id = $1
`

func (q *Queries) DeleteConferenceRecording(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConferenceRecording, id)
	return err
}

const finishConferenceRecording = `-- name: FinishConferenceRecording :one
UPDATE conference_recordings
SET status       = $1,
    size_bytes   = $2,
    duration_sec = $3,
    error        = $4,
    ended_at     = now(),
    expires_at   = CASE WHEN $5::int > 0
                        THEN now() + make_interval(days => $5::int)
                        ELSE NULL END
WHERE id = $6 AND status = 'active'
RETURNING id, conference_id, file_path, file_name, size_bytes, duration_sec, started_at, expires_at, created_at, egress_id, status, error, started_by, ended_at
`

type FinishConferenceRecordingParams struct {
	Status      string    `json:"status"`
	SizeBytes   int64     `json:"size_bytes"`
	DurationSec int32     `json:"duration_sec"`
	Error       string    `json:"error"`
	TtlDays     int32     `json:"ttl_days"`
	ID          uuid.UUID `json:"id"`
}

// FinishConferenceRecording closes a row: one statement for success and for
// failure, because the difference between them is the status and the error text
// and nothing else about the row's lifecycle.
//
// WHERE status = 'active' is the guard that matters. The poller and an explicit
// stop can both reach a recording in the same second; without it the slower one
// would overwrite the finished row — resetting ended_at, and pushing expires_at
// a fresh TTL into the future so the sweeper never picks the file up.
//
// expires_at follows conferences.recording_ttl_days, where 0 means "keep
// indefinitely" — NULL here, which is also what the sweeper's index skips.
func (q *Queries) FinishConferenceRecording(ctx context.Context, arg FinishConferenceRecordingParams) (ConferenceRecording, error) {
	row := q.db.QueryRow(ctx, finishConferenceRecording,
		arg.Status,
		arg.SizeBytes,
		arg.DurationSec,
		arg.Error,
		arg.TtlDays,
		arg.ID,
	)
	var i ConferenceRecording
	err := row.Scan(
		&i.ID,
		&i.ConferenceID,
		&i.FilePath,
		&i.FileName,
		&i.SizeBytes,
		&i.DurationSec,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EgressID,
		&i.Status,
		&i.Error,
		&i.StartedBy,
		&i.EndedAt,
	)
	return i, err
}

const getConferenceRecording = `-- name: GetConferenceRecording :one
SELECT id, conference_id, file_path, file_name, size_bytes, duration_sec, started_at, expires_at, created_at, egress_id, status, error, started_by, ended_at FROM conference_recordings WHERE id = $1
`

func (q *Queries) GetConferenceRecording(ctx context.Context, id uuid.UUID) (ConferenceRecording, error) {
	row := q.db.QueryRow(ctx, getConferenceRecording, id)
	var i ConferenceRecording
	err := row.Scan(
		&i.ID,
		&i.ConferenceID,
		&i.FilePath,
		&i.FileName,
		&i.SizeBytes,
		&i.DurationSec,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.EgressID,
		&i.Status,
		&i.Error,
		&i.StartedBy,
		&i.EndedAt,
	)
	return i, err
}

const listActiveRecordings = `-- name: ListActiveRecordings :many
SELECT r.id, r.conference_id, r.file_path, r.file_name, r.size_bytes, r.duration_sec, r.started_at, r.expires_at, r.created_at, r.egress_id, r.status, r.error, r.started_by, r.ended_at, c.recording_ttl_days
FROM conference_recordings r
JOIN conferences c ON c.id = r.conference_id
WHERE r.status = 'active'
ORDER BY r.started_at
`

type ListActiveRecordingsRow struct {
	ID               uuid.UUID  `json:"id"`
	ConferenceID     uuid.UUID  `json:"conference_id"`
	FilePath         string     `json:"file_path"`
	FileName         string     `json:"file_name"`
	SizeBytes        int64      `json:"size_bytes"`
	DurationSec      int32      `json:"duration_sec"`
	StartedAt        time.Time  `json:"started_at"`
	ExpiresAt        *time.Time `json:"expires_at"`
	CreatedAt        time.Time  `json:"created_at"`
	EgressID         string     `json:"egress_id"`
	Status           string     `json:"status"`
	Error            string     `json:"error"`
	StartedBy        *uuid.UUID `json:"started_by"`
	EndedAt          *time.Time `json:"ended_at"`
	RecordingTtlDays int32      `json:"recording_ttl_days"`
}

// ListActiveRecordings feeds the poller: every row still believed to be running,
// with the TTL it will need at the finish line. The TTL is carried along rather
// than fetched per row because the poller would otherwise do one GetConference
// per recording every minute to read a single integer.
func (q *Queries) ListActiveRecordings(ctx context.Context) ([]ListActiveRecordingsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRecordings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRecordingsRow
	for rows.Next() {
		var i ListActiveRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConferenceID,
			&i.FilePath,
			&i.FileName,
			&i.SizeBytes,
			&i.DurationSec,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.EgressID,
			&i.Status,
			&i.Error,
			&i.StartedBy,
			&i.EndedAt,
			&i.RecordingTtlDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConferenceRecordingPaths = `-- name: ListConferenceRecordingPaths :many
SELECT file_path FROM conference_recordings WHERE conference_id = $1
`

// ListConferenceRecordingPaths lists the files to unlink when a whole conference
// goes away: the rows themselves leave by ON DELETE CASCADE, which is precisely
// why the paths have to be read *before* the delete.
func (q *Queries) ListConferenceRecordingPaths(ctx context.Context, conferenceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listConferenceRecordingPaths, conferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConferenceRecordings = `-- name: ListConferenceRecordings :many
SELECT r.id, r.conference_id, r.file_path, r.file_name, r.size_bytes, r.duration_sec, r.started_at, r.expires_at, r.created_at, r.egress_id, r.status, r.error, r.started_by, r.ended_at, u.name AS started_by_name
FROM conference_recordings r
LEFT JOIN users u ON u.id = r.started_by
WHERE r.conference_id = $1
ORDER BY r.started_at DESC
`

type ListConferenceRecordingsRow struct {
	ID            uuid.UUID  `json:"id"`
	ConferenceID  uuid.UUID  `json:"conference_id"`
	FilePath      string     `json:"file_path"`
	FileName      string     `json:"file_name"`
	SizeBytes     int64      `json:"size_bytes"`
	DurationSec   int32      `json:"duration_sec"`
	StartedAt     time.Time  `json:"started_at"`
	ExpiresAt     *time.Time `json:"expires_at"`
	CreatedAt     time.Time  `json:"created_at"`
	EgressID      string     `json:"egress_id"`
	Status        string     `json:"status"`
	Error         string     `json:"error"`
	StartedBy     *uuid.UUID `json:"started_by"`
	EndedAt       *time.Time `json:"ended_at"`
	StartedByName *string    `json:"started_by_name"`
}

// ListConferenceRecordings backs the list on the conference card. It returns the
// failed rows too — a recording somebody started and never got is exactly what
// they will come asking about, and hiding the row would leave the answer only in
// the container logs.
func (q *Queries) ListConferenceRecordings(ctx context.Context, conferenceID uuid.UUID) ([]ListConferenceRecordingsRow, error) {
	rows, err := q.db.Query(ctx, listConferenceRecordings, conferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConferenceRecordingsRow
	for rows.Next() {
		var i ListConferenceRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConferenceID,
			&i.FilePath,
			&i.FileName,
			&i.SizeBytes,
			&i.DurationSec,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.EgressID,
			&i.Status,
			&i.Error,
			&i.StartedBy,
			&i.EndedAt,
			&i.StartedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRecordings = `-- name: ListExpiredRecordings :many
SELECT id, conference_id, file_path, file_name, size_bytes, duration_sec, started_at, expires_at, created_at, egress_id, status, error, started_by, ended_at FROM conference_recordings
WHERE expires_at IS NOT NULL AND expires_at < now()
ORDER BY expires_at
LIMIT $1
`

// ListExpiredRecordings drives the TTL sweeper. Limited on purpose: a tick that
// has to delete a thousand files should take a thousand files' worth of ticks
// rather than hold the worker for minutes on its first run after a TTL change.
//
// Failed rows are swept as well — a recording that died mid-way still left a
// partial file in the uploads volume, and it is the one nobody will ever ask to
// keep.
func (q *Queries) ListExpiredRecordings(ctx context.Context, limit int32) ([]ConferenceRecording, error) {
	rows, err := q.db.Query(ctx, listExpiredRecordings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConferenceRecording
	for rows.Next() {
		var i ConferenceRecording
		if err := rows.Scan(
			&i.ID,
			&i.ConferenceID,
			&i.FilePath,
			&i.FileName,
			&i.SizeBytes,
			&i.DurationSec,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.EgressID,
			&i.Status,
			&i.Error,
			&i.StartedBy,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
