// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conferences.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveConferenceParticipants = `-- name: CountActiveConferenceParticipants :one
SELECT count(*) FROM conference_participants
WHERE conference_id = $1 AND joined_at IS NOT NULL AND left_at IS NULL
`

func (q *Queries) CountActiveConferenceParticipants(ctx context.Context, conferenceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveConferenceParticipants, conferenceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConference = `-- name: CreateConference :one
INSERT INTO conferences (workspace_id, task_id, created_by, title, description, scheduled_at, recording_ttl_days)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, task_id, created_by, title, description, scheduled_at, started_at, ended_at, status, recording_ttl_days, created_at, updated_at
`

type CreateConferenceParams struct {
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	TaskID           *uuid.UUID `json:"task_id"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	ScheduledAt      *time.Time `json:"scheduled_at"`
	RecordingTtlDays int32      `json:"recording_ttl_days"`
}

func (q *Queries) CreateConference(ctx context.Context, arg CreateConferenceParams) (Conference, error) {
	row := q.db.QueryRow(ctx, createConference,
		arg.WorkspaceID,
		arg.TaskID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
		arg.RecordingTtlDays,
	)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.RecordingTtlDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConference = `-- name: DeleteConference :exec
DELETE FROM conferences WHERE id = $1
`

func (q *Queries) DeleteConference(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConference, id)
	return err
}

const endAllConferenceParticipants = `-- name: EndAllConferenceParticipants :exec
UPDATE conference_participants
SET left_at = now()
WHERE conference_id = $1 AND joined_at IS NOT NULL AND left_at IS NULL
`

// EndAllConferenceParticipants stamps everyone still in the room as gone, used
// when a moderator ends the session for all (#2879). Without it the participant
// rows keep saying people are present, and each client would flip itself back to
// "in room" and rejoin the call the End button just closed.
func (q *Queries) EndAllConferenceParticipants(ctx context.Context, conferenceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, endAllConferenceParticipants, conferenceID)
	return err
}

const getConference = `-- name: GetConference :one
SELECT id, workspace_id, task_id, created_by, title, description, scheduled_at, started_at, ended_at, status, recording_ttl_days, created_at, updated_at FROM conferences WHERE id = $1
`

func (q *Queries) GetConference(ctx context.Context, id uuid.UUID) (Conference, error) {
	row := q.db.QueryRow(ctx, getConference, id)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.RecordingTtlDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConferenceParticipant = `-- name: GetConferenceParticipant :one
SELECT conference_id, user_id, role, invited_at, joined_at, left_at, force_muted FROM conference_participants WHERE conference_id = $1 AND user_id = $2
`

type GetConferenceParticipantParams struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) GetConferenceParticipant(ctx context.Context, arg GetConferenceParticipantParams) (ConferenceParticipant, error) {
	row := q.db.QueryRow(ctx, getConferenceParticipant, arg.ConferenceID, arg.UserID)
	var i ConferenceParticipant
	err := row.Scan(
		&i.ConferenceID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.ForceMuted,
	)
	return i, err
}

const inviteConferenceParticipant = `-- name: InviteConferenceParticipant :one
INSERT INTO conference_participants (conference_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (conference_id, user_id) DO UPDATE
SET invited_at = now(), left_at = NULL
RETURNING conference_id, user_id, role, invited_at, joined_at, left_at, force_muted
`

type InviteConferenceParticipantParams struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	UserID       uuid.UUID `json:"user_id"`
	Role         string    `json:"role"`
}

// InviteConferenceParticipant adds an invitee, or re-invites someone who had
// left. ON CONFLICT rather than an existence check: invitations are sent from
// several places at once (the dialog, the notification, an /invite call) and
// the loser of that race must not get a unique-violation 500. The role is left
// alone on conflict — re-inviting the host must not demote them to member.
func (q *Queries) InviteConferenceParticipant(ctx context.Context, arg InviteConferenceParticipantParams) (ConferenceParticipant, error) {
	row := q.db.QueryRow(ctx, inviteConferenceParticipant, arg.ConferenceID, arg.UserID, arg.Role)
	var i ConferenceParticipant
	err := row.Scan(
		&i.ConferenceID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.ForceMuted,
	)
	return i, err
}

const joinConferenceParticipant = `-- name: JoinConferenceParticipant :one
INSERT INTO conference_participants (conference_id, user_id, role, joined_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (conference_id, user_id) DO UPDATE
SET joined_at = now(), left_at = NULL
RETURNING conference_id, user_id, role, invited_at, joined_at, left_at, force_muted
`

type JoinConferenceParticipantParams struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	UserID       uuid.UUID `json:"user_id"`
	Role         string    `json:"role"`
}

// JoinConferenceParticipant records attendance. It doubles as the invite for an
// open conference: a member of the workspace may walk into a call they were not
// explicitly invited to, and the row is created on the spot rather than the
// join being refused.
func (q *Queries) JoinConferenceParticipant(ctx context.Context, arg JoinConferenceParticipantParams) (ConferenceParticipant, error) {
	row := q.db.QueryRow(ctx, joinConferenceParticipant, arg.ConferenceID, arg.UserID, arg.Role)
	var i ConferenceParticipant
	err := row.Scan(
		&i.ConferenceID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.ForceMuted,
	)
	return i, err
}

const leaveConferenceParticipant = `-- name: LeaveConferenceParticipant :one
UPDATE conference_participants
SET left_at = now()
WHERE conference_id = $1 AND user_id = $2
RETURNING conference_id, user_id, role, invited_at, joined_at, left_at, force_muted
`

type LeaveConferenceParticipantParams struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) LeaveConferenceParticipant(ctx context.Context, arg LeaveConferenceParticipantParams) (ConferenceParticipant, error) {
	row := q.db.QueryRow(ctx, leaveConferenceParticipant, arg.ConferenceID, arg.UserID)
	var i ConferenceParticipant
	err := row.Scan(
		&i.ConferenceID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.ForceMuted,
	)
	return i, err
}

const listConferenceParticipants = `-- name: ListConferenceParticipants :many
SELECT p.conference_id, p.user_id, p.role, p.invited_at, p.joined_at, p.left_at, p.force_muted, u.name AS user_name, u.email AS user_email
FROM conference_participants p
JOIN users u ON u.id = p.user_id
WHERE p.conference_id = $1
ORDER BY p.role, u.name
`

type ListConferenceParticipantsRow struct {
	ConferenceID uuid.UUID  `json:"conference_id"`
	UserID       uuid.UUID  `json:"user_id"`
	Role         string     `json:"role"`
	InvitedAt    time.Time  `json:"invited_at"`
	JoinedAt     *time.Time `json:"joined_at"`
	LeftAt       *time.Time `json:"left_at"`
	ForceMuted   bool       `json:"force_muted"`
	UserName     string     `json:"user_name"`
	UserEmail    string     `json:"user_email"`
}

func (q *Queries) ListConferenceParticipants(ctx context.Context, conferenceID uuid.UUID) ([]ListConferenceParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listConferenceParticipants, conferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConferenceParticipantsRow
	for rows.Next() {
		var i ListConferenceParticipantsRow
		if err := rows.Scan(
			&i.ConferenceID,
			&i.UserID,
			&i.Role,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.LeftAt,
			&i.ForceMuted,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConferences = `-- name: ListConferences :many
SELECT c.id, c.workspace_id, c.task_id, c.created_by, c.title, c.description, c.scheduled_at, c.started_at, c.ended_at, c.status, c.recording_ttl_days, c.created_at, c.updated_at,
       u.name AS created_by_name,
       (SELECT count(*) FROM conference_participants p WHERE p.conference_id = c.id) AS participant_count,
       (SELECT count(*) FROM conference_participants p
         WHERE p.conference_id = c.id AND p.joined_at IS NOT NULL AND p.left_at IS NULL) AS active_count
FROM conferences c
LEFT JOIN users u ON u.id = c.created_by
WHERE c.workspace_id = $1
  AND ($2::text IS NULL OR c.status = $2::text)
ORDER BY (c.status = 'live') DESC,
         c.scheduled_at ASC NULLS LAST,
         c.created_at DESC
`

type ListConferencesParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Status      *string   `json:"status"`
}

type ListConferencesRow struct {
	ID               uuid.UUID  `json:"id"`
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	TaskID           *uuid.UUID `json:"task_id"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	ScheduledAt      *time.Time `json:"scheduled_at"`
	StartedAt        *time.Time `json:"started_at"`
	EndedAt          *time.Time `json:"ended_at"`
	Status           string     `json:"status"`
	RecordingTtlDays int32      `json:"recording_ttl_days"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	CreatedByName    *string    `json:"created_by_name"`
	ParticipantCount int64      `json:"participant_count"`
	ActiveCount      int64      `json:"active_count"`
}

// ListConferences returns the workspace's conferences with the two numbers the
// list screen shows next to every row: how many people are invited and how many
// are in the room right now. Counting them here rather than per-row keeps
// opening the section one round trip instead of one plus two per conference.
//
// Order puts live calls first — you join the meeting that is happening, not the
// one planned for Thursday — then the nearest scheduled, then the archive.
func (q *Queries) ListConferences(ctx context.Context, arg ListConferencesParams) ([]ListConferencesRow, error) {
	rows, err := q.db.Query(ctx, listConferences, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConferencesRow
	for rows.Next() {
		var i ListConferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.RecordingTtlDays,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.ParticipantCount,
			&i.ActiveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConferencesByTask = `-- name: ListConferencesByTask :many
SELECT id, workspace_id, task_id, created_by, title, description, scheduled_at, started_at, ended_at, status, recording_ttl_days, created_at, updated_at FROM conferences WHERE task_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListConferencesByTask(ctx context.Context, taskID *uuid.UUID) ([]Conference, error) {
	rows, err := q.db.Query(ctx, listConferencesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conference
	for rows.Next() {
		var i Conference
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.RecordingTtlDays,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseConference = `-- name: PauseConference :one
UPDATE conferences
SET status = 'scheduled', started_at = NULL, ended_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'live'
RETURNING id, workspace_id, task_id, created_by, title, description, scheduled_at, started_at, ended_at, status, recording_ttl_days, created_at, updated_at
`

// PauseConference ends the current session without ending the conference
// (#2879): the room goes back to 'scheduled' so it can be joined again, which is
// what lets one conference serve a daily standup. started_at/ended_at are wiped
// so the next session is timed from its own start. Only a live call is paused;
// an already-idle one returns no row, which the caller treats as success.
func (q *Queries) PauseConference(ctx context.Context, id uuid.UUID) (Conference, error) {
	row := q.db.QueryRow(ctx, pauseConference, id)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.RecordingTtlDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeConferenceParticipant = `-- name: RemoveConferenceParticipant :exec
DELETE FROM conference_participants WHERE conference_id = $1 AND user_id = $2
`

type RemoveConferenceParticipantParams struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveConferenceParticipant(ctx context.Context, arg RemoveConferenceParticipantParams) error {
	_, err := q.db.Exec(ctx, removeConferenceParticipant, arg.ConferenceID, arg.UserID)
	return err
}

const setConferenceParticipantMuted = `-- name: SetConferenceParticipantMuted :one
UPDATE conference_participants
SET force_muted = $3
WHERE conference_id = $1 AND user_id = $2
RETURNING conference_id, user_id, role, invited_at, joined_at, left_at, force_muted
`

type SetConferenceParticipantMutedParams struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	UserID       uuid.UUID `json:"user_id"`
	ForceMuted   bool      `json:"force_muted"`
}

func (q *Queries) SetConferenceParticipantMuted(ctx context.Context, arg SetConferenceParticipantMutedParams) (ConferenceParticipant, error) {
	row := q.db.QueryRow(ctx, setConferenceParticipantMuted, arg.ConferenceID, arg.UserID, arg.ForceMuted)
	var i ConferenceParticipant
	err := row.Scan(
		&i.ConferenceID,
		&i.UserID,
		&i.Role,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.LeftAt,
		&i.ForceMuted,
	)
	return i, err
}

const startConference = `-- name: StartConference :one
UPDATE conferences
SET status = 'live', started_at = COALESCE(started_at, now()), ended_at = NULL, updated_at = now()
WHERE id = $1 AND status <> 'live'
RETURNING id, workspace_id, task_id, created_by, title, description, scheduled_at, started_at, ended_at, status, recording_ttl_days, created_at, updated_at
`

// StartConference (re)activates a room. It is idempotent on purpose: everyone's
// client calls join at once when a meeting begins, and the first caller is
// whoever's network was fastest — the COALESCE keeps started_at at that first
// join instead of letting the last racer overwrite it. status <> 'live' (rather
// than = 'scheduled') is what makes a conference reusable (#2879): a call that
// was paused back to 'scheduled' — or a legacy 'ended' one — starts again on the
// next join instead of being a dead room. ended_at is cleared so a restarted
// call does not carry the previous session's end time.
func (q *Queries) StartConference(ctx context.Context, id uuid.UUID) (Conference, error) {
	row := q.db.QueryRow(ctx, startConference, id)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.RecordingTtlDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConference = `-- name: UpdateConference :one
UPDATE conferences
SET title = $2, description = $3, scheduled_at = $4, task_id = $5, recording_ttl_days = $6, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, task_id, created_by, title, description, scheduled_at, started_at, ended_at, status, recording_ttl_days, created_at, updated_at
`

type UpdateConferenceParams struct {
	ID               uuid.UUID  `json:"id"`
	Title            string     `json:"title"`
	Description      string     `json:"description"`
	ScheduledAt      *time.Time `json:"scheduled_at"`
	TaskID           *uuid.UUID `json:"task_id"`
	RecordingTtlDays int32      `json:"recording_ttl_days"`
}

// UpdateConference is a full replace of the editable fields (the same shape the
// other Update handlers in this codebase use); status transitions have their own
// statements below so a PATCH of the title can never take a call off the air.
func (q *Queries) UpdateConference(ctx context.Context, arg UpdateConferenceParams) (Conference, error) {
	row := q.db.QueryRow(ctx, updateConference,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ScheduledAt,
		arg.TaskID,
		arg.RecordingTtlDays,
	)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.RecordingTtlDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workspaceIDForConference = `-- name: WorkspaceIDForConference :one
SELECT workspace_id FROM conferences WHERE id = $1
`

func (q *Queries) WorkspaceIDForConference(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, workspaceIDForConference, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}
