// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_versions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (document_id, revision, author_id, title, content, preview, label, manual)
VALUES (
    $1,
    (SELECT coalesce(max(v.revision), 0) + 1 FROM document_versions v WHERE v.document_id = $1),
    $2, $3, $4, $5, $6, $7
)
RETURNING id, document_id, revision, author_id, title, content, preview, label, manual, created_at, updated_at
`

type CreateDocumentVersionParams struct {
	DocumentID uuid.UUID  `json:"document_id"`
	AuthorID   *uuid.UUID `json:"author_id"`
	Title      string     `json:"title"`
	Content    []byte     `json:"content"`
	Preview    string     `json:"preview"`
	Label      string     `json:"label"`
	Manual     bool       `json:"manual"`
}

// CreateDocumentVersion appends a snapshot. The revision is picked inside the
// statement rather than read first and incremented in Go: two autosaves from two
// tabs land here concurrently, and a read-then-write would hand them the same
// number — which the unique constraint would turn into a failed save of a
// document the user already typed.
func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Preview,
		arg.Label,
		arg.Manual,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Revision,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Preview,
		&i.Label,
		&i.Manual,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const extendDocumentVersion = `-- name: ExtendDocumentVersion :one
UPDATE document_versions
SET content = $2, preview = $3, title = $4, updated_at = now()
WHERE id = $1
RETURNING id, document_id, revision, author_id, title, content, preview, label, manual, created_at, updated_at
`

type ExtendDocumentVersionParams struct {
	ID      uuid.UUID `json:"id"`
	Content []byte    `json:"content"`
	Preview string    `json:"preview"`
	Title   string    `json:"title"`
}

// ExtendDocumentVersion folds another save of the same editing session into the
// version that session opened, instead of adding a row per autosave debounce.
func (q *Queries) ExtendDocumentVersion(ctx context.Context, arg ExtendDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, extendDocumentVersion,
		arg.ID,
		arg.Content,
		arg.Preview,
		arg.Title,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Revision,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Preview,
		&i.Label,
		&i.Manual,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, revision, author_id, title, content, preview, label, manual, created_at, updated_at FROM document_versions WHERE id = $1
`

func (q *Queries) GetDocumentVersion(ctx context.Context, id uuid.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Revision,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Preview,
		&i.Label,
		&i.Manual,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestDocumentVersion = `-- name: LatestDocumentVersion :one
SELECT id, document_id, revision, author_id, title, content, preview, label, manual, created_at, updated_at FROM document_versions WHERE document_id = $1 ORDER BY revision DESC LIMIT 1
`

// LatestDocumentVersion is the row the content endpoint checks on every save to
// decide whether this edit belongs to the open session or starts a new one.
func (q *Queries) LatestDocumentVersion(ctx context.Context, documentID uuid.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, latestDocumentVersion, documentID)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Revision,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.Preview,
		&i.Label,
		&i.Manual,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT v.id, v.document_id, v.revision, v.author_id, v.title, v.preview, v.label, v.manual,
       v.created_at, v.updated_at,
       u.name AS author_name, u.email AS author_email
FROM document_versions v
LEFT JOIN users u ON u.id = v.author_id
WHERE v.document_id = $1
ORDER BY v.revision DESC
`

type ListDocumentVersionsRow struct {
	ID          uuid.UUID  `json:"id"`
	DocumentID  uuid.UUID  `json:"document_id"`
	Revision    int32      `json:"revision"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Preview     string     `json:"preview"`
	Label       string     `json:"label"`
	Manual      bool       `json:"manual"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	AuthorName  *string    `json:"author_name"`
	AuthorEmail *string    `json:"author_email"`
}

// ListDocumentVersions returns the journal, newest first. Content is left out on
// purpose: a document is up to a megabyte of ProseMirror JSON and the journal
// shows fifty of them — the panel asks for a body only when a version is opened
// or compared.
func (q *Queries) ListDocumentVersions(ctx context.Context, documentID uuid.UUID) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentVersionsRow
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Revision,
			&i.AuthorID,
			&i.Title,
			&i.Preview,
			&i.Label,
			&i.Manual,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDocumentVersions = `-- name: PruneDocumentVersions :exec
DELETE FROM document_versions
WHERE document_versions.document_id = $1
  AND document_versions.manual = false
  AND document_versions.id NOT IN (
      SELECT v.id FROM document_versions v
      WHERE v.document_id = $1 AND v.manual = false
      ORDER BY v.revision DESC
      LIMIT $2
  )
`

type PruneDocumentVersionsParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Keep       int32     `json:"keep"`
}

// PruneDocumentVersions caps the automatic history of one document, keeping the
// newest @keep session snapshots. Manual versions are excluded from both the
// deletion and the count: they are milestones somebody asked to keep, and an
// afternoon of typing must not push them out of the journal.
func (q *Queries) PruneDocumentVersions(ctx context.Context, arg PruneDocumentVersionsParams) error {
	_, err := q.db.Exec(ctx, pruneDocumentVersions, arg.DocumentID, arg.Keep)
	return err
}
