// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_task_links.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocumentTaskLink = `-- name: CreateDocumentTaskLink :one
INSERT INTO document_task_links (document_id, task_id, block_id, quote, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (document_id, task_id, block_id)
DO UPDATE SET quote = EXCLUDED.quote
RETURNING id, document_id, task_id, block_id, quote, created_by, created_at
`

type CreateDocumentTaskLinkParams struct {
	DocumentID uuid.UUID  `json:"document_id"`
	TaskID     uuid.UUID  `json:"task_id"`
	BlockID    string     `json:"block_id"`
	Quote      string     `json:"quote"`
	CreatedBy  *uuid.UUID `json:"created_by"`
}

// CreateDocumentTaskLink links a task to a document, optionally to one block in
// it. Re-linking the same pair refreshes the quote instead of failing: the button
// is in a panel that may be looking at a stale list, and "already linked" is not
// an error the user can act on — the state they asked for is the state they get.
func (q *Queries) CreateDocumentTaskLink(ctx context.Context, arg CreateDocumentTaskLinkParams) (DocumentTaskLink, error) {
	row := q.db.QueryRow(ctx, createDocumentTaskLink,
		arg.DocumentID,
		arg.TaskID,
		arg.BlockID,
		arg.Quote,
		arg.CreatedBy,
	)
	var i DocumentTaskLink
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.TaskID,
		&i.BlockID,
		&i.Quote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentTaskLink = `-- name: DeleteDocumentTaskLink :exec
DELETE FROM document_task_links WHERE id = $1
`

func (q *Queries) DeleteDocumentTaskLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTaskLink, id)
	return err
}

const getDocumentTaskLink = `-- name: GetDocumentTaskLink :one
SELECT id, document_id, task_id, block_id, quote, created_by, created_at FROM document_task_links WHERE id = $1
`

func (q *Queries) GetDocumentTaskLink(ctx context.Context, id uuid.UUID) (DocumentTaskLink, error) {
	row := q.db.QueryRow(ctx, getDocumentTaskLink, id)
	var i DocumentTaskLink
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.TaskID,
		&i.BlockID,
		&i.Quote,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentTaskLinks = `-- name: ListDocumentTaskLinks :many
SELECT l.id, l.document_id, l.task_id, l.block_id, l.quote, l.created_by, l.created_at,
       t.title AS task_title, t.board_id AS task_board_id, t.priority AS task_priority,
       t.completed_at AS task_completed_at
FROM document_task_links l
JOIN tasks t ON t.id = l.task_id
WHERE l.document_id = $1
ORDER BY l.created_at
`

type ListDocumentTaskLinksRow struct {
	ID              uuid.UUID  `json:"id"`
	DocumentID      uuid.UUID  `json:"document_id"`
	TaskID          uuid.UUID  `json:"task_id"`
	BlockID         string     `json:"block_id"`
	Quote           string     `json:"quote"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	TaskTitle       string     `json:"task_title"`
	TaskBoardID     uuid.UUID  `json:"task_board_id"`
	TaskPriority    int32      `json:"task_priority"`
	TaskCompletedAt *time.Time `json:"task_completed_at"`
}

// ListDocumentTaskLinks returns a document's links with enough of each task to
// render the row without a second round trip per link. board_id rides along
// because the panel's job is to navigate to the task, and the board is what the
// route needs.
func (q *Queries) ListDocumentTaskLinks(ctx context.Context, documentID uuid.UUID) ([]ListDocumentTaskLinksRow, error) {
	rows, err := q.db.Query(ctx, listDocumentTaskLinks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentTaskLinksRow
	for rows.Next() {
		var i ListDocumentTaskLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TaskID,
			&i.BlockID,
			&i.Quote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TaskTitle,
			&i.TaskBoardID,
			&i.TaskPriority,
			&i.TaskCompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDocumentLinks = `-- name: ListTaskDocumentLinks :many
SELECT l.id, l.document_id, l.task_id, l.block_id, l.quote, l.created_by, l.created_at,
       d.title AS document_title, d.icon AS document_icon, d.slug AS document_slug,
       d.workspace_id AS document_workspace_id
FROM document_task_links l
JOIN documents d ON d.id = l.document_id
WHERE l.task_id = $1
ORDER BY l.created_at
`

type ListTaskDocumentLinksRow struct {
	ID                  uuid.UUID  `json:"id"`
	DocumentID          uuid.UUID  `json:"document_id"`
	TaskID              uuid.UUID  `json:"task_id"`
	BlockID             string     `json:"block_id"`
	Quote               string     `json:"quote"`
	CreatedBy           *uuid.UUID `json:"created_by"`
	CreatedAt           time.Time  `json:"created_at"`
	DocumentTitle       string     `json:"document_title"`
	DocumentIcon        string     `json:"document_icon"`
	DocumentSlug        string     `json:"document_slug"`
	DocumentWorkspaceID uuid.UUID  `json:"document_workspace_id"`
}

// ListTaskDocumentLinks is the same relation read from the task side, for the
// "Документы" section of the task modal.
func (q *Queries) ListTaskDocumentLinks(ctx context.Context, taskID uuid.UUID) ([]ListTaskDocumentLinksRow, error) {
	rows, err := q.db.Query(ctx, listTaskDocumentLinks, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskDocumentLinksRow
	for rows.Next() {
		var i ListTaskDocumentLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.TaskID,
			&i.BlockID,
			&i.Quote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DocumentTitle,
			&i.DocumentIcon,
			&i.DocumentSlug,
			&i.DocumentWorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
