// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDocumentCommentReplies = `-- name: CountDocumentCommentReplies :one
SELECT count(*) FROM document_comments WHERE parent_id = $1
`

func (q *Queries) CountDocumentCommentReplies(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentCommentReplies, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentComment = `-- name: CreateDocumentComment :one
INSERT INTO document_comments (document_id, block_id, parent_id, author_id, body, quote)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, block_id, parent_id, author_id, body, quote, resolved_at, resolved_by, created_at, updated_at
`

type CreateDocumentCommentParams struct {
	DocumentID uuid.UUID  `json:"document_id"`
	BlockID    string     `json:"block_id"`
	ParentID   *uuid.UUID `json:"parent_id"`
	AuthorID   *uuid.UUID `json:"author_id"`
	Body       string     `json:"body"`
	Quote      string     `json:"quote"`
}

func (q *Queries) CreateDocumentComment(ctx context.Context, arg CreateDocumentCommentParams) (DocumentComment, error) {
	row := q.db.QueryRow(ctx, createDocumentComment,
		arg.DocumentID,
		arg.BlockID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
		arg.Quote,
	)
	var i DocumentComment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BlockID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.Quote,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocumentComment = `-- name: DeleteDocumentComment :exec
DELETE FROM document_comments WHERE id = $1
`

func (q *Queries) DeleteDocumentComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentComment, id)
	return err
}

const getDocumentComment = `-- name: GetDocumentComment :one
SELECT id, document_id, block_id, parent_id, author_id, body, quote, resolved_at, resolved_by, created_at, updated_at FROM document_comments WHERE id = $1
`

func (q *Queries) GetDocumentComment(ctx context.Context, id uuid.UUID) (DocumentComment, error) {
	row := q.db.QueryRow(ctx, getDocumentComment, id)
	var i DocumentComment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BlockID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.Quote,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentComments = `-- name: ListDocumentComments :many
SELECT c.id, c.document_id, c.block_id, c.parent_id, c.author_id, c.body, c.quote, c.resolved_at, c.resolved_by, c.created_at, c.updated_at, u.name AS author_name, u.email AS author_email
FROM document_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.document_id = $1
ORDER BY c.created_at
`

type ListDocumentCommentsRow struct {
	ID          uuid.UUID  `json:"id"`
	DocumentID  uuid.UUID  `json:"document_id"`
	BlockID     string     `json:"block_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Body        string     `json:"body"`
	Quote       string     `json:"quote"`
	ResolvedAt  *time.Time `json:"resolved_at"`
	ResolvedBy  *uuid.UUID `json:"resolved_by"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	AuthorName  *string    `json:"author_name"`
	AuthorEmail *string    `json:"author_email"`
}

// ListDocumentComments returns every comment on a document, roots and replies
// alike, oldest first. The client assembles the threads: it has to group them by
// block anyway to place them next to the text, and a second round trip per
// thread would make opening a discussed document a request storm.
func (q *Queries) ListDocumentComments(ctx context.Context, documentID uuid.UUID) ([]ListDocumentCommentsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentComments, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentCommentsRow
	for rows.Next() {
		var i ListDocumentCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.BlockID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.Quote,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentCommentResolved = `-- name: SetDocumentCommentResolved :one
UPDATE document_comments
SET resolved_at = $2, resolved_by = $3, updated_at = now()
WHERE id = $1
RETURNING id, document_id, block_id, parent_id, author_id, body, quote, resolved_at, resolved_by, created_at, updated_at
`

type SetDocumentCommentResolvedParams struct {
	ID         uuid.UUID  `json:"id"`
	ResolvedAt *time.Time `json:"resolved_at"`
	ResolvedBy *uuid.UUID `json:"resolved_by"`
}

// SetDocumentCommentResolved marks a thread done, or reopens it. The CHECK on
// the table keeps this from ever landing on a reply.
func (q *Queries) SetDocumentCommentResolved(ctx context.Context, arg SetDocumentCommentResolvedParams) (DocumentComment, error) {
	row := q.db.QueryRow(ctx, setDocumentCommentResolved, arg.ID, arg.ResolvedAt, arg.ResolvedBy)
	var i DocumentComment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BlockID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.Quote,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentCommentBody = `-- name: UpdateDocumentCommentBody :one
UPDATE document_comments SET body = $2, updated_at = now() WHERE id = $1 RETURNING id, document_id, block_id, parent_id, author_id, body, quote, resolved_at, resolved_by, created_at, updated_at
`

type UpdateDocumentCommentBodyParams struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

func (q *Queries) UpdateDocumentCommentBody(ctx context.Context, arg UpdateDocumentCommentBodyParams) (DocumentComment, error) {
	row := q.db.QueryRow(ctx, updateDocumentCommentBody, arg.ID, arg.Body)
	var i DocumentComment
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BlockID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.Quote,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
