// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDocumentChildren = `-- name: CountDocumentChildren :one
SELECT count(*) FROM documents WHERE parent_id = $1
`

func (q *Queries) CountDocumentChildren(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (workspace_id, project_id, parent_id, author_id, title, slug, icon, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, parent_id, project_id, author_id, title, slug, icon, content, position, created_at, updated_at
`

type CreateDocumentParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Icon        string     `json:"icon"`
	Position    float64    `json:"position"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ParentID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Icon,
		arg.Position,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocumentSubtree = `-- name: DeleteDocumentSubtree :exec
WITH RECURSIVE down AS (
    SELECT a.id FROM documents a WHERE a.id = $1
    UNION ALL
    SELECT d.id FROM documents d JOIN down ON d.parent_id = down.id
)
DELETE FROM documents WHERE documents.id IN (SELECT id FROM down)
`

// DeleteDocumentSubtree removes a document together with everything nested
// below it. One statement, so the parent_id RESTRICT never sees an intermediate
// state with a dangling child.
func (q *Queries) DeleteDocumentSubtree(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentSubtree, id)
	return err
}

const documentAncestorIDs = `-- name: DocumentAncestorIDs :many
WITH RECURSIVE up AS (
    SELECT a.id, a.parent_id FROM documents a WHERE a.id = $1
    UNION ALL
    SELECT d.id, d.parent_id FROM documents d JOIN up ON d.id = up.parent_id
)
SELECT id FROM up
`

// DocumentAncestorIDs returns the document itself followed by its ancestors, up
// to the root. Used to reject re-parenting a document into its own subtree,
// which would detach the branch from the tree and leave it orphaned in the
// table. The membership test is done in Go: sqlc's analyzer cannot resolve a
// recursive CTE referenced from inside a subquery, so EXISTS(...) here does not
// generate.
func (q *Queries) DocumentAncestorIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, documentAncestorIDs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const documentSlugExists = `-- name: DocumentSlugExists :one
SELECT EXISTS(SELECT 1 FROM documents WHERE workspace_id = $1 AND slug = $2)
`

type DocumentSlugExistsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Slug        string    `json:"slug"`
}

func (q *Queries) DocumentSlugExists(ctx context.Context, arg DocumentSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, documentSlugExists, arg.WorkspaceID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const documentsMissingSlug = `-- name: DocumentsMissingSlug :many
SELECT id, workspace_id, title FROM documents WHERE slug = ''
`

type DocumentsMissingSlugRow struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Title       string    `json:"title"`
}

func (q *Queries) DocumentsMissingSlug(ctx context.Context) ([]DocumentsMissingSlugRow, error) {
	rows, err := q.db.Query(ctx, documentsMissingSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentsMissingSlugRow
	for rows.Next() {
		var i DocumentsMissingSlugRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT id, workspace_id, parent_id, project_id, author_id, title, slug, icon, content, position, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBySlug = `-- name: GetDocumentBySlug :one
SELECT id, workspace_id, parent_id, project_id, author_id, title, slug, icon, content, position, created_at, updated_at FROM documents WHERE workspace_id = $1 AND slug = $2
`

type GetDocumentBySlugParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Slug        string    `json:"slug"`
}

func (q *Queries) GetDocumentBySlug(ctx context.Context, arg GetDocumentBySlugParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySlug, arg.WorkspaceID, arg.Slug)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, workspace_id, project_id, parent_id, author_id, title, slug, icon, position, created_at, updated_at
FROM documents
WHERE workspace_id = $1
ORDER BY position, created_at
`

type ListDocumentsRow struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Icon        string     `json:"icon"`
	Position    float64    `json:"position"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

// ListDocuments returns the workspace's documents as a flat list; the tree is
// assembled client-side (same call shape serves Android and MCP). Columns are
// listed explicitly to leave `content` behind: with D2 that column holds
// hundreds of KB per document, and SELECT * would turn opening the section into
// downloading every document in the workspace.
func (q *Queries) ListDocuments(ctx context.Context, workspaceID uuid.UUID) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ParentID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByProject = `-- name: ListDocumentsByProject :many
SELECT id, workspace_id, project_id, parent_id, author_id, title, slug, icon, position, created_at, updated_at
FROM documents
WHERE workspace_id = $1 AND project_id = $2
ORDER BY position, created_at
`

type ListDocumentsByProjectParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
}

type ListDocumentsByProjectRow struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Slug        string     `json:"slug"`
	Icon        string     `json:"icon"`
	Position    float64    `json:"position"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

func (q *Queries) ListDocumentsByProject(ctx context.Context, arg ListDocumentsByProjectParams) ([]ListDocumentsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByProject, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByProjectRow
	for rows.Next() {
		var i ListDocumentsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ParentID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Icon,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignProjectDocumentsWorkspace = `-- name: ReassignProjectDocumentsWorkspace :exec
UPDATE documents SET workspace_id = $2 WHERE project_id = $1
`

type ReassignProjectDocumentsWorkspaceParams struct {
	ProjectID   *uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
}

// ReassignProjectDocumentsWorkspace re-stamps workspace_id on documents tied to
// a project, used when the project is transferred between workspaces (mirrors
// notes). Without it a transferred project's documents keep the old
// workspace_id, and requireMember authorizes on exactly that column — the
// documents would stay visible to the team the project left.
func (q *Queries) ReassignProjectDocumentsWorkspace(ctx context.Context, arg ReassignProjectDocumentsWorkspaceParams) error {
	_, err := q.db.Exec(ctx, reassignProjectDocumentsWorkspace, arg.ProjectID, arg.WorkspaceID)
	return err
}

const setDocumentSlug = `-- name: SetDocumentSlug :exec
UPDATE documents SET slug = $2 WHERE id = $1
`

type SetDocumentSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) SetDocumentSlug(ctx context.Context, arg SetDocumentSlugParams) error {
	_, err := q.db.Exec(ctx, setDocumentSlug, arg.ID, arg.Slug)
	return err
}

const updateDocumentMeta = `-- name: UpdateDocumentMeta :one
UPDATE documents
SET title = $2, icon = $3, parent_id = $4, project_id = $5, position = $6, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, parent_id, project_id, author_id, title, slug, icon, content, position, created_at, updated_at
`

type UpdateDocumentMetaParams struct {
	ID        uuid.UUID  `json:"id"`
	Title     string     `json:"title"`
	Icon      string     `json:"icon"`
	ParentID  *uuid.UUID `json:"parent_id"`
	ProjectID *uuid.UUID `json:"project_id"`
	Position  float64    `json:"position"`
}

func (q *Queries) UpdateDocumentMeta(ctx context.Context, arg UpdateDocumentMetaParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentMeta,
		arg.ID,
		arg.Title,
		arg.Icon,
		arg.ParentID,
		arg.ProjectID,
		arg.Position,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
