// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_templates.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDocumentTemplates = `-- name: CountDocumentTemplates :one
SELECT count(*) FROM document_templates WHERE workspace_id = $1
`

func (q *Queries) CountDocumentTemplates(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentTemplates, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentTemplate = `-- name: CreateDocumentTemplate :one
INSERT INTO document_templates (workspace_id, author_id, title, description, icon, content, preview)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, author_id, title, description, icon, content, preview, created_at, updated_at
`

type CreateDocumentTemplateParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Icon        string     `json:"icon"`
	Content     []byte     `json:"content"`
	Preview     string     `json:"preview"`
}

func (q *Queries) CreateDocumentTemplate(ctx context.Context, arg CreateDocumentTemplateParams) (DocumentTemplate, error) {
	row := q.db.QueryRow(ctx, createDocumentTemplate,
		arg.WorkspaceID,
		arg.AuthorID,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.Content,
		arg.Preview,
	)
	var i DocumentTemplate
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.Content,
		&i.Preview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocumentTemplate = `-- name: DeleteDocumentTemplate :exec
DELETE FROM document_templates WHERE id = $1
`

func (q *Queries) DeleteDocumentTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentTemplate, id)
	return err
}

const getDocumentTemplate = `-- name: GetDocumentTemplate :one
SELECT id, workspace_id, author_id, title, description, icon, content, preview, created_at, updated_at FROM document_templates WHERE id = $1
`

func (q *Queries) GetDocumentTemplate(ctx context.Context, id uuid.UUID) (DocumentTemplate, error) {
	row := q.db.QueryRow(ctx, getDocumentTemplate, id)
	var i DocumentTemplate
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.Content,
		&i.Preview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentTemplates = `-- name: ListDocumentTemplates :many
SELECT t.id, t.workspace_id, t.author_id, t.title, t.description, t.icon, t.preview,
       t.created_at, t.updated_at,
       u.name AS author_name
FROM document_templates t
LEFT JOIN users u ON u.id = t.author_id
WHERE t.workspace_id = $1
ORDER BY t.title, t.created_at
`

type ListDocumentTemplatesRow struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Icon        string     `json:"icon"`
	Preview     string     `json:"preview"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	AuthorName  *string    `json:"author_name"`
}

// ListDocumentTemplates returns the workspace gallery. Content is left behind
// for the same reason as in ListDocuments: a template is a whole document body,
// and the gallery shows all of them at once — the preview column exists so this
// list stays cheap.
func (q *Queries) ListDocumentTemplates(ctx context.Context, workspaceID uuid.UUID) ([]ListDocumentTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentTemplates, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentTemplatesRow
	for rows.Next() {
		var i ListDocumentTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.AuthorID,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.Preview,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentTemplateMeta = `-- name: UpdateDocumentTemplateMeta :one
UPDATE document_templates
SET title = $2, description = $3, icon = $4, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, author_id, title, description, icon, content, preview, created_at, updated_at
`

type UpdateDocumentTemplateMetaParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
}

func (q *Queries) UpdateDocumentTemplateMeta(ctx context.Context, arg UpdateDocumentTemplateMetaParams) (DocumentTemplate, error) {
	row := q.db.QueryRow(ctx, updateDocumentTemplateMeta,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Icon,
	)
	var i DocumentTemplate
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.AuthorID,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.Content,
		&i.Preview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
