// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab_relations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTaskRelationSourced = `-- name: AddTaskRelationSourced :one
INSERT INTO task_relations (task_id, related_task_id, kind, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (task_id, related_task_id, kind)
DO UPDATE SET source = task_relations.source
RETURNING id, task_id, related_task_id, kind, created_at, source
`

type AddTaskRelationSourcedParams struct {
	TaskID        uuid.UUID `json:"task_id"`
	RelatedTaskID uuid.UUID `json:"related_task_id"`
	Kind          string    `json:"kind"`
	Source        string    `json:"source"`
}

// AddTaskRelationSourced projects a remote link onto the core table. The conflict
// branch is a deliberate no-op update: it returns the existing row (so the link can
// record which relation it maps to) without downgrading a user-made relation's
// source to 'gitlab'.
func (q *Queries) AddTaskRelationSourced(ctx context.Context, arg AddTaskRelationSourcedParams) (TaskRelation, error) {
	row := q.db.QueryRow(ctx, addTaskRelationSourced,
		arg.TaskID,
		arg.RelatedTaskID,
		arg.Kind,
		arg.Source,
	)
	var i TaskRelation
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.RelatedTaskID,
		&i.Kind,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const deleteGitlabRelation = `-- name: DeleteGitlabRelation :execrows
DELETE FROM task_relations WHERE id = $1 AND source = 'gitlab'
`

// DeleteGitlabRelation unprojects a relation. The source guard means a relation the
// user has since taken ownership of is never removed by the sync.
func (q *Queries) DeleteGitlabRelation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGitlabRelation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleGitlabIssueLinks = `-- name: DeleteStaleGitlabIssueLinks :many
WITH deleted AS (
    DELETE FROM gitlab_issue_links
    WHERE integration_id = $1
      AND src_iid = ANY($2::bigint[])
      AND last_seen_at < $3
    RETURNING resolved_relation_id
)
SELECT resolved_relation_id::uuid AS relation_id FROM deleted WHERE resolved_relation_id IS NOT NULL
`

type DeleteStaleGitlabIssueLinksParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	SrcIids       []int64   `json:"src_iids"`
	SeenBefore    time.Time `json:"seen_before"`
}

// DeleteStaleGitlabIssueLinks drops links GitLab no longer reports, returning the
// relations they had projected so the caller can unproject them. Scoped to the
// source iids actually inspected this run — an issue outside the run's scope must
// keep its links rather than lose them to a "not seen" verdict.
func (q *Queries) DeleteStaleGitlabIssueLinks(ctx context.Context, arg DeleteStaleGitlabIssueLinksParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteStaleGitlabIssueLinks, arg.IntegrationID, arg.SrcIids, arg.SeenBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var relation_id uuid.UUID
		if err := rows.Scan(&relation_id); err != nil {
			return nil, err
		}
		items = append(items, relation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGitlabIntegrationByWorkspaceProject = `-- name: GetGitlabIntegrationByWorkspaceProject :one
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after, last_full_synced_at, members_synced_at, full_sync_interval_sec, relations_sync FROM gitlab_integrations WHERE workspace_id = $1 AND project_path = $2 LIMIT 1
`

type GetGitlabIntegrationByWorkspaceProjectParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectPath string    `json:"project_path"`
}

// GetGitlabIntegrationByWorkspaceProject finds the binding for a project path
// inside one workspace — the hop that resolves a cross-project link while keeping
// relations from ever crossing a workspace boundary.
func (q *Queries) GetGitlabIntegrationByWorkspaceProject(ctx context.Context, arg GetGitlabIntegrationByWorkspaceProjectParams) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegrationByWorkspaceProject, arg.WorkspaceID, arg.ProjectPath)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
		&i.LastFullSyncedAt,
		&i.MembersSyncedAt,
		&i.FullSyncIntervalSec,
		&i.RelationsSync,
	)
	return i, err
}

const getGitlabLinkByIID = `-- name: GetGitlabLinkByIID :one
SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url, start_overridden, gl_last_state, estimate_overridden, gl_snapshot, milestone_overridden, gl_is_group, gl_work_item_id, gl_parent_global_id FROM gitlab_links WHERE integration_id = $1 AND gl_iid = $2 LIMIT 1
`

type GetGitlabLinkByIIDParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlIid         int64     `json:"gl_iid"`
}

// GetGitlabLinkByIID resolves a GitLab issue iid to its Tessera task within one
// binding (gl_iid is unique per integration in practice; LIMIT 1 guards the rest).
func (q *Queries) GetGitlabLinkByIID(ctx context.Context, arg GetGitlabLinkByIIDParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByIID, arg.IntegrationID, arg.GlIid)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
		&i.StartOverridden,
		&i.GlLastState,
		&i.EstimateOverridden,
		&i.GlSnapshot,
		&i.MilestoneOverridden,
		&i.GlIsGroup,
		&i.GlWorkItemID,
		&i.GlParentGlobalID,
	)
	return i, err
}

const listUnresolvedGitlabIssueLinks = `-- name: ListUnresolvedGitlabIssueLinks :many
SELECT id, integration_id, src_project_path, src_iid, dst_project_path, dst_iid, link_type, gl_link_id, gl_web_url, resolved_relation_id, last_seen_at, created_at FROM gitlab_issue_links
WHERE integration_id = $1 AND resolved_relation_id IS NULL
ORDER BY created_at
`

// ListUnresolvedGitlabIssueLinks returns every link with no core relation yet:
// both the ones just upserted and older ones whose other endpoint had not been
// imported at the time (deferred resolution).
func (q *Queries) ListUnresolvedGitlabIssueLinks(ctx context.Context, integrationID uuid.UUID) ([]GitlabIssueLink, error) {
	rows, err := q.db.Query(ctx, listUnresolvedGitlabIssueLinks, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabIssueLink
	for rows.Next() {
		var i GitlabIssueLink
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.SrcProjectPath,
			&i.SrcIid,
			&i.DstProjectPath,
			&i.DstIid,
			&i.LinkType,
			&i.GlLinkID,
			&i.GlWebUrl,
			&i.ResolvedRelationID,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGitlabIssueLinkResolved = `-- name: SetGitlabIssueLinkResolved :exec
UPDATE gitlab_issue_links SET resolved_relation_id = $2 WHERE id = $1
`

type SetGitlabIssueLinkResolvedParams struct {
	ID                 uuid.UUID  `json:"id"`
	ResolvedRelationID *uuid.UUID `json:"resolved_relation_id"`
}

func (q *Queries) SetGitlabIssueLinkResolved(ctx context.Context, arg SetGitlabIssueLinkResolvedParams) error {
	_, err := q.db.Exec(ctx, setGitlabIssueLinkResolved, arg.ID, arg.ResolvedRelationID)
	return err
}

const upsertGitlabIssueLink = `-- name: UpsertGitlabIssueLink :one

INSERT INTO gitlab_issue_links (
    integration_id, src_project_path, src_iid, dst_project_path, dst_iid,
    link_type, gl_link_id, gl_web_url, last_seen_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (integration_id, src_project_path, src_iid, dst_project_path, dst_iid, link_type)
DO UPDATE SET gl_link_id = EXCLUDED.gl_link_id, gl_web_url = EXCLUDED.gl_web_url, last_seen_at = now()
RETURNING id, integration_id, src_project_path, src_iid, dst_project_path, dst_iid, link_type, gl_link_id, gl_web_url, resolved_relation_id, last_seen_at, created_at
`

type UpsertGitlabIssueLinkParams struct {
	IntegrationID  uuid.UUID `json:"integration_id"`
	SrcProjectPath string    `json:"src_project_path"`
	SrcIid         int64     `json:"src_iid"`
	DstProjectPath string    `json:"dst_project_path"`
	DstIid         int64     `json:"dst_iid"`
	LinkType       string    `json:"link_type"`
	GlLinkID       string    `json:"gl_link_id"`
	GlWebUrl       string    `json:"gl_web_url"`
}

// GitLab linked items (task #2591). Raw remote links live here; the core
// `task_relations` table only ever sees a provider-neutral source='gitlab'.
// UpsertGitlabIssueLink records one remote link and stamps it as seen this run.
// resolved_relation_id is intentionally NOT touched, so RETURNING reports whether
// the link was already projected onto a core relation (nil ⇒ still to resolve).
func (q *Queries) UpsertGitlabIssueLink(ctx context.Context, arg UpsertGitlabIssueLinkParams) (GitlabIssueLink, error) {
	row := q.db.QueryRow(ctx, upsertGitlabIssueLink,
		arg.IntegrationID,
		arg.SrcProjectPath,
		arg.SrcIid,
		arg.DstProjectPath,
		arg.DstIid,
		arg.LinkType,
		arg.GlLinkID,
		arg.GlWebUrl,
	)
	var i GitlabIssueLink
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.SrcProjectPath,
		&i.SrcIid,
		&i.DstProjectPath,
		&i.DstIid,
		&i.LinkType,
		&i.GlLinkID,
		&i.GlWebUrl,
		&i.ResolvedRelationID,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
