// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTaskAssigneeSourced = `-- name: AddTaskAssigneeSourced :exec
INSERT INTO task_assignees (task_id, user_id, source) VALUES ($1, $2, $3)
ON CONFLICT (task_id, user_id) DO NOTHING
`

type AddTaskAssigneeSourcedParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

func (q *Queries) AddTaskAssigneeSourced(ctx context.Context, arg AddTaskAssigneeSourcedParams) error {
	_, err := q.db.Exec(ctx, addTaskAssigneeSourced, arg.TaskID, arg.UserID, arg.Source)
	return err
}

const addTaskTagSourced = `-- name: AddTaskTagSourced :execrows
INSERT INTO task_tags (task_id, tag_id, source) VALUES ($1, $2, $3)
ON CONFLICT (task_id, tag_id) DO NOTHING
`

type AddTaskTagSourcedParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
	Source string    `json:"source"`
}

// AddTaskTagSourced returns the number of rows inserted (1 = newly attached, 0 =
// the tag was already on the task) so the sync journal can record actual additions.
func (q *Queries) AddTaskTagSourced(ctx context.Context, arg AddTaskTagSourcedParams) (int64, error) {
	result, err := q.db.Exec(ctx, addTaskTagSourced, arg.TaskID, arg.TagID, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGitlabIntegration = `-- name: CreateGitlabIntegration :one

INSERT INTO gitlab_integrations (
    workspace_id, name, project_path, board_id, label_rules, enabled, owner_user_id,
    sync_interval_sec, due_source, start_source, writeback, scope, closed_policy, closed_after, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, now())
RETURNING id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after
`

type CreateGitlabIntegrationParams struct {
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	Name            string     `json:"name"`
	ProjectPath     string     `json:"project_path"`
	BoardID         uuid.UUID  `json:"board_id"`
	LabelRules      []byte     `json:"label_rules"`
	Enabled         bool       `json:"enabled"`
	OwnerUserID     *uuid.UUID `json:"owner_user_id"`
	SyncIntervalSec int32      `json:"sync_interval_sec"`
	DueSource       string     `json:"due_source"`
	StartSource     string     `json:"start_source"`
	Writeback       []byte     `json:"writeback"`
	Scope           string     `json:"scope"`
	ClosedPolicy    string     `json:"closed_policy"`
	ClosedAfter     *time.Time `json:"closed_after"`
}

// ── Per-workspace integration ──────────────────────────────
func (q *Queries) CreateGitlabIntegration(ctx context.Context, arg CreateGitlabIntegrationParams) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, createGitlabIntegration,
		arg.WorkspaceID,
		arg.Name,
		arg.ProjectPath,
		arg.BoardID,
		arg.LabelRules,
		arg.Enabled,
		arg.OwnerUserID,
		arg.SyncIntervalSec,
		arg.DueSource,
		arg.StartSource,
		arg.Writeback,
		arg.Scope,
		arg.ClosedPolicy,
		arg.ClosedAfter,
	)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
	)
	return i, err
}

const createGitlabLink = `-- name: CreateGitlabLink :one
INSERT INTO gitlab_links (
    task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url,
    gl_updated_at, title_hash, desc_hash, labels_hash, gl_author, gl_author_name,
    gl_author_avatar_url, gl_last_state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url, start_overridden, gl_last_state, estimate_overridden, gl_snapshot, milestone_overridden
`

type CreateGitlabLinkParams struct {
	TaskID            uuid.UUID  `json:"task_id"`
	IntegrationID     uuid.UUID  `json:"integration_id"`
	GlGlobalID        string     `json:"gl_global_id"`
	GlIid             int64      `json:"gl_iid"`
	GlProjectPath     string     `json:"gl_project_path"`
	GlWebUrl          string     `json:"gl_web_url"`
	GlUpdatedAt       *time.Time `json:"gl_updated_at"`
	TitleHash         string     `json:"title_hash"`
	DescHash          string     `json:"desc_hash"`
	LabelsHash        string     `json:"labels_hash"`
	GlAuthor          string     `json:"gl_author"`
	GlAuthorName      string     `json:"gl_author_name"`
	GlAuthorAvatarUrl string     `json:"gl_author_avatar_url"`
	GlLastState       string     `json:"gl_last_state"`
}

func (q *Queries) CreateGitlabLink(ctx context.Context, arg CreateGitlabLinkParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, createGitlabLink,
		arg.TaskID,
		arg.IntegrationID,
		arg.GlGlobalID,
		arg.GlIid,
		arg.GlProjectPath,
		arg.GlWebUrl,
		arg.GlUpdatedAt,
		arg.TitleHash,
		arg.DescHash,
		arg.LabelsHash,
		arg.GlAuthor,
		arg.GlAuthorName,
		arg.GlAuthorAvatarUrl,
		arg.GlLastState,
	)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
		&i.StartOverridden,
		&i.GlLastState,
		&i.EstimateOverridden,
		&i.GlSnapshot,
		&i.MilestoneOverridden,
	)
	return i, err
}

const deleteGitlabCredential = `-- name: DeleteGitlabCredential :exec
DELETE FROM gitlab_credentials WHERE user_id = $1
`

func (q *Queries) DeleteGitlabCredential(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitlabCredential, userID)
	return err
}

const deleteGitlabIntegration = `-- name: DeleteGitlabIntegration :exec
DELETE FROM gitlab_integrations WHERE id = $1
`

func (q *Queries) DeleteGitlabIntegration(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitlabIntegration, id)
	return err
}

const deleteGitlabSourcedAssignees = `-- name: DeleteGitlabSourcedAssignees :exec
DELETE FROM task_gitlab_assignees WHERE task_id = $1 AND source = 'gitlab'
`

// ── external GitLab assignees (no Tessera account) ─────────
// Only the sync-made set is rebuilt each run; user-pinned (source='user') survive.
func (q *Queries) DeleteGitlabSourcedAssignees(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitlabSourcedAssignees, taskID)
	return err
}

const deleteStaleGitlabAssignees = `-- name: DeleteStaleGitlabAssignees :exec
DELETE FROM task_assignees
WHERE task_id = $1 AND source = 'gitlab' AND NOT (user_id = ANY($2::uuid[]))
`

type DeleteStaleGitlabAssigneesParams struct {
	TaskID  uuid.UUID   `json:"task_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) DeleteStaleGitlabAssignees(ctx context.Context, arg DeleteStaleGitlabAssigneesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleGitlabAssignees, arg.TaskID, arg.Column2)
	return err
}

const deleteStaleGitlabProjectMembers = `-- name: DeleteStaleGitlabProjectMembers :exec
DELETE FROM gitlab_project_members WHERE integration_id = $1 AND NOT (gl_user_id = ANY($2::bigint[]))
`

type DeleteStaleGitlabProjectMembersParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Column2       []int64   `json:"column_2"`
}

func (q *Queries) DeleteStaleGitlabProjectMembers(ctx context.Context, arg DeleteStaleGitlabProjectMembersParams) error {
	_, err := q.db.Exec(ctx, deleteStaleGitlabProjectMembers, arg.IntegrationID, arg.Column2)
	return err
}

const deleteStaleGitlabTaskTags = `-- name: DeleteStaleGitlabTaskTags :many
WITH deleted AS (
    DELETE FROM task_tags
    WHERE task_id = $1 AND source = 'gitlab' AND NOT (tag_id = ANY($2::uuid[]))
    RETURNING tag_id
)
SELECT t.name FROM deleted d JOIN tags t ON t.id = d.tag_id
`

type DeleteStaleGitlabTaskTagsParams struct {
	TaskID  uuid.UUID   `json:"task_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

// DeleteStaleGitlabTaskTags removes gitlab-sourced tags GitLab no longer has and
// returns their names for the sync journal.
func (q *Queries) DeleteStaleGitlabTaskTags(ctx context.Context, arg DeleteStaleGitlabTaskTagsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteStaleGitlabTaskTags, arg.TaskID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGitlabCredential = `-- name: GetGitlabCredential :one
SELECT user_id, base_url, token_enc, gl_user_id, gl_username, created_at, updated_at FROM gitlab_credentials WHERE user_id = $1
`

func (q *Queries) GetGitlabCredential(ctx context.Context, userID uuid.UUID) (GitlabCredential, error) {
	row := q.db.QueryRow(ctx, getGitlabCredential, userID)
	var i GitlabCredential
	err := row.Scan(
		&i.UserID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.GlUserID,
		&i.GlUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabIntegration = `-- name: GetGitlabIntegration :one
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after FROM gitlab_integrations WHERE id = $1
`

func (q *Queries) GetGitlabIntegration(ctx context.Context, id uuid.UUID) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegration, id)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
	)
	return i, err
}

const getGitlabIntegrationByBoard = `-- name: GetGitlabIntegrationByBoard :one
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after FROM gitlab_integrations WHERE board_id = $1
`

// GetGitlabIntegrationByBoard resolves the binding that mirrors into a given board
// (task-scoped operations: create-issue, board-scoped sync).
func (q *Queries) GetGitlabIntegrationByBoard(ctx context.Context, boardID uuid.UUID) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegrationByBoard, boardID)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
	)
	return i, err
}

const getGitlabIntegrationByProject = `-- name: GetGitlabIntegrationByProject :one
SELECT i.id, i.workspace_id, i.project_path, i.board_id, i.label_rules, i.enabled, i.created_at, i.updated_at, i.owner_user_id, i.sync_interval_sec, i.last_synced_at, i.due_source, i.start_source, i.writeback, i.name, i.scope, i.closed_policy, i.closed_after FROM gitlab_integrations i
JOIN boards b ON b.id = i.board_id
WHERE b.project_id = $1
ORDER BY i.created_at
LIMIT 1
`

// GetGitlabIntegrationByProject resolves a binding whose target board lives in a
// project (milestone push is project-scoped). Picks the oldest when several.
func (q *Queries) GetGitlabIntegrationByProject(ctx context.Context, projectID uuid.UUID) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegrationByProject, projectID)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
	)
	return i, err
}

const getGitlabLinkByGlobalID = `-- name: GetGitlabLinkByGlobalID :one

SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url, start_overridden, gl_last_state, estimate_overridden, gl_snapshot, milestone_overridden FROM gitlab_links WHERE integration_id = $1 AND gl_global_id = $2
`

type GetGitlabLinkByGlobalIDParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlGlobalID    string    `json:"gl_global_id"`
}

// ── Task ↔ work item link ──────────────────────────────────
func (q *Queries) GetGitlabLinkByGlobalID(ctx context.Context, arg GetGitlabLinkByGlobalIDParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByGlobalID, arg.IntegrationID, arg.GlGlobalID)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
		&i.StartOverridden,
		&i.GlLastState,
		&i.EstimateOverridden,
		&i.GlSnapshot,
		&i.MilestoneOverridden,
	)
	return i, err
}

const getGitlabLinkByTask = `-- name: GetGitlabLinkByTask :one
SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url, start_overridden, gl_last_state, estimate_overridden, gl_snapshot, milestone_overridden FROM gitlab_links WHERE task_id = $1
`

func (q *Queries) GetGitlabLinkByTask(ctx context.Context, taskID uuid.UUID) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByTask, taskID)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
		&i.StartOverridden,
		&i.GlLastState,
		&i.EstimateOverridden,
		&i.GlSnapshot,
		&i.MilestoneOverridden,
	)
	return i, err
}

const getGitlabMemberIDByUsername = `-- name: GetGitlabMemberIDByUsername :one
SELECT gl_user_id FROM gitlab_project_members WHERE integration_id = $1 AND gl_username = $2
`

type GetGitlabMemberIDByUsernameParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlUsername    string    `json:"gl_username"`
}

func (q *Queries) GetGitlabMemberIDByUsername(ctx context.Context, arg GetGitlabMemberIDByUsernameParams) (int64, error) {
	row := q.db.QueryRow(ctx, getGitlabMemberIDByUsername, arg.IntegrationID, arg.GlUsername)
	var gl_user_id int64
	err := row.Scan(&gl_user_id)
	return gl_user_id, err
}

const getUserIDByGitlabUsername = `-- name: GetUserIDByGitlabUsername :one
SELECT user_id FROM gitlab_credentials WHERE gl_username = $1
`

// ── sync reconciliation: mixed tags / assignees ────────────
// Resolve a GitLab username to a Tessera user (via their linked credential).
func (q *Queries) GetUserIDByGitlabUsername(ctx context.Context, glUsername string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByGitlabUsername, glUsername)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const linkedIidsForIntegration = `-- name: LinkedIidsForIntegration :many
SELECT gl_iid FROM gitlab_links WHERE integration_id = $1
`

func (q *Queries) LinkedIidsForIntegration(ctx context.Context, integrationID uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, linkedIidsForIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var gl_iid int64
		if err := rows.Scan(&gl_iid); err != nil {
			return nil, err
		}
		items = append(items, gl_iid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoSyncIntegrations = `-- name: ListAutoSyncIntegrations :many
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after FROM gitlab_integrations
WHERE enabled
  AND sync_interval_sec > 0
  AND owner_user_id IS NOT NULL
  AND (last_synced_at IS NULL OR last_synced_at < now() - make_interval(secs => sync_interval_sec))
`

// ListAutoSyncIntegrations returns integrations due for unattended sync: enabled,
// with a positive interval, an owner credential set, and either never synced or
// past their interval. Used by the background worker.
func (q *Queries) ListAutoSyncIntegrations(ctx context.Context) ([]GitlabIntegration, error) {
	rows, err := q.db.Query(ctx, listAutoSyncIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabIntegration
	for rows.Next() {
		var i GitlabIntegration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectPath,
			&i.BoardID,
			&i.LabelRules,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.SyncIntervalSec,
			&i.LastSyncedAt,
			&i.DueSource,
			&i.StartSource,
			&i.Writeback,
			&i.Name,
			&i.Scope,
			&i.ClosedPolicy,
			&i.ClosedAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSyncIntegrations = `-- name: ListDueSyncIntegrations :many
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after FROM gitlab_integrations
WHERE enabled
  AND sync_interval_sec > 0
  AND (last_synced_at IS NULL OR last_synced_at < now() - make_interval(secs => sync_interval_sec))
`

// ListDueSyncIntegrations returns integrations due for unattended sync regardless
// of an owner credential — used when an instance service token drives the sync.
func (q *Queries) ListDueSyncIntegrations(ctx context.Context) ([]GitlabIntegration, error) {
	rows, err := q.db.Query(ctx, listDueSyncIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabIntegration
	for rows.Next() {
		var i GitlabIntegration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectPath,
			&i.BoardID,
			&i.LabelRules,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.SyncIntervalSec,
			&i.LastSyncedAt,
			&i.DueSource,
			&i.StartSource,
			&i.Writeback,
			&i.Name,
			&i.Scope,
			&i.ClosedPolicy,
			&i.ClosedAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitlabIntegrationsByWorkspace = `-- name: ListGitlabIntegrationsByWorkspace :many
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after FROM gitlab_integrations WHERE workspace_id = $1 ORDER BY name, created_at
`

func (q *Queries) ListGitlabIntegrationsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]GitlabIntegration, error) {
	rows, err := q.db.Query(ctx, listGitlabIntegrationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabIntegration
	for rows.Next() {
		var i GitlabIntegration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectPath,
			&i.BoardID,
			&i.LabelRules,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.SyncIntervalSec,
			&i.LastSyncedAt,
			&i.DueSource,
			&i.StartSource,
			&i.Writeback,
			&i.Name,
			&i.Scope,
			&i.ClosedPolicy,
			&i.ClosedAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitlabProjectMembersByWorkspace = `-- name: ListGitlabProjectMembersByWorkspace :many
SELECT DISTINCT ON (m.gl_user_id)
  m.gl_user_id, m.gl_username, m.gl_name, m.gl_avatar_url, m.access_level,
  oi.user_id AS tessera_user_id,
  gc.user_id AS tessera_user_id_pat
FROM gitlab_project_members m
JOIN gitlab_integrations i ON i.id = m.integration_id
LEFT JOIN oauth_identities oi ON oi.provider = 'gitlab' AND oi.provider_username = m.gl_username
LEFT JOIN gitlab_credentials gc ON gc.gl_username = m.gl_username
WHERE i.workspace_id = $1
ORDER BY m.gl_user_id, m.gl_name
`

type ListGitlabProjectMembersByWorkspaceRow struct {
	GlUserID         int64      `json:"gl_user_id"`
	GlUsername       string     `json:"gl_username"`
	GlName           string     `json:"gl_name"`
	GlAvatarUrl      string     `json:"gl_avatar_url"`
	AccessLevel      int32      `json:"access_level"`
	TesseraUserID    *uuid.UUID `json:"tessera_user_id"`
	TesseraUserIDPat *uuid.UUID `json:"tessera_user_id_pat"`
}

// ListGitlabProjectMembersByWorkspace returns the assignable GitLab roster, each
// annotated with the Tessera user it maps to (via OAuth identity or connected PAT),
// so the UI can dedup members that already have a Tessera account.
func (q *Queries) ListGitlabProjectMembersByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListGitlabProjectMembersByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listGitlabProjectMembersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGitlabProjectMembersByWorkspaceRow
	for rows.Next() {
		var i ListGitlabProjectMembersByWorkspaceRow
		if err := rows.Scan(
			&i.GlUserID,
			&i.GlUsername,
			&i.GlName,
			&i.GlAvatarUrl,
			&i.AccessLevel,
			&i.TesseraUserID,
			&i.TesseraUserIDPat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskGitlabAssignees = `-- name: ListTaskGitlabAssignees :many
SELECT gl_username, gl_name, gl_avatar_url, source FROM task_gitlab_assignees WHERE task_id = $1 ORDER BY gl_name
`

type ListTaskGitlabAssigneesRow struct {
	GlUsername  string `json:"gl_username"`
	GlName      string `json:"gl_name"`
	GlAvatarUrl string `json:"gl_avatar_url"`
	Source      string `json:"source"`
}

func (q *Queries) ListTaskGitlabAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskGitlabAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskGitlabAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskGitlabAssigneesRow
	for rows.Next() {
		var i ListTaskGitlabAssigneesRow
		if err := rows.Scan(
			&i.GlUsername,
			&i.GlName,
			&i.GlAvatarUrl,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGitlabDueOverridden = `-- name: MarkGitlabDueOverridden :exec
UPDATE gitlab_links SET due_overridden = true WHERE task_id = $1
`

// MarkGitlabDueOverridden flags a linked task's due as user-set so the sync stops
// touching it. No-op when the task isn't linked.
func (q *Queries) MarkGitlabDueOverridden(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabDueOverridden, taskID)
	return err
}

const markGitlabEstimateOverridden = `-- name: MarkGitlabEstimateOverridden :exec
UPDATE gitlab_links SET estimate_overridden = true WHERE task_id = $1
`

func (q *Queries) MarkGitlabEstimateOverridden(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabEstimateOverridden, taskID)
	return err
}

const markGitlabStartOverridden = `-- name: MarkGitlabStartOverridden :exec
UPDATE gitlab_links SET start_overridden = true WHERE task_id = $1
`

// MarkGitlabStartOverridden flags a linked task's start as user-set so the sync
// stops touching it. No-op when the task isn't linked.
func (q *Queries) MarkGitlabStartOverridden(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabStartOverridden, taskID)
	return err
}

const markGitlabSynced = `-- name: MarkGitlabSynced :exec
UPDATE gitlab_integrations SET last_synced_at = now() WHERE id = $1
`

// MarkGitlabSynced stamps the integration's last successful sync time.
func (q *Queries) MarkGitlabSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabSynced, id)
	return err
}

const pinGitlabAssignee = `-- name: PinGitlabAssignee :exec
INSERT INTO task_gitlab_assignees (task_id, gl_username, gl_name, gl_avatar_url, source) VALUES ($1, $2, $3, $4, 'user')
ON CONFLICT (task_id, gl_username) DO UPDATE SET source = 'user', gl_name = EXCLUDED.gl_name, gl_avatar_url = EXCLUDED.gl_avatar_url
`

type PinGitlabAssigneeParams struct {
	TaskID      uuid.UUID `json:"task_id"`
	GlUsername  string    `json:"gl_username"`
	GlName      string    `json:"gl_name"`
	GlAvatarUrl string    `json:"gl_avatar_url"`
}

// User pin (from the assignee picker): forces source='user' so the sync won't drop it.
func (q *Queries) PinGitlabAssignee(ctx context.Context, arg PinGitlabAssigneeParams) error {
	_, err := q.db.Exec(ctx, pinGitlabAssignee,
		arg.TaskID,
		arg.GlUsername,
		arg.GlName,
		arg.GlAvatarUrl,
	)
	return err
}

const removeGitlabAssignee = `-- name: RemoveGitlabAssignee :exec
DELETE FROM task_gitlab_assignees WHERE task_id = $1 AND gl_username = $2
`

type RemoveGitlabAssigneeParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	GlUsername string    `json:"gl_username"`
}

func (q *Queries) RemoveGitlabAssignee(ctx context.Context, arg RemoveGitlabAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeGitlabAssignee, arg.TaskID, arg.GlUsername)
	return err
}

const setGitlabLinkSnapshot = `-- name: SetGitlabLinkSnapshot :exec
UPDATE gitlab_links SET gl_snapshot = $2 WHERE task_id = $1
`

type SetGitlabLinkSnapshotParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	GlSnapshot []byte    `json:"gl_snapshot"`
}

// SetGitlabLinkSnapshot stores the last-synced GitLab field state (the conflict
// baseline). Written alongside the pull link-update and after a successful push, so
// the next push can tell a clean overwrite from a both-sides-changed conflict.
func (q *Queries) SetGitlabLinkSnapshot(ctx context.Context, arg SetGitlabLinkSnapshotParams) error {
	_, err := q.db.Exec(ctx, setGitlabLinkSnapshot, arg.TaskID, arg.GlSnapshot)
	return err
}

const syncUpdateTask = `-- name: SyncUpdateTask :one
UPDATE tasks
SET title = $2, description = $3, priority = $4, column_id = $5, completed_at = $6, board_id = $7, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type SyncUpdateTaskParams struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Priority    int32      `json:"priority"`
	ColumnID    uuid.UUID  `json:"column_id"`
	CompletedAt *time.Time `json:"completed_at"`
	BoardID     uuid.UUID  `json:"board_id"`
}

// SyncUpsertTask updates the synced fields of a linked task without touching its
// position (the user may have reordered it on the board).
func (q *Queries) SyncUpdateTask(ctx context.Context, arg SyncUpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, syncUpdateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.ColumnID,
		arg.CompletedAt,
		arg.BoardID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const updateGitlabIntegration = `-- name: UpdateGitlabIntegration :one
UPDATE gitlab_integrations
SET name = $2, project_path = $3, board_id = $4, label_rules = $5, enabled = $6,
    owner_user_id = $7, sync_interval_sec = $8, due_source = $9, start_source = $10,
    writeback = $11, scope = $12, closed_policy = $13, closed_after = $14, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after
`

type UpdateGitlabIntegrationParams struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	ProjectPath     string     `json:"project_path"`
	BoardID         uuid.UUID  `json:"board_id"`
	LabelRules      []byte     `json:"label_rules"`
	Enabled         bool       `json:"enabled"`
	OwnerUserID     *uuid.UUID `json:"owner_user_id"`
	SyncIntervalSec int32      `json:"sync_interval_sec"`
	DueSource       string     `json:"due_source"`
	StartSource     string     `json:"start_source"`
	Writeback       []byte     `json:"writeback"`
	Scope           string     `json:"scope"`
	ClosedPolicy    string     `json:"closed_policy"`
	ClosedAfter     *time.Time `json:"closed_after"`
}

func (q *Queries) UpdateGitlabIntegration(ctx context.Context, arg UpdateGitlabIntegrationParams) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, updateGitlabIntegration,
		arg.ID,
		arg.Name,
		arg.ProjectPath,
		arg.BoardID,
		arg.LabelRules,
		arg.Enabled,
		arg.OwnerUserID,
		arg.SyncIntervalSec,
		arg.DueSource,
		arg.StartSource,
		arg.Writeback,
		arg.Scope,
		arg.ClosedPolicy,
		arg.ClosedAfter,
	)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
	)
	return i, err
}

const updateGitlabLink = `-- name: UpdateGitlabLink :one
UPDATE gitlab_links
SET gl_iid = $2, gl_web_url = $3, gl_updated_at = $4,
    title_hash = $5, desc_hash = $6, labels_hash = $7,
    gl_author = $8, gl_author_name = $9, gl_author_avatar_url = $10,
    gl_last_state = $11,
    last_synced_at = now()
WHERE task_id = $1
RETURNING task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url, start_overridden, gl_last_state, estimate_overridden, gl_snapshot, milestone_overridden
`

type UpdateGitlabLinkParams struct {
	TaskID            uuid.UUID  `json:"task_id"`
	GlIid             int64      `json:"gl_iid"`
	GlWebUrl          string     `json:"gl_web_url"`
	GlUpdatedAt       *time.Time `json:"gl_updated_at"`
	TitleHash         string     `json:"title_hash"`
	DescHash          string     `json:"desc_hash"`
	LabelsHash        string     `json:"labels_hash"`
	GlAuthor          string     `json:"gl_author"`
	GlAuthorName      string     `json:"gl_author_name"`
	GlAuthorAvatarUrl string     `json:"gl_author_avatar_url"`
	GlLastState       string     `json:"gl_last_state"`
}

func (q *Queries) UpdateGitlabLink(ctx context.Context, arg UpdateGitlabLinkParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, updateGitlabLink,
		arg.TaskID,
		arg.GlIid,
		arg.GlWebUrl,
		arg.GlUpdatedAt,
		arg.TitleHash,
		arg.DescHash,
		arg.LabelsHash,
		arg.GlAuthor,
		arg.GlAuthorName,
		arg.GlAuthorAvatarUrl,
		arg.GlLastState,
	)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
		&i.StartOverridden,
		&i.GlLastState,
		&i.EstimateOverridden,
		&i.GlSnapshot,
		&i.MilestoneOverridden,
	)
	return i, err
}

const upsertGitlabComment = `-- name: UpsertGitlabComment :one
INSERT INTO task_comments (task_id, author_id, body, gl_note_id, gl_author_login, gl_author_name, gl_author_avatar_url, created_at, updated_at)
VALUES ($1, NULL, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (gl_note_id) WHERE gl_note_id IS NOT NULL
DO UPDATE SET body = EXCLUDED.body, gl_author_name = EXCLUDED.gl_author_name, gl_author_avatar_url = EXCLUDED.gl_author_avatar_url, updated_at = now()
RETURNING (xmax = 0) AS inserted
`

type UpsertGitlabCommentParams struct {
	TaskID            uuid.UUID `json:"task_id"`
	Body              string    `json:"body"`
	GlNoteID          *string   `json:"gl_note_id"`
	GlAuthorLogin     string    `json:"gl_author_login"`
	GlAuthorName      string    `json:"gl_author_name"`
	GlAuthorAvatarUrl string    `json:"gl_author_avatar_url"`
	CreatedAt         time.Time `json:"created_at"`
}

// ── synced comments (idempotent by GitLab note id) ─────────
// UpsertGitlabComment returns whether the row was freshly inserted (xmax = 0) so
// the sync journal can count new comments rather than re-synced ones.
func (q *Queries) UpsertGitlabComment(ctx context.Context, arg UpsertGitlabCommentParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertGitlabComment,
		arg.TaskID,
		arg.Body,
		arg.GlNoteID,
		arg.GlAuthorLogin,
		arg.GlAuthorName,
		arg.GlAuthorAvatarUrl,
		arg.CreatedAt,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const upsertGitlabCredential = `-- name: UpsertGitlabCredential :one


INSERT INTO gitlab_credentials (user_id, base_url, token_enc, gl_user_id, gl_username, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id) DO UPDATE
SET base_url = EXCLUDED.base_url,
    token_enc = EXCLUDED.token_enc,
    gl_user_id = EXCLUDED.gl_user_id,
    gl_username = EXCLUDED.gl_username,
    updated_at = now()
RETURNING user_id, base_url, token_enc, gl_user_id, gl_username, created_at, updated_at
`

type UpsertGitlabCredentialParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BaseUrl    string    `json:"base_url"`
	TokenEnc   string    `json:"token_enc"`
	GlUserID   int64     `json:"gl_user_id"`
	GlUsername string    `json:"gl_username"`
}

// GitLab integration queries (Phase A, pull-only).
// ── Per-user credential ────────────────────────────────────
func (q *Queries) UpsertGitlabCredential(ctx context.Context, arg UpsertGitlabCredentialParams) (GitlabCredential, error) {
	row := q.db.QueryRow(ctx, upsertGitlabCredential,
		arg.UserID,
		arg.BaseUrl,
		arg.TokenEnc,
		arg.GlUserID,
		arg.GlUsername,
	)
	var i GitlabCredential
	err := row.Scan(
		&i.UserID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.GlUserID,
		&i.GlUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitlabProjectMember = `-- name: UpsertGitlabProjectMember :exec
INSERT INTO gitlab_project_members (integration_id, gl_user_id, gl_username, gl_name, gl_avatar_url, access_level, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (integration_id, gl_user_id) DO UPDATE SET
    gl_username = EXCLUDED.gl_username, gl_name = EXCLUDED.gl_name,
    gl_avatar_url = EXCLUDED.gl_avatar_url, access_level = EXCLUDED.access_level, updated_at = now()
`

type UpsertGitlabProjectMemberParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlUserID      int64     `json:"gl_user_id"`
	GlUsername    string    `json:"gl_username"`
	GlName        string    `json:"gl_name"`
	GlAvatarUrl   string    `json:"gl_avatar_url"`
	AccessLevel   int32     `json:"access_level"`
}

// ── GitLab project members (assignable from Tessera) ───────
func (q *Queries) UpsertGitlabProjectMember(ctx context.Context, arg UpsertGitlabProjectMemberParams) error {
	_, err := q.db.Exec(ctx, upsertGitlabProjectMember,
		arg.IntegrationID,
		arg.GlUserID,
		arg.GlUsername,
		arg.GlName,
		arg.GlAvatarUrl,
		arg.AccessLevel,
	)
	return err
}

const upsertGitlabSourcedAssignee = `-- name: UpsertGitlabSourcedAssignee :exec
INSERT INTO task_gitlab_assignees (task_id, gl_username, gl_name, gl_avatar_url, source) VALUES ($1, $2, $3, $4, 'gitlab')
ON CONFLICT (task_id, gl_username) DO UPDATE SET gl_name = EXCLUDED.gl_name, gl_avatar_url = EXCLUDED.gl_avatar_url
`

type UpsertGitlabSourcedAssigneeParams struct {
	TaskID      uuid.UUID `json:"task_id"`
	GlUsername  string    `json:"gl_username"`
	GlName      string    `json:"gl_name"`
	GlAvatarUrl string    `json:"gl_avatar_url"`
}

// Sync upsert: never downgrades an existing user-pinned row's source.
func (q *Queries) UpsertGitlabSourcedAssignee(ctx context.Context, arg UpsertGitlabSourcedAssigneeParams) error {
	_, err := q.db.Exec(ctx, upsertGitlabSourcedAssignee,
		arg.TaskID,
		arg.GlUsername,
		arg.GlName,
		arg.GlAvatarUrl,
	)
	return err
}
