// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab_journal.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createGitlabSyncAction = `-- name: CreateGitlabSyncAction :exec
INSERT INTO gitlab_sync_actions (
    run_id, seq, direction, entity_type, op, task_id, gl_iid, summary, detail, status, error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateGitlabSyncActionParams struct {
	RunID      uuid.UUID  `json:"run_id"`
	Seq        int32      `json:"seq"`
	Direction  string     `json:"direction"`
	EntityType string     `json:"entity_type"`
	Op         string     `json:"op"`
	TaskID     *uuid.UUID `json:"task_id"`
	GlIid      *int64     `json:"gl_iid"`
	Summary    string     `json:"summary"`
	Detail     []byte     `json:"detail"`
	Status     string     `json:"status"`
	Error      string     `json:"error"`
}

func (q *Queries) CreateGitlabSyncAction(ctx context.Context, arg CreateGitlabSyncActionParams) error {
	_, err := q.db.Exec(ctx, createGitlabSyncAction,
		arg.RunID,
		arg.Seq,
		arg.Direction,
		arg.EntityType,
		arg.Op,
		arg.TaskID,
		arg.GlIid,
		arg.Summary,
		arg.Detail,
		arg.Status,
		arg.Error,
	)
	return err
}

const createGitlabSyncRun = `-- name: CreateGitlabSyncRun :one

INSERT INTO gitlab_sync_runs (integration_id, kind, trigger, actor_id, started_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, integration_id, kind, trigger, actor_id, status, created_count, updated_count, deleted_count, action_count, error, started_at, finished_at
`

type CreateGitlabSyncRunParams struct {
	IntegrationID uuid.UUID  `json:"integration_id"`
	Kind          string     `json:"kind"`
	Trigger       string     `json:"trigger"`
	ActorID       *uuid.UUID `json:"actor_id"`
}

// GitLab sync journal: run + action history written by the pull engine and the
// write-back worker, read back by the journal modal. See migration 0033.
func (q *Queries) CreateGitlabSyncRun(ctx context.Context, arg CreateGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, createGitlabSyncRun,
		arg.IntegrationID,
		arg.Kind,
		arg.Trigger,
		arg.ActorID,
	)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Kind,
		&i.Trigger,
		&i.ActorID,
		&i.Status,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.DeletedCount,
		&i.ActionCount,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishGitlabSyncRun = `-- name: FinishGitlabSyncRun :exec
UPDATE gitlab_sync_runs
SET status = $2, created_count = $3, updated_count = $4, deleted_count = $5,
    action_count = $6, error = $7, finished_at = now()
WHERE id = $1
`

type FinishGitlabSyncRunParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	CreatedCount int32     `json:"created_count"`
	UpdatedCount int32     `json:"updated_count"`
	DeletedCount int32     `json:"deleted_count"`
	ActionCount  int32     `json:"action_count"`
	Error        string    `json:"error"`
}

// FinishGitlabSyncRun stamps the final status, counts and finish time once a run
// (and all its actions) is recorded.
func (q *Queries) FinishGitlabSyncRun(ctx context.Context, arg FinishGitlabSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishGitlabSyncRun,
		arg.ID,
		arg.Status,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.DeletedCount,
		arg.ActionCount,
		arg.Error,
	)
	return err
}

const getGitlabSyncAction = `-- name: GetGitlabSyncAction :one
SELECT a.id, a.run_id, a.seq, a.direction, a.entity_type, a.op, a.task_id, a.gl_iid, a.summary, a.detail, a.status, a.error, a.created_at FROM gitlab_sync_actions a
JOIN gitlab_sync_runs r ON r.id = a.run_id
WHERE a.id = $1 AND r.integration_id = $2
`

type GetGitlabSyncActionParams struct {
	ID            uuid.UUID `json:"id"`
	IntegrationID uuid.UUID `json:"integration_id"`
}

func (q *Queries) GetGitlabSyncAction(ctx context.Context, arg GetGitlabSyncActionParams) (GitlabSyncAction, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncAction, arg.ID, arg.IntegrationID)
	var i GitlabSyncAction
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Direction,
		&i.EntityType,
		&i.Op,
		&i.TaskID,
		&i.GlIid,
		&i.Summary,
		&i.Detail,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getGitlabSyncRun = `-- name: GetGitlabSyncRun :one
SELECT id, integration_id, kind, trigger, actor_id, status, created_count, updated_count, deleted_count, action_count, error, started_at, finished_at FROM gitlab_sync_runs WHERE id = $1 AND integration_id = $2
`

type GetGitlabSyncRunParams struct {
	ID            uuid.UUID `json:"id"`
	IntegrationID uuid.UUID `json:"integration_id"`
}

// GetGitlabSyncRun fetches a run scoped to its integration (ownership check).
func (q *Queries) GetGitlabSyncRun(ctx context.Context, arg GetGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncRun, arg.ID, arg.IntegrationID)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Kind,
		&i.Trigger,
		&i.ActorID,
		&i.Status,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.DeletedCount,
		&i.ActionCount,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listGitlabSyncActions = `-- name: ListGitlabSyncActions :many
SELECT id, run_id, seq, direction, entity_type, op, task_id, gl_iid, summary, detail, status, error, created_at FROM gitlab_sync_actions
WHERE run_id = $1
ORDER BY seq
`

func (q *Queries) ListGitlabSyncActions(ctx context.Context, runID uuid.UUID) ([]GitlabSyncAction, error) {
	rows, err := q.db.Query(ctx, listGitlabSyncActions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabSyncAction
	for rows.Next() {
		var i GitlabSyncAction
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Direction,
			&i.EntityType,
			&i.Op,
			&i.TaskID,
			&i.GlIid,
			&i.Summary,
			&i.Detail,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitlabSyncRuns = `-- name: ListGitlabSyncRuns :many
SELECT id, integration_id, kind, trigger, actor_id, status, created_count, updated_count, deleted_count, action_count, error, started_at, finished_at FROM gitlab_sync_runs
WHERE integration_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListGitlabSyncRunsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListGitlabSyncRuns(ctx context.Context, arg ListGitlabSyncRunsParams) ([]GitlabSyncRun, error) {
	rows, err := q.db.Query(ctx, listGitlabSyncRuns, arg.IntegrationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabSyncRun
	for rows.Next() {
		var i GitlabSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Kind,
			&i.Trigger,
			&i.ActorID,
			&i.Status,
			&i.CreatedCount,
			&i.UpdatedCount,
			&i.DeletedCount,
			&i.ActionCount,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneGitlabSyncRuns = `-- name: PruneGitlabSyncRuns :exec
DELETE FROM gitlab_sync_runs r
WHERE r.integration_id = $1
  AND r.id NOT IN (
    SELECT s.id FROM gitlab_sync_runs s
    WHERE s.integration_id = $1
    ORDER BY s.started_at DESC
    LIMIT $2
  )
`

type PruneGitlabSyncRunsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
}

// PruneGitlabSyncRuns keeps only the most recent $2 runs of an integration; older
// runs (and their actions, via ON DELETE CASCADE) are dropped so the journal stays
// bounded.
func (q *Queries) PruneGitlabSyncRuns(ctx context.Context, arg PruneGitlabSyncRunsParams) error {
	_, err := q.db.Exec(ctx, pruneGitlabSyncRuns, arg.IntegrationID, arg.Limit)
	return err
}
