// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTaskAssigneeSourced = `-- name: AddTaskAssigneeSourced :exec
INSERT INTO task_assignees (task_id, user_id, source) VALUES ($1, $2, $3)
ON CONFLICT (task_id, user_id) DO NOTHING
`

type AddTaskAssigneeSourcedParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

func (q *Queries) AddTaskAssigneeSourced(ctx context.Context, arg AddTaskAssigneeSourcedParams) error {
	_, err := q.db.Exec(ctx, addTaskAssigneeSourced, arg.TaskID, arg.UserID, arg.Source)
	return err
}

const addTaskGitlabAssignee = `-- name: AddTaskGitlabAssignee :exec
INSERT INTO task_gitlab_assignees (task_id, gl_username, gl_name, gl_avatar_url) VALUES ($1, $2, $3, $4)
ON CONFLICT (task_id, gl_username) DO UPDATE SET gl_name = EXCLUDED.gl_name, gl_avatar_url = EXCLUDED.gl_avatar_url
`

type AddTaskGitlabAssigneeParams struct {
	TaskID      uuid.UUID `json:"task_id"`
	GlUsername  string    `json:"gl_username"`
	GlName      string    `json:"gl_name"`
	GlAvatarUrl string    `json:"gl_avatar_url"`
}

func (q *Queries) AddTaskGitlabAssignee(ctx context.Context, arg AddTaskGitlabAssigneeParams) error {
	_, err := q.db.Exec(ctx, addTaskGitlabAssignee,
		arg.TaskID,
		arg.GlUsername,
		arg.GlName,
		arg.GlAvatarUrl,
	)
	return err
}

const addTaskTagSourced = `-- name: AddTaskTagSourced :exec
INSERT INTO task_tags (task_id, tag_id, source) VALUES ($1, $2, $3)
ON CONFLICT (task_id, tag_id) DO NOTHING
`

type AddTaskTagSourcedParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
	Source string    `json:"source"`
}

func (q *Queries) AddTaskTagSourced(ctx context.Context, arg AddTaskTagSourcedParams) error {
	_, err := q.db.Exec(ctx, addTaskTagSourced, arg.TaskID, arg.TagID, arg.Source)
	return err
}

const createGitlabLink = `-- name: CreateGitlabLink :one
INSERT INTO gitlab_links (
    task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url,
    gl_updated_at, title_hash, desc_hash, labels_hash, gl_author, gl_author_name,
    gl_author_avatar_url
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url
`

type CreateGitlabLinkParams struct {
	TaskID            uuid.UUID  `json:"task_id"`
	IntegrationID     uuid.UUID  `json:"integration_id"`
	GlGlobalID        string     `json:"gl_global_id"`
	GlIid             int64      `json:"gl_iid"`
	GlProjectPath     string     `json:"gl_project_path"`
	GlWebUrl          string     `json:"gl_web_url"`
	GlUpdatedAt       *time.Time `json:"gl_updated_at"`
	TitleHash         string     `json:"title_hash"`
	DescHash          string     `json:"desc_hash"`
	LabelsHash        string     `json:"labels_hash"`
	GlAuthor          string     `json:"gl_author"`
	GlAuthorName      string     `json:"gl_author_name"`
	GlAuthorAvatarUrl string     `json:"gl_author_avatar_url"`
}

func (q *Queries) CreateGitlabLink(ctx context.Context, arg CreateGitlabLinkParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, createGitlabLink,
		arg.TaskID,
		arg.IntegrationID,
		arg.GlGlobalID,
		arg.GlIid,
		arg.GlProjectPath,
		arg.GlWebUrl,
		arg.GlUpdatedAt,
		arg.TitleHash,
		arg.DescHash,
		arg.LabelsHash,
		arg.GlAuthor,
		arg.GlAuthorName,
		arg.GlAuthorAvatarUrl,
	)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
	)
	return i, err
}

const deleteGitlabCredential = `-- name: DeleteGitlabCredential :exec
DELETE FROM gitlab_credentials WHERE user_id = $1
`

func (q *Queries) DeleteGitlabCredential(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitlabCredential, userID)
	return err
}

const deleteStaleGitlabAssignees = `-- name: DeleteStaleGitlabAssignees :exec
DELETE FROM task_assignees
WHERE task_id = $1 AND source = 'gitlab' AND NOT (user_id = ANY($2::uuid[]))
`

type DeleteStaleGitlabAssigneesParams struct {
	TaskID  uuid.UUID   `json:"task_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) DeleteStaleGitlabAssignees(ctx context.Context, arg DeleteStaleGitlabAssigneesParams) error {
	_, err := q.db.Exec(ctx, deleteStaleGitlabAssignees, arg.TaskID, arg.Column2)
	return err
}

const deleteStaleGitlabTaskTags = `-- name: DeleteStaleGitlabTaskTags :exec
DELETE FROM task_tags
WHERE task_id = $1 AND source = 'gitlab' AND NOT (tag_id = ANY($2::uuid[]))
`

type DeleteStaleGitlabTaskTagsParams struct {
	TaskID  uuid.UUID   `json:"task_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) DeleteStaleGitlabTaskTags(ctx context.Context, arg DeleteStaleGitlabTaskTagsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleGitlabTaskTags, arg.TaskID, arg.Column2)
	return err
}

const deleteTaskGitlabAssignees = `-- name: DeleteTaskGitlabAssignees :exec
DELETE FROM task_gitlab_assignees WHERE task_id = $1
`

// ── external GitLab assignees (no Tessera account) ─────────
func (q *Queries) DeleteTaskGitlabAssignees(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskGitlabAssignees, taskID)
	return err
}

const getGitlabCredential = `-- name: GetGitlabCredential :one
SELECT user_id, base_url, token_enc, gl_user_id, gl_username, created_at, updated_at FROM gitlab_credentials WHERE user_id = $1
`

func (q *Queries) GetGitlabCredential(ctx context.Context, userID uuid.UUID) (GitlabCredential, error) {
	row := q.db.QueryRow(ctx, getGitlabCredential, userID)
	var i GitlabCredential
	err := row.Scan(
		&i.UserID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.GlUserID,
		&i.GlUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabIntegrationByWorkspace = `-- name: GetGitlabIntegrationByWorkspace :one
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source FROM gitlab_integrations WHERE workspace_id = $1
`

func (q *Queries) GetGitlabIntegrationByWorkspace(ctx context.Context, workspaceID uuid.UUID) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegrationByWorkspace, workspaceID)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
	)
	return i, err
}

const getGitlabLinkByGlobalID = `-- name: GetGitlabLinkByGlobalID :one

SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url FROM gitlab_links WHERE integration_id = $1 AND gl_global_id = $2
`

type GetGitlabLinkByGlobalIDParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlGlobalID    string    `json:"gl_global_id"`
}

// ── Task ↔ work item link ──────────────────────────────────
func (q *Queries) GetGitlabLinkByGlobalID(ctx context.Context, arg GetGitlabLinkByGlobalIDParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByGlobalID, arg.IntegrationID, arg.GlGlobalID)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
	)
	return i, err
}

const getGitlabLinkByTask = `-- name: GetGitlabLinkByTask :one
SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url FROM gitlab_links WHERE task_id = $1
`

func (q *Queries) GetGitlabLinkByTask(ctx context.Context, taskID uuid.UUID) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByTask, taskID)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
	)
	return i, err
}

const getUserIDByGitlabUsername = `-- name: GetUserIDByGitlabUsername :one
SELECT user_id FROM gitlab_credentials WHERE gl_username = $1
`

// ── sync reconciliation: mixed tags / assignees ────────────
// Resolve a GitLab username to a Tessera user (via their linked credential).
func (q *Queries) GetUserIDByGitlabUsername(ctx context.Context, glUsername string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByGitlabUsername, glUsername)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const linkedIidsForIntegration = `-- name: LinkedIidsForIntegration :many
SELECT gl_iid FROM gitlab_links WHERE integration_id = $1
`

func (q *Queries) LinkedIidsForIntegration(ctx context.Context, integrationID uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, linkedIidsForIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var gl_iid int64
		if err := rows.Scan(&gl_iid); err != nil {
			return nil, err
		}
		items = append(items, gl_iid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoSyncIntegrations = `-- name: ListAutoSyncIntegrations :many
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source FROM gitlab_integrations
WHERE enabled
  AND sync_interval_sec > 0
  AND owner_user_id IS NOT NULL
  AND (last_synced_at IS NULL OR last_synced_at < now() - make_interval(secs => sync_interval_sec))
`

// ListAutoSyncIntegrations returns integrations due for unattended sync: enabled,
// with a positive interval, an owner credential set, and either never synced or
// past their interval. Used by the background worker.
func (q *Queries) ListAutoSyncIntegrations(ctx context.Context) ([]GitlabIntegration, error) {
	rows, err := q.db.Query(ctx, listAutoSyncIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabIntegration
	for rows.Next() {
		var i GitlabIntegration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectPath,
			&i.BoardID,
			&i.LabelRules,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.SyncIntervalSec,
			&i.LastSyncedAt,
			&i.DueSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskGitlabAssignees = `-- name: ListTaskGitlabAssignees :many
SELECT gl_username, gl_name, gl_avatar_url FROM task_gitlab_assignees WHERE task_id = $1 ORDER BY gl_name
`

type ListTaskGitlabAssigneesRow struct {
	GlUsername  string `json:"gl_username"`
	GlName      string `json:"gl_name"`
	GlAvatarUrl string `json:"gl_avatar_url"`
}

func (q *Queries) ListTaskGitlabAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskGitlabAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskGitlabAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskGitlabAssigneesRow
	for rows.Next() {
		var i ListTaskGitlabAssigneesRow
		if err := rows.Scan(&i.GlUsername, &i.GlName, &i.GlAvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGitlabDueOverridden = `-- name: MarkGitlabDueOverridden :exec
UPDATE gitlab_links SET due_overridden = true WHERE task_id = $1
`

// MarkGitlabDueOverridden flags a linked task's due as user-set so the sync stops
// touching it. No-op when the task isn't linked.
func (q *Queries) MarkGitlabDueOverridden(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabDueOverridden, taskID)
	return err
}

const markGitlabSynced = `-- name: MarkGitlabSynced :exec
UPDATE gitlab_integrations SET last_synced_at = now() WHERE id = $1
`

// MarkGitlabSynced stamps the integration's last successful sync time.
func (q *Queries) MarkGitlabSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabSynced, id)
	return err
}

const syncUpdateTask = `-- name: SyncUpdateTask :one
UPDATE tasks
SET title = $2, description = $3, priority = $4, column_id = $5, completed_at = $6, board_id = $7, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant
`

type SyncUpdateTaskParams struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Priority    int32      `json:"priority"`
	ColumnID    uuid.UUID  `json:"column_id"`
	CompletedAt *time.Time `json:"completed_at"`
	BoardID     uuid.UUID  `json:"board_id"`
}

// SyncUpsertTask updates the synced fields of a linked task without touching its
// position (the user may have reordered it on the board).
func (q *Queries) SyncUpdateTask(ctx context.Context, arg SyncUpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, syncUpdateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.ColumnID,
		arg.CompletedAt,
		arg.BoardID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
	)
	return i, err
}

const updateGitlabLink = `-- name: UpdateGitlabLink :one
UPDATE gitlab_links
SET gl_iid = $2, gl_web_url = $3, gl_updated_at = $4,
    title_hash = $5, desc_hash = $6, labels_hash = $7,
    gl_author = $8, gl_author_name = $9, gl_author_avatar_url = $10,
    last_synced_at = now()
WHERE task_id = $1
RETURNING task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name, due_overridden, gl_author_avatar_url
`

type UpdateGitlabLinkParams struct {
	TaskID            uuid.UUID  `json:"task_id"`
	GlIid             int64      `json:"gl_iid"`
	GlWebUrl          string     `json:"gl_web_url"`
	GlUpdatedAt       *time.Time `json:"gl_updated_at"`
	TitleHash         string     `json:"title_hash"`
	DescHash          string     `json:"desc_hash"`
	LabelsHash        string     `json:"labels_hash"`
	GlAuthor          string     `json:"gl_author"`
	GlAuthorName      string     `json:"gl_author_name"`
	GlAuthorAvatarUrl string     `json:"gl_author_avatar_url"`
}

func (q *Queries) UpdateGitlabLink(ctx context.Context, arg UpdateGitlabLinkParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, updateGitlabLink,
		arg.TaskID,
		arg.GlIid,
		arg.GlWebUrl,
		arg.GlUpdatedAt,
		arg.TitleHash,
		arg.DescHash,
		arg.LabelsHash,
		arg.GlAuthor,
		arg.GlAuthorName,
		arg.GlAuthorAvatarUrl,
	)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
		&i.DueOverridden,
		&i.GlAuthorAvatarUrl,
	)
	return i, err
}

const upsertGitlabComment = `-- name: UpsertGitlabComment :exec
INSERT INTO task_comments (task_id, author_id, body, gl_note_id, gl_author_login, gl_author_name, gl_author_avatar_url, created_at, updated_at)
VALUES ($1, NULL, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (gl_note_id) WHERE gl_note_id IS NOT NULL
DO UPDATE SET body = EXCLUDED.body, gl_author_name = EXCLUDED.gl_author_name, gl_author_avatar_url = EXCLUDED.gl_author_avatar_url, updated_at = now()
`

type UpsertGitlabCommentParams struct {
	TaskID            uuid.UUID `json:"task_id"`
	Body              string    `json:"body"`
	GlNoteID          *string   `json:"gl_note_id"`
	GlAuthorLogin     string    `json:"gl_author_login"`
	GlAuthorName      string    `json:"gl_author_name"`
	GlAuthorAvatarUrl string    `json:"gl_author_avatar_url"`
	CreatedAt         time.Time `json:"created_at"`
}

// ── synced comments (idempotent by GitLab note id) ─────────
func (q *Queries) UpsertGitlabComment(ctx context.Context, arg UpsertGitlabCommentParams) error {
	_, err := q.db.Exec(ctx, upsertGitlabComment,
		arg.TaskID,
		arg.Body,
		arg.GlNoteID,
		arg.GlAuthorLogin,
		arg.GlAuthorName,
		arg.GlAuthorAvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const upsertGitlabCredential = `-- name: UpsertGitlabCredential :one


INSERT INTO gitlab_credentials (user_id, base_url, token_enc, gl_user_id, gl_username, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id) DO UPDATE
SET base_url = EXCLUDED.base_url,
    token_enc = EXCLUDED.token_enc,
    gl_user_id = EXCLUDED.gl_user_id,
    gl_username = EXCLUDED.gl_username,
    updated_at = now()
RETURNING user_id, base_url, token_enc, gl_user_id, gl_username, created_at, updated_at
`

type UpsertGitlabCredentialParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BaseUrl    string    `json:"base_url"`
	TokenEnc   string    `json:"token_enc"`
	GlUserID   int64     `json:"gl_user_id"`
	GlUsername string    `json:"gl_username"`
}

// GitLab integration queries (Phase A, pull-only).
// ── Per-user credential ────────────────────────────────────
func (q *Queries) UpsertGitlabCredential(ctx context.Context, arg UpsertGitlabCredentialParams) (GitlabCredential, error) {
	row := q.db.QueryRow(ctx, upsertGitlabCredential,
		arg.UserID,
		arg.BaseUrl,
		arg.TokenEnc,
		arg.GlUserID,
		arg.GlUsername,
	)
	var i GitlabCredential
	err := row.Scan(
		&i.UserID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.GlUserID,
		&i.GlUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitlabIntegration = `-- name: UpsertGitlabIntegration :one

INSERT INTO gitlab_integrations (workspace_id, project_path, board_id, label_rules, enabled, owner_user_id, sync_interval_sec, due_source, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (workspace_id) DO UPDATE
SET project_path = EXCLUDED.project_path,
    board_id = EXCLUDED.board_id,
    label_rules = EXCLUDED.label_rules,
    enabled = EXCLUDED.enabled,
    owner_user_id = EXCLUDED.owner_user_id,
    sync_interval_sec = EXCLUDED.sync_interval_sec,
    due_source = EXCLUDED.due_source,
    updated_at = now()
RETURNING id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source
`

type UpsertGitlabIntegrationParams struct {
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	ProjectPath     string     `json:"project_path"`
	BoardID         uuid.UUID  `json:"board_id"`
	LabelRules      []byte     `json:"label_rules"`
	Enabled         bool       `json:"enabled"`
	OwnerUserID     *uuid.UUID `json:"owner_user_id"`
	SyncIntervalSec int32      `json:"sync_interval_sec"`
	DueSource       string     `json:"due_source"`
}

// ── Per-workspace integration ──────────────────────────────
func (q *Queries) UpsertGitlabIntegration(ctx context.Context, arg UpsertGitlabIntegrationParams) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, upsertGitlabIntegration,
		arg.WorkspaceID,
		arg.ProjectPath,
		arg.BoardID,
		arg.LabelRules,
		arg.Enabled,
		arg.OwnerUserID,
		arg.SyncIntervalSec,
		arg.DueSource,
	)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
	)
	return i, err
}
