// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGitlabLink = `-- name: CreateGitlabLink :one
INSERT INTO gitlab_links (
    task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url,
    gl_updated_at, title_hash, desc_hash, labels_hash, gl_author, gl_author_name
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name
`

type CreateGitlabLinkParams struct {
	TaskID        uuid.UUID  `json:"task_id"`
	IntegrationID uuid.UUID  `json:"integration_id"`
	GlGlobalID    string     `json:"gl_global_id"`
	GlIid         int64      `json:"gl_iid"`
	GlProjectPath string     `json:"gl_project_path"`
	GlWebUrl      string     `json:"gl_web_url"`
	GlUpdatedAt   *time.Time `json:"gl_updated_at"`
	TitleHash     string     `json:"title_hash"`
	DescHash      string     `json:"desc_hash"`
	LabelsHash    string     `json:"labels_hash"`
	GlAuthor      string     `json:"gl_author"`
	GlAuthorName  string     `json:"gl_author_name"`
}

func (q *Queries) CreateGitlabLink(ctx context.Context, arg CreateGitlabLinkParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, createGitlabLink,
		arg.TaskID,
		arg.IntegrationID,
		arg.GlGlobalID,
		arg.GlIid,
		arg.GlProjectPath,
		arg.GlWebUrl,
		arg.GlUpdatedAt,
		arg.TitleHash,
		arg.DescHash,
		arg.LabelsHash,
		arg.GlAuthor,
		arg.GlAuthorName,
	)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
	)
	return i, err
}

const deleteGitlabCredential = `-- name: DeleteGitlabCredential :exec
DELETE FROM gitlab_credentials WHERE user_id = $1
`

func (q *Queries) DeleteGitlabCredential(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitlabCredential, userID)
	return err
}

const getGitlabCredential = `-- name: GetGitlabCredential :one
SELECT user_id, base_url, token_enc, gl_user_id, gl_username, created_at, updated_at FROM gitlab_credentials WHERE user_id = $1
`

func (q *Queries) GetGitlabCredential(ctx context.Context, userID uuid.UUID) (GitlabCredential, error) {
	row := q.db.QueryRow(ctx, getGitlabCredential, userID)
	var i GitlabCredential
	err := row.Scan(
		&i.UserID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.GlUserID,
		&i.GlUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitlabIntegrationByWorkspace = `-- name: GetGitlabIntegrationByWorkspace :one
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at FROM gitlab_integrations WHERE workspace_id = $1
`

func (q *Queries) GetGitlabIntegrationByWorkspace(ctx context.Context, workspaceID uuid.UUID) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegrationByWorkspace, workspaceID)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
	)
	return i, err
}

const getGitlabLinkByGlobalID = `-- name: GetGitlabLinkByGlobalID :one

SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name FROM gitlab_links WHERE integration_id = $1 AND gl_global_id = $2
`

type GetGitlabLinkByGlobalIDParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlGlobalID    string    `json:"gl_global_id"`
}

// ── Task ↔ work item link ──────────────────────────────────
func (q *Queries) GetGitlabLinkByGlobalID(ctx context.Context, arg GetGitlabLinkByGlobalIDParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByGlobalID, arg.IntegrationID, arg.GlGlobalID)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
	)
	return i, err
}

const getGitlabLinkByTask = `-- name: GetGitlabLinkByTask :one
SELECT task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name FROM gitlab_links WHERE task_id = $1
`

func (q *Queries) GetGitlabLinkByTask(ctx context.Context, taskID uuid.UUID) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, getGitlabLinkByTask, taskID)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
	)
	return i, err
}

const listAutoSyncIntegrations = `-- name: ListAutoSyncIntegrations :many
SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at FROM gitlab_integrations
WHERE enabled
  AND sync_interval_sec > 0
  AND owner_user_id IS NOT NULL
  AND (last_synced_at IS NULL OR last_synced_at < now() - make_interval(secs => sync_interval_sec))
`

// ListAutoSyncIntegrations returns integrations due for unattended sync: enabled,
// with a positive interval, an owner credential set, and either never synced or
// past their interval. Used by the background worker.
func (q *Queries) ListAutoSyncIntegrations(ctx context.Context) ([]GitlabIntegration, error) {
	rows, err := q.db.Query(ctx, listAutoSyncIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabIntegration
	for rows.Next() {
		var i GitlabIntegration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectPath,
			&i.BoardID,
			&i.LabelRules,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerUserID,
			&i.SyncIntervalSec,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGitlabSynced = `-- name: MarkGitlabSynced :exec
UPDATE gitlab_integrations SET last_synced_at = now() WHERE id = $1
`

// MarkGitlabSynced stamps the integration's last successful sync time.
func (q *Queries) MarkGitlabSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGitlabSynced, id)
	return err
}

const syncUpdateTask = `-- name: SyncUpdateTask :one
UPDATE tasks
SET title = $2, description = $3, priority = $4, column_id = $5, completed_at = $6, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number
`

type SyncUpdateTaskParams struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Priority    int32      `json:"priority"`
	ColumnID    uuid.UUID  `json:"column_id"`
	CompletedAt *time.Time `json:"completed_at"`
}

// SyncUpsertTask updates the synced fields of a linked task without touching its
// position (the user may have reordered it on the board).
func (q *Queries) SyncUpdateTask(ctx context.Context, arg SyncUpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, syncUpdateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.ColumnID,
		arg.CompletedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
	)
	return i, err
}

const updateGitlabLink = `-- name: UpdateGitlabLink :one
UPDATE gitlab_links
SET gl_iid = $2, gl_web_url = $3, gl_updated_at = $4,
    title_hash = $5, desc_hash = $6, labels_hash = $7,
    gl_author = $8, gl_author_name = $9, last_synced_at = now()
WHERE task_id = $1
RETURNING task_id, integration_id, gl_global_id, gl_iid, gl_project_path, gl_web_url, gl_updated_at, title_hash, desc_hash, labels_hash, last_synced_at, created_at, gl_author, gl_author_name
`

type UpdateGitlabLinkParams struct {
	TaskID       uuid.UUID  `json:"task_id"`
	GlIid        int64      `json:"gl_iid"`
	GlWebUrl     string     `json:"gl_web_url"`
	GlUpdatedAt  *time.Time `json:"gl_updated_at"`
	TitleHash    string     `json:"title_hash"`
	DescHash     string     `json:"desc_hash"`
	LabelsHash   string     `json:"labels_hash"`
	GlAuthor     string     `json:"gl_author"`
	GlAuthorName string     `json:"gl_author_name"`
}

func (q *Queries) UpdateGitlabLink(ctx context.Context, arg UpdateGitlabLinkParams) (GitlabLink, error) {
	row := q.db.QueryRow(ctx, updateGitlabLink,
		arg.TaskID,
		arg.GlIid,
		arg.GlWebUrl,
		arg.GlUpdatedAt,
		arg.TitleHash,
		arg.DescHash,
		arg.LabelsHash,
		arg.GlAuthor,
		arg.GlAuthorName,
	)
	var i GitlabLink
	err := row.Scan(
		&i.TaskID,
		&i.IntegrationID,
		&i.GlGlobalID,
		&i.GlIid,
		&i.GlProjectPath,
		&i.GlWebUrl,
		&i.GlUpdatedAt,
		&i.TitleHash,
		&i.DescHash,
		&i.LabelsHash,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.GlAuthor,
		&i.GlAuthorName,
	)
	return i, err
}

const upsertGitlabCredential = `-- name: UpsertGitlabCredential :one


INSERT INTO gitlab_credentials (user_id, base_url, token_enc, gl_user_id, gl_username, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id) DO UPDATE
SET base_url = EXCLUDED.base_url,
    token_enc = EXCLUDED.token_enc,
    gl_user_id = EXCLUDED.gl_user_id,
    gl_username = EXCLUDED.gl_username,
    updated_at = now()
RETURNING user_id, base_url, token_enc, gl_user_id, gl_username, created_at, updated_at
`

type UpsertGitlabCredentialParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BaseUrl    string    `json:"base_url"`
	TokenEnc   string    `json:"token_enc"`
	GlUserID   int64     `json:"gl_user_id"`
	GlUsername string    `json:"gl_username"`
}

// GitLab integration queries (Phase A, pull-only).
// ── Per-user credential ────────────────────────────────────
func (q *Queries) UpsertGitlabCredential(ctx context.Context, arg UpsertGitlabCredentialParams) (GitlabCredential, error) {
	row := q.db.QueryRow(ctx, upsertGitlabCredential,
		arg.UserID,
		arg.BaseUrl,
		arg.TokenEnc,
		arg.GlUserID,
		arg.GlUsername,
	)
	var i GitlabCredential
	err := row.Scan(
		&i.UserID,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.GlUserID,
		&i.GlUsername,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGitlabIntegration = `-- name: UpsertGitlabIntegration :one

INSERT INTO gitlab_integrations (workspace_id, project_path, board_id, label_rules, enabled, owner_user_id, sync_interval_sec, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (workspace_id) DO UPDATE
SET project_path = EXCLUDED.project_path,
    board_id = EXCLUDED.board_id,
    label_rules = EXCLUDED.label_rules,
    enabled = EXCLUDED.enabled,
    owner_user_id = EXCLUDED.owner_user_id,
    sync_interval_sec = EXCLUDED.sync_interval_sec,
    updated_at = now()
RETURNING id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at
`

type UpsertGitlabIntegrationParams struct {
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	ProjectPath     string     `json:"project_path"`
	BoardID         uuid.UUID  `json:"board_id"`
	LabelRules      []byte     `json:"label_rules"`
	Enabled         bool       `json:"enabled"`
	OwnerUserID     *uuid.UUID `json:"owner_user_id"`
	SyncIntervalSec int32      `json:"sync_interval_sec"`
}

// ── Per-workspace integration ──────────────────────────────
func (q *Queries) UpsertGitlabIntegration(ctx context.Context, arg UpsertGitlabIntegrationParams) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, upsertGitlabIntegration,
		arg.WorkspaceID,
		arg.ProjectPath,
		arg.BoardID,
		arg.LabelRules,
		arg.Enabled,
		arg.OwnerUserID,
		arg.SyncIntervalSec,
	)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
	)
	return i, err
}
