// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab_writeback.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimPendingWritebacks = `-- name: ClaimPendingWritebacks :many
UPDATE gitlab_writebacks
SET status = 'sending', attempts = attempts + 1, updated_at = now()
WHERE id IN (
    SELECT id FROM gitlab_writebacks
    WHERE status = 'pending' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, task_id, integration_id, change_kind, payload, status, attempts, last_error, next_attempt_at, created_at, updated_at, conflict, resolution, resolved_by, resolved_at, actor_user_id
`

// ClaimPendingWritebacks atomically grabs up to $1 due pending rows, marking them
// 'sending' and bumping attempts, so concurrent/queued workers never pick the same
// row (FOR UPDATE SKIP LOCKED).
func (q *Queries) ClaimPendingWritebacks(ctx context.Context, limit int32) ([]GitlabWriteback, error) {
	rows, err := q.db.Query(ctx, claimPendingWritebacks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabWriteback
	for rows.Next() {
		var i GitlabWriteback
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.IntegrationID,
			&i.ChangeKind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conflict,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.ActorUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coalescePendingWriteback = `-- name: CoalescePendingWriteback :execrows
UPDATE gitlab_writebacks
SET payload = $3, actor_user_id = $4, next_attempt_at = now(), updated_at = now()
WHERE task_id = $1 AND change_kind = $2 AND status = 'pending'
`

type CoalescePendingWritebackParams struct {
	TaskID      uuid.UUID  `json:"task_id"`
	ChangeKind  string     `json:"change_kind"`
	Payload     []byte     `json:"payload"`
	ActorUserID *uuid.UUID `json:"actor_user_id"`
}

// CoalescePendingWriteback refreshes an already-pending row for the same task and
// change_kind (collapsing a burst of edits into one push, latest value wins) and
// re-arms it for immediate delivery. The actor is refreshed too (latest editor wins,
// so the coalesced push is attributed to whoever made the most recent change).
// Returns the rows updated; 0 means the caller should insert a fresh row.
func (q *Queries) CoalescePendingWriteback(ctx context.Context, arg CoalescePendingWritebackParams) (int64, error) {
	result, err := q.db.Exec(ctx, coalescePendingWriteback,
		arg.TaskID,
		arg.ChangeKind,
		arg.Payload,
		arg.ActorUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGitlabWriteback = `-- name: CreateGitlabWriteback :exec
INSERT INTO gitlab_writebacks (task_id, integration_id, change_kind, payload, actor_user_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateGitlabWritebackParams struct {
	TaskID        uuid.UUID  `json:"task_id"`
	IntegrationID uuid.UUID  `json:"integration_id"`
	ChangeKind    string     `json:"change_kind"`
	Payload       []byte     `json:"payload"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
}

func (q *Queries) CreateGitlabWriteback(ctx context.Context, arg CreateGitlabWritebackParams) error {
	_, err := q.db.Exec(ctx, createGitlabWriteback,
		arg.TaskID,
		arg.IntegrationID,
		arg.ChangeKind,
		arg.Payload,
		arg.ActorUserID,
	)
	return err
}

const getCommentThreadTarget = `-- name: GetCommentThreadTarget :one
SELECT p.gl_discussion_id, p.gl_note_id
FROM task_comments c JOIN task_comments p ON p.id = c.parent_id
WHERE c.id = $1
`

type GetCommentThreadTargetRow struct {
	GlDiscussionID string  `json:"gl_discussion_id"`
	GlNoteID       *string `json:"gl_note_id"`
}

// GetCommentThreadTarget returns the GitLab discussion a reply should be posted
// into: the discussion of the reply's parent (its thread root).
func (q *Queries) GetCommentThreadTarget(ctx context.Context, id uuid.UUID) (GetCommentThreadTargetRow, error) {
	row := q.db.QueryRow(ctx, getCommentThreadTarget, id)
	var i GetCommentThreadTargetRow
	err := row.Scan(&i.GlDiscussionID, &i.GlNoteID)
	return i, err
}

const getGitlabIntegrationByID = `-- name: GetGitlabIntegrationByID :one

SELECT id, workspace_id, project_path, board_id, label_rules, enabled, created_at, updated_at, owner_user_id, sync_interval_sec, last_synced_at, due_source, start_source, writeback, name, scope, closed_policy, closed_after, last_full_synced_at, members_synced_at, full_sync_interval_sec, relations_sync FROM gitlab_integrations WHERE id = $1
`

// GitLab write-back (phase B): outbox queue + the integration lookup the worker
// needs. Mirrors the notification delivery outbox (claim / backoff / settle).
func (q *Queries) GetGitlabIntegrationByID(ctx context.Context, id uuid.UUID) (GitlabIntegration, error) {
	row := q.db.QueryRow(ctx, getGitlabIntegrationByID, id)
	var i GitlabIntegration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectPath,
		&i.BoardID,
		&i.LabelRules,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerUserID,
		&i.SyncIntervalSec,
		&i.LastSyncedAt,
		&i.DueSource,
		&i.StartSource,
		&i.Writeback,
		&i.Name,
		&i.Scope,
		&i.ClosedPolicy,
		&i.ClosedAfter,
		&i.LastFullSyncedAt,
		&i.MembersSyncedAt,
		&i.FullSyncIntervalSec,
		&i.RelationsSync,
	)
	return i, err
}

const getGitlabWriteback = `-- name: GetGitlabWriteback :one
SELECT id, task_id, integration_id, change_kind, payload, status, attempts, last_error, next_attempt_at, created_at, updated_at, conflict, resolution, resolved_by, resolved_at, actor_user_id FROM gitlab_writebacks WHERE id = $1
`

// GetGitlabWriteback fetches one outbox row by id (for the resolve endpoint).
func (q *Queries) GetGitlabWriteback(ctx context.Context, id uuid.UUID) (GitlabWriteback, error) {
	row := q.db.QueryRow(ctx, getGitlabWriteback, id)
	var i GitlabWriteback
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.IntegrationID,
		&i.ChangeKind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conflict,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ActorUserID,
	)
	return i, err
}

const getOpenConflict = `-- name: GetOpenConflict :one
SELECT id, task_id, integration_id, change_kind, payload, status, attempts, last_error, next_attempt_at, created_at, updated_at, conflict, resolution, resolved_by, resolved_at, actor_user_id FROM gitlab_writebacks
WHERE task_id = $1 AND change_kind = $2 AND status = 'conflict'
`

type GetOpenConflictParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	ChangeKind string    `json:"change_kind"`
}

// GetOpenConflict returns the open conflict row for a (task, change_kind), if any.
func (q *Queries) GetOpenConflict(ctx context.Context, arg GetOpenConflictParams) (GitlabWriteback, error) {
	row := q.db.QueryRow(ctx, getOpenConflict, arg.TaskID, arg.ChangeKind)
	var i GitlabWriteback
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.IntegrationID,
		&i.ChangeKind,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Conflict,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ActorUserID,
	)
	return i, err
}

const listOpenConflictKinds = `-- name: ListOpenConflictKinds :many
SELECT change_kind FROM gitlab_writebacks WHERE task_id = $1 AND status = 'conflict'
`

// ListOpenConflictKinds lists the change kinds with an open conflict for a task, so
// the pull can freeze those fields (not overwrite the user's pending value).
func (q *Queries) ListOpenConflictKinds(ctx context.Context, taskID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOpenConflictKinds, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var change_kind string
		if err := rows.Scan(&change_kind); err != nil {
			return nil, err
		}
		items = append(items, change_kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenConflicts = `-- name: ListOpenConflicts :many
SELECT w.id, w.task_id, w.integration_id, w.change_kind, w.payload, w.status, w.attempts, w.last_error, w.next_attempt_at, w.created_at, w.updated_at, w.conflict, w.resolution, w.resolved_by, w.resolved_at, w.actor_user_id, t.title AS task_title, t.number AS task_number
FROM gitlab_writebacks w
JOIN tasks t ON t.id = w.task_id
WHERE w.integration_id = $1 AND w.status = 'conflict'
ORDER BY w.updated_at DESC
`

type ListOpenConflictsRow struct {
	ID            uuid.UUID  `json:"id"`
	TaskID        uuid.UUID  `json:"task_id"`
	IntegrationID uuid.UUID  `json:"integration_id"`
	ChangeKind    string     `json:"change_kind"`
	Payload       []byte     `json:"payload"`
	Status        string     `json:"status"`
	Attempts      int32      `json:"attempts"`
	LastError     string     `json:"last_error"`
	NextAttemptAt time.Time  `json:"next_attempt_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	Conflict      []byte     `json:"conflict"`
	Resolution    string     `json:"resolution"`
	ResolvedBy    *uuid.UUID `json:"resolved_by"`
	ResolvedAt    *time.Time `json:"resolved_at"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
	TaskTitle     string     `json:"task_title"`
	TaskNumber    *int64     `json:"task_number"`
}

// ListOpenConflicts returns every open conflict for an integration with its task's
// title/number, newest first — powers the conflicts inbox.
func (q *Queries) ListOpenConflicts(ctx context.Context, integrationID uuid.UUID) ([]ListOpenConflictsRow, error) {
	rows, err := q.db.Query(ctx, listOpenConflicts, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenConflictsRow
	for rows.Next() {
		var i ListOpenConflictsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.IntegrationID,
			&i.ChangeKind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conflict,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.ActorUserID,
			&i.TaskTitle,
			&i.TaskNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenConflictsByWorkspace = `-- name: ListOpenConflictsByWorkspace :many
SELECT w.id, w.task_id, w.integration_id, w.change_kind, w.payload, w.status, w.attempts, w.last_error, w.next_attempt_at, w.created_at, w.updated_at, w.conflict, w.resolution, w.resolved_by, w.resolved_at, w.actor_user_id, t.title AS task_title, t.number AS task_number
FROM gitlab_writebacks w
JOIN tasks t ON t.id = w.task_id
JOIN gitlab_integrations i ON i.id = w.integration_id
WHERE i.workspace_id = $1 AND w.status = 'conflict'
ORDER BY w.updated_at DESC
`

type ListOpenConflictsByWorkspaceRow struct {
	ID            uuid.UUID  `json:"id"`
	TaskID        uuid.UUID  `json:"task_id"`
	IntegrationID uuid.UUID  `json:"integration_id"`
	ChangeKind    string     `json:"change_kind"`
	Payload       []byte     `json:"payload"`
	Status        string     `json:"status"`
	Attempts      int32      `json:"attempts"`
	LastError     string     `json:"last_error"`
	NextAttemptAt time.Time  `json:"next_attempt_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	Conflict      []byte     `json:"conflict"`
	Resolution    string     `json:"resolution"`
	ResolvedBy    *uuid.UUID `json:"resolved_by"`
	ResolvedAt    *time.Time `json:"resolved_at"`
	ActorUserID   *uuid.UUID `json:"actor_user_id"`
	TaskTitle     string     `json:"task_title"`
	TaskNumber    *int64     `json:"task_number"`
}

// ListOpenConflictsByWorkspace aggregates every open conflict across a workspace's
// bindings (multi-binding conflicts inbox), newest first.
func (q *Queries) ListOpenConflictsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListOpenConflictsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listOpenConflictsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenConflictsByWorkspaceRow
	for rows.Next() {
		var i ListOpenConflictsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.IntegrationID,
			&i.ChangeKind,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Conflict,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.ActorUserID,
			&i.TaskTitle,
			&i.TaskNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWritebackConflict = `-- name: MarkWritebackConflict :exec

UPDATE gitlab_writebacks
SET status = 'conflict', conflict = $2, updated_at = now()
WHERE id = $1
`

type MarkWritebackConflictParams struct {
	ID       uuid.UUID `json:"id"`
	Conflict []byte    `json:"conflict"`
}

// ── Write-back conflicts ────────────────────────────────────
// MarkWritebackConflict parks a claimed row as a conflict (both sides changed the
// same field since the last sync). It stays parked until the user resolves it.
func (q *Queries) MarkWritebackConflict(ctx context.Context, arg MarkWritebackConflictParams) error {
	_, err := q.db.Exec(ctx, markWritebackConflict, arg.ID, arg.Conflict)
	return err
}

const markWritebackFailed = `-- name: MarkWritebackFailed :exec
UPDATE gitlab_writebacks SET status = 'failed', last_error = $2, updated_at = now() WHERE id = $1
`

type MarkWritebackFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkWritebackFailed(ctx context.Context, arg MarkWritebackFailedParams) error {
	_, err := q.db.Exec(ctx, markWritebackFailed, arg.ID, arg.LastError)
	return err
}

const markWritebackRetry = `-- name: MarkWritebackRetry :exec
UPDATE gitlab_writebacks
SET status = 'pending', last_error = $2, next_attempt_at = $3, updated_at = now()
WHERE id = $1
`

type MarkWritebackRetryParams struct {
	ID            uuid.UUID `json:"id"`
	LastError     string    `json:"last_error"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

// MarkWritebackRetry reschedules a transient failure (back to pending, backed-off).
func (q *Queries) MarkWritebackRetry(ctx context.Context, arg MarkWritebackRetryParams) error {
	_, err := q.db.Exec(ctx, markWritebackRetry, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const markWritebackSent = `-- name: MarkWritebackSent :exec
UPDATE gitlab_writebacks SET status = 'sent', last_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkWritebackSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWritebackSent, id)
	return err
}

const reArmConflict = `-- name: ReArmConflict :exec
UPDATE gitlab_writebacks
SET status = 'pending', attempts = 0, last_error = '', next_attempt_at = now(),
    conflict = '{}'::jsonb, resolution = $2, resolved_by = $3, resolved_at = now(),
    updated_at = now()
WHERE id = $1
`

type ReArmConflictParams struct {
	ID         uuid.UUID  `json:"id"`
	Resolution string     `json:"resolution"`
	ResolvedBy *uuid.UUID `json:"resolved_by"`
}

// ReArmConflict re-queues a resolved conflict for delivery (ours/manual): the
// worker re-fetches GitLab and pushes the now-acknowledged value. Records the choice.
func (q *Queries) ReArmConflict(ctx context.Context, arg ReArmConflictParams) error {
	_, err := q.db.Exec(ctx, reArmConflict, arg.ID, arg.Resolution, arg.ResolvedBy)
	return err
}

const refreshConflict = `-- name: RefreshConflict :exec
UPDATE gitlab_writebacks
SET payload = $3, conflict = $4, updated_at = now()
WHERE task_id = $1 AND change_kind = $2 AND status = 'conflict'
`

type RefreshConflictParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	ChangeKind string    `json:"change_kind"`
	Payload    []byte    `json:"payload"`
	Conflict   []byte    `json:"conflict"`
}

// RefreshConflict updates an open conflict's desired payload + conflict snapshot
// when the user edits the same field again before resolving (latest intent wins).
func (q *Queries) RefreshConflict(ctx context.Context, arg RefreshConflictParams) error {
	_, err := q.db.Exec(ctx, refreshConflict,
		arg.TaskID,
		arg.ChangeKind,
		arg.Payload,
		arg.Conflict,
	)
	return err
}

const resolveConflictSettled = `-- name: ResolveConflictSettled :exec
UPDATE gitlab_writebacks
SET status = 'sent', conflict = '{}'::jsonb, resolution = $2, resolved_by = $3,
    resolved_at = now(), updated_at = now()
WHERE id = $1
`

type ResolveConflictSettledParams struct {
	ID         uuid.UUID  `json:"id"`
	Resolution string     `json:"resolution"`
	ResolvedBy *uuid.UUID `json:"resolved_by"`
}

// ResolveConflictSettled closes a conflict with no push (theirs): the task already
// holds GitLab's value, so nothing is sent.
func (q *Queries) ResolveConflictSettled(ctx context.Context, arg ResolveConflictSettledParams) error {
	_, err := q.db.Exec(ctx, resolveConflictSettled, arg.ID, arg.Resolution, arg.ResolvedBy)
	return err
}

const setCommentGlIDs = `-- name: SetCommentGlIDs :exec
UPDATE task_comments SET gl_note_id = $2, gl_discussion_id = $3, updated_at = now() WHERE id = $1
`

type SetCommentGlIDsParams struct {
	ID             uuid.UUID `json:"id"`
	GlNoteID       *string   `json:"gl_note_id"`
	GlDiscussionID string    `json:"gl_discussion_id"`
}

// SetCommentGlIDs tags a Tessera comment with the GitLab note id created by a
// write-back push, so the next pull's comment upsert (keyed on gl_note_id) updates
// that row instead of inserting a duplicate. The discussion id is stored alongside
// it: without it a later reply from Tessera has no thread to aim at and would be
// posted as a separate root.
func (q *Queries) SetCommentGlIDs(ctx context.Context, arg SetCommentGlIDsParams) error {
	_, err := q.db.Exec(ctx, setCommentGlIDs, arg.ID, arg.GlNoteID, arg.GlDiscussionID)
	return err
}
