// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab_journal.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGitlabSyncAction = `-- name: CreateGitlabSyncAction :exec
INSERT INTO gitlab_sync_actions (
    run_id, seq, direction, entity_type, op, task_id, gl_iid, summary, detail, status, error
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateGitlabSyncActionParams struct {
	RunID      uuid.UUID  `json:"run_id"`
	Seq        int32      `json:"seq"`
	Direction  string     `json:"direction"`
	EntityType string     `json:"entity_type"`
	Op         string     `json:"op"`
	TaskID     *uuid.UUID `json:"task_id"`
	GlIid      *int64     `json:"gl_iid"`
	Summary    string     `json:"summary"`
	Detail     []byte     `json:"detail"`
	Status     string     `json:"status"`
	Error      string     `json:"error"`
}

func (q *Queries) CreateGitlabSyncAction(ctx context.Context, arg CreateGitlabSyncActionParams) error {
	_, err := q.db.Exec(ctx, createGitlabSyncAction,
		arg.RunID,
		arg.Seq,
		arg.Direction,
		arg.EntityType,
		arg.Op,
		arg.TaskID,
		arg.GlIid,
		arg.Summary,
		arg.Detail,
		arg.Status,
		arg.Error,
	)
	return err
}

const createGitlabSyncRun = `-- name: CreateGitlabSyncRun :one

INSERT INTO gitlab_sync_runs (integration_id, kind, trigger, actor_id, status, started_at, mode)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, integration_id, kind, trigger, actor_id, status, created_count, updated_count, deleted_count, action_count, error, started_at, finished_at, mode
`

type CreateGitlabSyncRunParams struct {
	IntegrationID uuid.UUID  `json:"integration_id"`
	Kind          string     `json:"kind"`
	Trigger       string     `json:"trigger"`
	ActorID       *uuid.UUID `json:"actor_id"`
	Status        string     `json:"status"`
	StartedAt     time.Time  `json:"started_at"`
	Mode          string     `json:"mode"`
}

// GitLab sync journal: run + action history written by the pull engine and the
// write-back worker, read back by the journal modal. See migration 0033.
// CreateGitlabSyncRun opens a run row. started_at is supplied by the caller (the
// real moment the sync began, not the moment it was recorded), and status is
// normally 'running' — FinishGitlabSyncRun stamps the outcome afterwards. mode is
// 'full' | 'incremental' (how issues were fetched).
func (q *Queries) CreateGitlabSyncRun(ctx context.Context, arg CreateGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, createGitlabSyncRun,
		arg.IntegrationID,
		arg.Kind,
		arg.Trigger,
		arg.ActorID,
		arg.Status,
		arg.StartedAt,
		arg.Mode,
	)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Kind,
		&i.Trigger,
		&i.ActorID,
		&i.Status,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.DeletedCount,
		&i.ActionCount,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Mode,
	)
	return i, err
}

const failStaleGitlabSyncRuns = `-- name: FailStaleGitlabSyncRuns :exec
UPDATE gitlab_sync_runs
SET status = 'error', error = 'прервано перезапуском сервиса', finished_at = now()
WHERE status = 'running' AND finished_at IS NULL
`

// FailStaleGitlabSyncRuns closes runs left in 'running' by a process that died
// mid-sync (restart/crash). Called once at startup — nothing can legitimately be
// running at that point, so no in-flight run is clobbered.
func (q *Queries) FailStaleGitlabSyncRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, failStaleGitlabSyncRuns)
	return err
}

const finishGitlabSyncRun = `-- name: FinishGitlabSyncRun :exec
UPDATE gitlab_sync_runs
SET status = $2, created_count = $3, updated_count = $4, deleted_count = $5,
    action_count = $6, error = $7, finished_at = now()
WHERE id = $1
`

type FinishGitlabSyncRunParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	CreatedCount int32     `json:"created_count"`
	UpdatedCount int32     `json:"updated_count"`
	DeletedCount int32     `json:"deleted_count"`
	ActionCount  int32     `json:"action_count"`
	Error        string    `json:"error"`
}

// FinishGitlabSyncRun stamps the final status, counts and finish time once a run
// (and all its actions) is recorded.
func (q *Queries) FinishGitlabSyncRun(ctx context.Context, arg FinishGitlabSyncRunParams) error {
	_, err := q.db.Exec(ctx, finishGitlabSyncRun,
		arg.ID,
		arg.Status,
		arg.CreatedCount,
		arg.UpdatedCount,
		arg.DeletedCount,
		arg.ActionCount,
		arg.Error,
	)
	return err
}

const getGitlabSyncAction = `-- name: GetGitlabSyncAction :one
SELECT a.id, a.run_id, a.seq, a.direction, a.entity_type, a.op, a.task_id, a.gl_iid, a.summary, a.detail, a.status, a.error, a.created_at FROM gitlab_sync_actions a
JOIN gitlab_sync_runs r ON r.id = a.run_id
WHERE a.id = $1 AND r.integration_id = $2
`

type GetGitlabSyncActionParams struct {
	ID            uuid.UUID `json:"id"`
	IntegrationID uuid.UUID `json:"integration_id"`
}

func (q *Queries) GetGitlabSyncAction(ctx context.Context, arg GetGitlabSyncActionParams) (GitlabSyncAction, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncAction, arg.ID, arg.IntegrationID)
	var i GitlabSyncAction
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Direction,
		&i.EntityType,
		&i.Op,
		&i.TaskID,
		&i.GlIid,
		&i.Summary,
		&i.Detail,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getGitlabSyncActionInWorkspace = `-- name: GetGitlabSyncActionInWorkspace :one
SELECT a.id, a.run_id, a.seq, a.direction, a.entity_type, a.op, a.task_id, a.gl_iid, a.summary, a.detail, a.status, a.error, a.created_at, r.integration_id AS run_integration_id
FROM gitlab_sync_actions a
JOIN gitlab_sync_runs r ON r.id = a.run_id
JOIN gitlab_integrations i ON i.id = r.integration_id
WHERE a.id = $1 AND i.workspace_id = $2
`

type GetGitlabSyncActionInWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetGitlabSyncActionInWorkspaceRow struct {
	ID               uuid.UUID  `json:"id"`
	RunID            uuid.UUID  `json:"run_id"`
	Seq              int32      `json:"seq"`
	Direction        string     `json:"direction"`
	EntityType       string     `json:"entity_type"`
	Op               string     `json:"op"`
	TaskID           *uuid.UUID `json:"task_id"`
	GlIid            *int64     `json:"gl_iid"`
	Summary          string     `json:"summary"`
	Detail           []byte     `json:"detail"`
	Status           string     `json:"status"`
	Error            string     `json:"error"`
	CreatedAt        time.Time  `json:"created_at"`
	RunIntegrationID uuid.UUID  `json:"run_integration_id"`
}

// GetGitlabSyncActionInWorkspace fetches an action scoped to a workspace (across
// all its bindings), returning its run's integration_id so a retry can re-enqueue.
func (q *Queries) GetGitlabSyncActionInWorkspace(ctx context.Context, arg GetGitlabSyncActionInWorkspaceParams) (GetGitlabSyncActionInWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncActionInWorkspace, arg.ID, arg.WorkspaceID)
	var i GetGitlabSyncActionInWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Direction,
		&i.EntityType,
		&i.Op,
		&i.TaskID,
		&i.GlIid,
		&i.Summary,
		&i.Detail,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.RunIntegrationID,
	)
	return i, err
}

const getGitlabSyncRun = `-- name: GetGitlabSyncRun :one
SELECT id, integration_id, kind, trigger, actor_id, status, created_count, updated_count, deleted_count, action_count, error, started_at, finished_at, mode FROM gitlab_sync_runs WHERE id = $1 AND integration_id = $2
`

type GetGitlabSyncRunParams struct {
	ID            uuid.UUID `json:"id"`
	IntegrationID uuid.UUID `json:"integration_id"`
}

// GetGitlabSyncRun fetches a run scoped to its integration (ownership check).
func (q *Queries) GetGitlabSyncRun(ctx context.Context, arg GetGitlabSyncRunParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncRun, arg.ID, arg.IntegrationID)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Kind,
		&i.Trigger,
		&i.ActorID,
		&i.Status,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.DeletedCount,
		&i.ActionCount,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Mode,
	)
	return i, err
}

const getGitlabSyncRunInWorkspace = `-- name: GetGitlabSyncRunInWorkspace :one
SELECT r.id, r.integration_id, r.kind, r.trigger, r.actor_id, r.status, r.created_count, r.updated_count, r.deleted_count, r.action_count, r.error, r.started_at, r.finished_at, r.mode FROM gitlab_sync_runs r
JOIN gitlab_integrations i ON i.id = r.integration_id
WHERE r.id = $1 AND i.workspace_id = $2
`

type GetGitlabSyncRunInWorkspaceParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// GetGitlabSyncRunInWorkspace fetches a run scoped to a workspace (ownership check
// across all its bindings).
func (q *Queries) GetGitlabSyncRunInWorkspace(ctx context.Context, arg GetGitlabSyncRunInWorkspaceParams) (GitlabSyncRun, error) {
	row := q.db.QueryRow(ctx, getGitlabSyncRunInWorkspace, arg.ID, arg.WorkspaceID)
	var i GitlabSyncRun
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Kind,
		&i.Trigger,
		&i.ActorID,
		&i.Status,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.DeletedCount,
		&i.ActionCount,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Mode,
	)
	return i, err
}

const listGitlabSyncActions = `-- name: ListGitlabSyncActions :many
SELECT id, run_id, seq, direction, entity_type, op, task_id, gl_iid, summary, detail, status, error, created_at FROM gitlab_sync_actions
WHERE run_id = $1
ORDER BY seq
`

func (q *Queries) ListGitlabSyncActions(ctx context.Context, runID uuid.UUID) ([]GitlabSyncAction, error) {
	rows, err := q.db.Query(ctx, listGitlabSyncActions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabSyncAction
	for rows.Next() {
		var i GitlabSyncAction
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Direction,
			&i.EntityType,
			&i.Op,
			&i.TaskID,
			&i.GlIid,
			&i.Summary,
			&i.Detail,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitlabSyncRuns = `-- name: ListGitlabSyncRuns :many
SELECT id, integration_id, kind, trigger, actor_id, status, created_count, updated_count, deleted_count, action_count, error, started_at, finished_at, mode FROM gitlab_sync_runs
WHERE integration_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListGitlabSyncRunsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
}

func (q *Queries) ListGitlabSyncRuns(ctx context.Context, arg ListGitlabSyncRunsParams) ([]GitlabSyncRun, error) {
	rows, err := q.db.Query(ctx, listGitlabSyncRuns, arg.IntegrationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabSyncRun
	for rows.Next() {
		var i GitlabSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Kind,
			&i.Trigger,
			&i.ActorID,
			&i.Status,
			&i.CreatedCount,
			&i.UpdatedCount,
			&i.DeletedCount,
			&i.ActionCount,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitlabSyncRunsByWorkspace = `-- name: ListGitlabSyncRunsByWorkspace :many
SELECT r.id, r.integration_id, r.kind, r.trigger, r.actor_id, r.status, r.created_count, r.updated_count, r.deleted_count, r.action_count, r.error, r.started_at, r.finished_at, r.mode FROM gitlab_sync_runs r
JOIN gitlab_integrations i ON i.id = r.integration_id
WHERE i.workspace_id = $1
ORDER BY r.started_at DESC
LIMIT $2
`

type ListGitlabSyncRunsByWorkspaceParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
}

// ListGitlabSyncRunsByWorkspace aggregates recent runs across every binding in a
// workspace (multi-binding journal), newest first.
func (q *Queries) ListGitlabSyncRunsByWorkspace(ctx context.Context, arg ListGitlabSyncRunsByWorkspaceParams) ([]GitlabSyncRun, error) {
	rows, err := q.db.Query(ctx, listGitlabSyncRunsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitlabSyncRun
	for rows.Next() {
		var i GitlabSyncRun
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Kind,
			&i.Trigger,
			&i.ActorID,
			&i.Status,
			&i.CreatedCount,
			&i.UpdatedCount,
			&i.DeletedCount,
			&i.ActionCount,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentGitlabSyncRuns = `-- name: ListRecentGitlabSyncRuns :many
SELECT r.id, r.integration_id, r.kind, r.trigger, r.actor_id, r.status, r.created_count, r.updated_count, r.deleted_count, r.action_count, r.error, r.started_at, r.finished_at, r.mode, COALESCE(NULLIF(i.name, ''), i.project_path) AS integration_label
FROM gitlab_sync_runs r
JOIN gitlab_integrations i ON i.id = r.integration_id
WHERE r.finished_at IS NOT NULL AND r.started_at >= $1
ORDER BY r.started_at DESC
LIMIT $2
`

type ListRecentGitlabSyncRunsParams struct {
	StartedAt time.Time `json:"started_at"`
	Limit     int32     `json:"limit"`
}

type ListRecentGitlabSyncRunsRow struct {
	ID               uuid.UUID  `json:"id"`
	IntegrationID    uuid.UUID  `json:"integration_id"`
	Kind             string     `json:"kind"`
	Trigger          string     `json:"trigger"`
	ActorID          *uuid.UUID `json:"actor_id"`
	Status           string     `json:"status"`
	CreatedCount     int32      `json:"created_count"`
	UpdatedCount     int32      `json:"updated_count"`
	DeletedCount     int32      `json:"deleted_count"`
	ActionCount      int32      `json:"action_count"`
	Error            string     `json:"error"`
	StartedAt        time.Time  `json:"started_at"`
	FinishedAt       *time.Time `json:"finished_at"`
	Mode             string     `json:"mode"`
	IntegrationLabel string     `json:"integration_label"`
}

// ListRecentGitlabSyncRuns returns finished sync runs across every integration
// started within the retention window, with the integration name — the durable
// backing for the background-jobs panel's journal (survives a restart, unlike the
// in-memory registry). Instance-wide (admin panel), newest first.
func (q *Queries) ListRecentGitlabSyncRuns(ctx context.Context, arg ListRecentGitlabSyncRunsParams) ([]ListRecentGitlabSyncRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecentGitlabSyncRuns, arg.StartedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentGitlabSyncRunsRow
	for rows.Next() {
		var i ListRecentGitlabSyncRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Kind,
			&i.Trigger,
			&i.ActorID,
			&i.Status,
			&i.CreatedCount,
			&i.UpdatedCount,
			&i.DeletedCount,
			&i.ActionCount,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Mode,
			&i.IntegrationLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneGitlabSyncRuns = `-- name: PruneGitlabSyncRuns :exec
DELETE FROM gitlab_sync_runs r
WHERE r.integration_id = $1
  AND r.id NOT IN (
    SELECT s.id FROM gitlab_sync_runs s
    WHERE s.integration_id = $1
    ORDER BY s.started_at DESC
    LIMIT $2
  )
`

type PruneGitlabSyncRunsParams struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	Limit         int32     `json:"limit"`
}

// PruneGitlabSyncRuns keeps only the most recent $2 runs of an integration; older
// runs (and their actions, via ON DELETE CASCADE) are dropped so the journal stays
// bounded.
func (q *Queries) PruneGitlabSyncRuns(ctx context.Context, arg PruneGitlabSyncRunsParams) error {
	_, err := q.db.Exec(ctx, pruneGitlabSyncRuns, arg.IntegrationID, arg.Limit)
	return err
}
