// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: milestones.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (project_id, title, description, start_date, due_date, state, slug, position)
VALUES (
    $1, $2, $3, $4, $5, COALESCE($7, 'active'), $6,
    (SELECT COALESCE(MAX(position), 0) + 1 FROM milestones WHERE project_id = $1)
)
RETURNING id, project_id, title, description, start_date, due_date, state, position, created_at, updated_at, slug
`

type CreateMilestoneParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	StartDate   *time.Time  `json:"start_date"`
	DueDate     *time.Time  `json:"due_date"`
	Slug        string      `json:"slug"`
	State       interface{} `json:"state"`
}

// CreateMilestone appends a milestone (position = max+1 within the project).
func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.DueDate,
		arg.Slug,
		arg.State,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.State,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones WHERE id = $1
`

func (q *Queries) DeleteMilestone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMilestone, id)
	return err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, project_id, title, description, start_date, due_date, state, position, created_at, updated_at, slug FROM milestones WHERE id = $1
`

func (q *Queries) GetMilestone(ctx context.Context, id uuid.UUID) (Milestone, error) {
	row := q.db.QueryRow(ctx, getMilestone, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.State,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const getMilestoneInProjectBySlug = `-- name: GetMilestoneInProjectBySlug :one
SELECT id, project_id, title, description, start_date, due_date, state, position, created_at, updated_at, slug FROM milestones WHERE project_id = $1 AND slug = $2
`

type GetMilestoneInProjectBySlugParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

// GetMilestoneInProjectBySlug resolves a ?milestone=<slug> board scope.
func (q *Queries) GetMilestoneInProjectBySlug(ctx context.Context, arg GetMilestoneInProjectBySlugParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, getMilestoneInProjectBySlug, arg.ProjectID, arg.Slug)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.State,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}

const listMilestones = `-- name: ListMilestones :many

SELECT m.id, m.project_id, m.title, m.description, m.start_date, m.due_date, m.state, m.position, m.created_at, m.updated_at, m.slug, l.gl_web_url AS gl_url, l.gl_global_id AS gl_global_id
FROM milestones m
LEFT JOIN gitlab_milestone_links l ON l.milestone_id = m.id
WHERE m.project_id = $1
ORDER BY m.position, m.created_at
`

type ListMilestonesRow struct {
	ID          uuid.UUID  `json:"id"`
	ProjectID   uuid.UUID  `json:"project_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	StartDate   *time.Time `json:"start_date"`
	DueDate     *time.Time `json:"due_date"`
	State       string     `json:"state"`
	Position    float64    `json:"position"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	Slug        string     `json:"slug"`
	GlUrl       *string    `json:"gl_url"`
	GlGlobalID  *string    `json:"gl_global_id"`
}

// Milestones («Этап») — project-scoped planning unit. CRUD + task assignment.
// GitLab-sourced milestones get a row in gitlab_milestone_links (added later); the
// presence of that link makes a milestone read-only in Tessera.
// ListMilestones returns a project's milestones with their GitLab link info (null
// columns when native), so the UI can tell native from GitLab-sourced.
func (q *Queries) ListMilestones(ctx context.Context, projectID uuid.UUID) ([]ListMilestonesRow, error) {
	rows, err := q.db.Query(ctx, listMilestones, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMilestonesRow
	for rows.Next() {
		var i ListMilestonesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.DueDate,
			&i.State,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.GlUrl,
			&i.GlGlobalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMilestones = `-- name: ListWorkspaceMilestones :many
SELECT m.id, m.project_id, m.title, m.description, m.start_date, m.due_date,
       m.state, m.position, m.slug, m.created_at, m.updated_at,
       l.gl_web_url AS gl_url, l.gl_global_id AS gl_global_id,
       p.name AS project_name, p.slug AS project_slug,
       COALESCE((SELECT b.slug FROM boards b WHERE b.project_id = p.id
        ORDER BY b.position, b.created_at LIMIT 1), '') AS board_slug,
       COUNT(t.id) AS task_count,
       COUNT(t.id) FILTER (WHERE t.completed_at IS NOT NULL) AS done_count,
       COALESCE(SUM(t.estimate), 0)::float8 AS estimate_sum
FROM milestones m
JOIN projects p ON p.id = m.project_id
LEFT JOIN gitlab_milestone_links l ON l.milestone_id = m.id
LEFT JOIN tasks t ON t.milestone_id = m.id AND t.archived_at IS NULL
WHERE p.workspace_id = $1
GROUP BY m.id, l.gl_web_url, l.gl_global_id, p.name, p.slug, p.id
ORDER BY p.name, m.position, m.created_at
`

type ListWorkspaceMilestonesRow struct {
	ID          uuid.UUID   `json:"id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	StartDate   *time.Time  `json:"start_date"`
	DueDate     *time.Time  `json:"due_date"`
	State       string      `json:"state"`
	Position    float64     `json:"position"`
	Slug        string      `json:"slug"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	GlUrl       *string     `json:"gl_url"`
	GlGlobalID  *string     `json:"gl_global_id"`
	ProjectName string      `json:"project_name"`
	ProjectSlug string      `json:"project_slug"`
	BoardSlug   interface{} `json:"board_slug"`
	TaskCount   int64       `json:"task_count"`
	DoneCount   int64       `json:"done_count"`
	EstimateSum float64     `json:"estimate_sum"`
}

// ListWorkspaceMilestones returns every milestone across a workspace's projects with
// per-milestone task rollups (total / done / Σ estimate, archived excluded) plus the
// owning project's name + slug and a board slug to deep-link to. Powers the dedicated
// «Этапы» roadmap screen (one query, no per-project fan-out).
func (q *Queries) ListWorkspaceMilestones(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMilestonesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMilestones, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMilestonesRow
	for rows.Next() {
		var i ListWorkspaceMilestonesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.DueDate,
			&i.State,
			&i.Position,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GlUrl,
			&i.GlGlobalID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.BoardSlug,
			&i.TaskCount,
			&i.DoneCount,
			&i.EstimateSum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const milestoneSlugExistsInProject = `-- name: MilestoneSlugExistsInProject :one
SELECT EXISTS(SELECT 1 FROM milestones WHERE project_id = $1 AND slug = $2)
`

type MilestoneSlugExistsInProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) MilestoneSlugExistsInProject(ctx context.Context, arg MilestoneSlugExistsInProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, milestoneSlugExistsInProject, arg.ProjectID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const milestonesMissingSlug = `-- name: MilestonesMissingSlug :many
SELECT id, project_id, title FROM milestones WHERE slug = ''
`

type MilestonesMissingSlugRow struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
}

func (q *Queries) MilestonesMissingSlug(ctx context.Context) ([]MilestonesMissingSlugRow, error) {
	rows, err := q.db.Query(ctx, milestonesMissingSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MilestonesMissingSlugRow
	for rows.Next() {
		var i MilestonesMissingSlugRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMilestoneSlug = `-- name: SetMilestoneSlug :exec
UPDATE milestones SET slug = $2 WHERE id = $1
`

type SetMilestoneSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) SetMilestoneSlug(ctx context.Context, arg SetMilestoneSlugParams) error {
	_, err := q.db.Exec(ctx, setMilestoneSlug, arg.ID, arg.Slug)
	return err
}

const setTaskMilestone = `-- name: SetTaskMilestone :exec
UPDATE tasks SET milestone_id = $2, updated_at = now() WHERE id = $1
`

type SetTaskMilestoneParams struct {
	ID          uuid.UUID  `json:"id"`
	MilestoneID *uuid.UUID `json:"milestone_id"`
}

func (q *Queries) SetTaskMilestone(ctx context.Context, arg SetTaskMilestoneParams) error {
	_, err := q.db.Exec(ctx, setTaskMilestone, arg.ID, arg.MilestoneID)
	return err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET title = $2, description = $3, start_date = $4, due_date = $5, state = $6, updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, start_date, due_date, state, position, created_at, updated_at, slug
`

type UpdateMilestoneParams struct {
	ID          uuid.UUID  `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	StartDate   *time.Time `json:"start_date"`
	DueDate     *time.Time `json:"due_date"`
	State       string     `json:"state"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.DueDate,
		arg.State,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.DueDate,
		&i.State,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
	)
	return i, err
}
