// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID           uuid.UUID  `json:"id"`
	ProjectID    uuid.UUID  `json:"project_id"`
	Name         string     `json:"name"`
	Position     float64    `json:"position"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DoneColumnID *uuid.UUID `json:"done_column_id"`
	Slug         string     `json:"slug"`
	Icon         string     `json:"icon"`
	Color        string     `json:"color"`
	IconMode     string     `json:"icon_mode"`
}

type BoardColumn struct {
	ID        uuid.UUID `json:"id"`
	BoardID   uuid.UUID `json:"board_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	Position  float64   `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type BoardView struct {
	ID        uuid.UUID `json:"id"`
	BoardID   uuid.UUID `json:"board_id"`
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Config    []byte    `json:"config"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DueNotificationState struct {
	TaskID      uuid.UUID `json:"task_id"`
	UserID      uuid.UUID `json:"user_id"`
	FiredDue    time.Time `json:"fired_due"`
	LastFiredAt time.Time `json:"last_fired_at"`
}

type GitlabCredential struct {
	UserID     uuid.UUID `json:"user_id"`
	BaseUrl    string    `json:"base_url"`
	TokenEnc   string    `json:"token_enc"`
	GlUserID   int64     `json:"gl_user_id"`
	GlUsername string    `json:"gl_username"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type GitlabIntegration struct {
	ID                  uuid.UUID  `json:"id"`
	WorkspaceID         uuid.UUID  `json:"workspace_id"`
	ProjectPath         string     `json:"project_path"`
	BoardID             uuid.UUID  `json:"board_id"`
	LabelRules          []byte     `json:"label_rules"`
	Enabled             bool       `json:"enabled"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	OwnerUserID         *uuid.UUID `json:"owner_user_id"`
	SyncIntervalSec     int32      `json:"sync_interval_sec"`
	LastSyncedAt        *time.Time `json:"last_synced_at"`
	DueSource           string     `json:"due_source"`
	StartSource         string     `json:"start_source"`
	Writeback           []byte     `json:"writeback"`
	Name                string     `json:"name"`
	Scope               string     `json:"scope"`
	ClosedPolicy        string     `json:"closed_policy"`
	ClosedAfter         *time.Time `json:"closed_after"`
	LastFullSyncedAt    *time.Time `json:"last_full_synced_at"`
	MembersSyncedAt     *time.Time `json:"members_synced_at"`
	FullSyncIntervalSec int32      `json:"full_sync_interval_sec"`
	RelationsSync       string     `json:"relations_sync"`
}

type GitlabIssueLink struct {
	ID                 uuid.UUID  `json:"id"`
	IntegrationID      uuid.UUID  `json:"integration_id"`
	SrcProjectPath     string     `json:"src_project_path"`
	SrcIid             int64      `json:"src_iid"`
	DstProjectPath     string     `json:"dst_project_path"`
	DstIid             int64      `json:"dst_iid"`
	LinkType           string     `json:"link_type"`
	GlLinkID           string     `json:"gl_link_id"`
	GlWebUrl           string     `json:"gl_web_url"`
	ResolvedRelationID *uuid.UUID `json:"resolved_relation_id"`
	LastSeenAt         time.Time  `json:"last_seen_at"`
	CreatedAt          time.Time  `json:"created_at"`
}

type GitlabLink struct {
	TaskID              uuid.UUID  `json:"task_id"`
	IntegrationID       uuid.UUID  `json:"integration_id"`
	GlGlobalID          string     `json:"gl_global_id"`
	GlIid               int64      `json:"gl_iid"`
	GlProjectPath       string     `json:"gl_project_path"`
	GlWebUrl            string     `json:"gl_web_url"`
	GlUpdatedAt         *time.Time `json:"gl_updated_at"`
	TitleHash           string     `json:"title_hash"`
	DescHash            string     `json:"desc_hash"`
	LabelsHash          string     `json:"labels_hash"`
	LastSyncedAt        time.Time  `json:"last_synced_at"`
	CreatedAt           time.Time  `json:"created_at"`
	GlAuthor            string     `json:"gl_author"`
	GlAuthorName        string     `json:"gl_author_name"`
	DueOverridden       bool       `json:"due_overridden"`
	GlAuthorAvatarUrl   string     `json:"gl_author_avatar_url"`
	StartOverridden     bool       `json:"start_overridden"`
	GlLastState         string     `json:"gl_last_state"`
	EstimateOverridden  bool       `json:"estimate_overridden"`
	GlSnapshot          []byte     `json:"gl_snapshot"`
	MilestoneOverridden bool       `json:"milestone_overridden"`
}

type GitlabMilestoneLink struct {
	MilestoneID   uuid.UUID `json:"milestone_id"`
	IntegrationID uuid.UUID `json:"integration_id"`
	GlGlobalID    string    `json:"gl_global_id"`
	GlIid         *int64    `json:"gl_iid"`
	GlNumericID   int64     `json:"gl_numeric_id"`
	GlWebUrl      string    `json:"gl_web_url"`
	GlState       string    `json:"gl_state"`
	TitleHash     string    `json:"title_hash"`
	LastSyncedAt  time.Time `json:"last_synced_at"`
}

type GitlabProjectMember struct {
	IntegrationID uuid.UUID `json:"integration_id"`
	GlUserID      int64     `json:"gl_user_id"`
	GlUsername    string    `json:"gl_username"`
	GlName        string    `json:"gl_name"`
	GlAvatarUrl   string    `json:"gl_avatar_url"`
	AccessLevel   int32     `json:"access_level"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type GitlabSyncAction struct {
	ID         uuid.UUID  `json:"id"`
	RunID      uuid.UUID  `json:"run_id"`
	Seq        int32      `json:"seq"`
	Direction  string     `json:"direction"`
	EntityType string     `json:"entity_type"`
	Op         string     `json:"op"`
	TaskID     *uuid.UUID `json:"task_id"`
	GlIid      *int64     `json:"gl_iid"`
	Summary    string     `json:"summary"`
	Detail     []byte     `json:"detail"`
	Status     string     `json:"status"`
	Error      string     `json:"error"`
	CreatedAt  time.Time  `json:"created_at"`
}

type GitlabSyncRun struct {
	ID            uuid.UUID  `json:"id"`
	IntegrationID uuid.UUID  `json:"integration_id"`
	Kind          string     `json:"kind"`
	Trigger       string     `json:"trigger"`
	ActorID       *uuid.UUID `json:"actor_id"`
	Status        string     `json:"status"`
	CreatedCount  int32      `json:"created_count"`
	UpdatedCount  int32      `json:"updated_count"`
	DeletedCount  int32      `json:"deleted_count"`
	ActionCount   int32      `json:"action_count"`
	Error         string     `json:"error"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	Mode          string     `json:"mode"`
}

type GitlabWriteback struct {
	ID            uuid.UUID  `json:"id"`
	TaskID        uuid.UUID  `json:"task_id"`
	IntegrationID uuid.UUID  `json:"integration_id"`
	ChangeKind    string     `json:"change_kind"`
	Payload       []byte     `json:"payload"`
	Status        string     `json:"status"`
	Attempts      int32      `json:"attempts"`
	LastError     string     `json:"last_error"`
	NextAttemptAt time.Time  `json:"next_attempt_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	Conflict      []byte     `json:"conflict"`
	Resolution    string     `json:"resolution"`
	ResolvedBy    *uuid.UUID `json:"resolved_by"`
	ResolvedAt    *time.Time `json:"resolved_at"`
}

type Membership struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
}

type Milestone struct {
	ID          uuid.UUID  `json:"id"`
	ProjectID   uuid.UUID  `json:"project_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	StartDate   *time.Time `json:"start_date"`
	DueDate     *time.Time `json:"due_date"`
	State       string     `json:"state"`
	Position    float64    `json:"position"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	Slug        string     `json:"slug"`
}

type Note struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	ProjectID   *uuid.UUID `json:"project_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Title       string     `json:"title"`
	Body        string     `json:"body"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	Slug        string     `json:"slug"`
}

type Notification struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	TaskID      *uuid.UUID `json:"task_id"`
	ActorID     *uuid.UUID `json:"actor_id"`
	Kind        string     `json:"kind"`
	Text        string     `json:"text"`
	ReadAt      *time.Time `json:"read_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type NotificationChannel struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	Label     string    `json:"label"`
	Config    []byte    `json:"config"`
	SecretEnc string    `json:"secret_enc"`
	Enabled   bool      `json:"enabled"`
	Verified  bool      `json:"verified"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Template  string    `json:"template"`
}

type NotificationDelivery struct {
	ID             uuid.UUID `json:"id"`
	NotificationID uuid.UUID `json:"notification_id"`
	ChannelID      uuid.UUID `json:"channel_id"`
	Status         string    `json:"status"`
	Attempts       int32     `json:"attempts"`
	LastError      string    `json:"last_error"`
	NextAttemptAt  time.Time `json:"next_attempt_at"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	DigestGroup    string    `json:"digest_group"`
}

type NotificationPref struct {
	UserID            uuid.UUID `json:"user_id"`
	DueEnabled        bool      `json:"due_enabled"`
	DueLeadMinutes    int32     `json:"due_lead_minutes"`
	DueRepeatMinutes  int32     `json:"due_repeat_minutes"`
	ReminderEnabled   bool      `json:"reminder_enabled"`
	UpdatedAt         time.Time `json:"updated_at"`
	QuietEnabled      bool      `json:"quiet_enabled"`
	QuietStartMinutes int32     `json:"quiet_start_minutes"`
	QuietEndMinutes   int32     `json:"quiet_end_minutes"`
	QuietTz           string    `json:"quiet_tz"`
	DigestMinutes     int32     `json:"digest_minutes"`
}

type NotificationRoute struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	Position   float64     `json:"position"`
	Matcher    []byte      `json:"matcher"`
	ChannelIds []uuid.UUID `json:"channel_ids"`
	Options    []byte      `json:"options"`
	Enabled    bool        `json:"enabled"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type OauthIdentity struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	Provider         string    `json:"provider"`
	ProviderUserID   string    `json:"provider_user_id"`
	ProviderUsername string    `json:"provider_username"`
	ProviderEmail    string    `json:"provider_email"`
	GlBaseUrl        string    `json:"gl_base_url"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type OauthProvider struct {
	Provider        string    `json:"provider"`
	ClientID        string    `json:"client_id"`
	ClientSecretEnc string    `json:"client_secret_enc"`
	GlBaseUrl       string    `json:"gl_base_url"`
	Enabled         bool      `json:"enabled"`
	OrgMap          []byte    `json:"org_map"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ServiceTokenEnc string    `json:"service_token_enc"`
}

type PersonalAccessToken struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	Name       string     `json:"name"`
	TokenHash  string     `json:"token_hash"`
	LastFour   string     `json:"last_four"`
	ExpiresAt  *time.Time `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID        `json:"id"`
	WorkspaceID uuid.UUID        `json:"workspace_id"`
	GroupID     *uuid.UUID       `json:"group_id"`
	Name        string           `json:"name"`
	Color       string           `json:"color"`
	Position    float64          `json:"position"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
	Icon        string           `json:"icon"`
	Slug        string           `json:"slug"`
	Estimation  *json.RawMessage `json:"estimation"`
	IconMode    string           `json:"icon_mode"`
	TreeMode    string           `json:"tree_mode"`
}

type ProjectGroup struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Name        string     `json:"name"`
	Position    float64    `json:"position"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Icon        string     `json:"icon"`
	Color       string     `json:"color"`
	IconMode    string     `json:"icon_mode"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Reminder struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	TaskID     *uuid.UUID `json:"task_id"`
	RemindAt   time.Time  `json:"remind_at"`
	Message    string     `json:"message"`
	Done       bool       `json:"done"`
	CreatedAt  time.Time  `json:"created_at"`
	NotifiedAt *time.Time `json:"notified_at"`
}

type Tag struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	ProjectID   uuid.UUID `json:"project_id"`
}

type TagPrefix struct {
	ProjectID   uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Prefix      string    `json:"prefix"`
	Label       string    `json:"label"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Task struct {
	ID                 uuid.UUID        `json:"id"`
	BoardID            uuid.UUID        `json:"board_id"`
	ColumnID           uuid.UUID        `json:"column_id"`
	ParentID           *uuid.UUID       `json:"parent_id"`
	Title              string           `json:"title"`
	Description        string           `json:"description"`
	Priority           int32            `json:"priority"`
	DueDate            *time.Time       `json:"due_date"`
	Position           float64          `json:"position"`
	CreatedBy          *uuid.UUID       `json:"created_by"`
	CompletedAt        *time.Time       `json:"completed_at"`
	CreatedAt          time.Time        `json:"created_at"`
	UpdatedAt          time.Time        `json:"updated_at"`
	ArchivedAt         *time.Time       `json:"archived_at"`
	Number             *int64           `json:"number"`
	DueLeadMinutes     *int32           `json:"due_lead_minutes"`
	DueRepeatMinutes   *int32           `json:"due_repeat_minutes"`
	DueNotifyEnabled   *bool            `json:"due_notify_enabled"`
	Recurrence         *json.RawMessage `json:"recurrence"`
	EisenhowerQuadrant *int16           `json:"eisenhower_quadrant"`
	StartDate          *time.Time       `json:"start_date"`
	Estimate           *float64         `json:"estimate"`
	MilestoneID        *uuid.UUID       `json:"milestone_id"`
}

type TaskAssignee struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

type TaskAttachment struct {
	ID          uuid.UUID  `json:"id"`
	TaskID      uuid.UUID  `json:"task_id"`
	UploaderID  *uuid.UUID `json:"uploader_id"`
	Filename    string     `json:"filename"`
	ContentType string     `json:"content_type"`
	Size        int64      `json:"size"`
	StoragePath string     `json:"storage_path"`
	CreatedAt   time.Time  `json:"created_at"`
}

type TaskComment struct {
	ID                uuid.UUID  `json:"id"`
	TaskID            uuid.UUID  `json:"task_id"`
	AuthorID          *uuid.UUID `json:"author_id"`
	Body              string     `json:"body"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	GlNoteID          *string    `json:"gl_note_id"`
	GlAuthorLogin     string     `json:"gl_author_login"`
	GlAuthorName      string     `json:"gl_author_name"`
	GlAuthorAvatarUrl string     `json:"gl_author_avatar_url"`
}

type TaskEvent struct {
	ID        uuid.UUID  `json:"id"`
	TaskID    uuid.UUID  `json:"task_id"`
	ActorID   *uuid.UUID `json:"actor_id"`
	Kind      string     `json:"kind"`
	Data      []byte     `json:"data"`
	CreatedAt time.Time  `json:"created_at"`
}

type TaskGitlabAssignee struct {
	TaskID      uuid.UUID `json:"task_id"`
	GlUsername  string    `json:"gl_username"`
	GlName      string    `json:"gl_name"`
	GlAvatarUrl string    `json:"gl_avatar_url"`
	Source      string    `json:"source"`
}

type TaskRelation struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	RelatedTaskID uuid.UUID `json:"related_task_id"`
	Kind          string    `json:"kind"`
	CreatedAt     time.Time `json:"created_at"`
	Source        string    `json:"source"`
}

type TaskTag struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
	Source string    `json:"source"`
}

type User struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	Name          string    `json:"name"`
	PasswordHash  string    `json:"password_hash"`
	IsAdmin       bool      `json:"is_admin"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	Provider      string    `json:"provider"`
	Active        bool      `json:"active"`
	EmailVerified bool      `json:"email_verified"`
	LastName      string    `json:"last_name"`
	FirstName     string    `json:"first_name"`
	MiddleName    string    `json:"middle_name"`
	Bio           string    `json:"bio"`
	Company       string    `json:"company"`
	JobTitle      string    `json:"job_title"`
}

type UserAvatar struct {
	UserID      uuid.UUID `json:"user_id"`
	ContentType string    `json:"content_type"`
	Bytes       []byte    `json:"bytes"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UserPreference struct {
	UserID          uuid.UUID `json:"user_id"`
	Language        string    `json:"language"`
	Timezone        string    `json:"timezone"`
	Country         string    `json:"country"`
	TimeFormat      string    `json:"time_format"`
	DateFormat      string    `json:"date_format"`
	WeekStart       int16     `json:"week_start"`
	Theme           string    `json:"theme"`
	Accent          string    `json:"accent"`
	BoardBackground string    `json:"board_background"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type UserToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Kind      string     `json:"kind"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Workspace struct {
	ID          uuid.UUID        `json:"id"`
	Name        string           `json:"name"`
	OwnerID     uuid.UUID        `json:"owner_id"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
	TaskCounter int64            `json:"task_counter"`
	Estimation  *json.RawMessage `json:"estimation"`
}

type WorkspaceInvitation struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Email       string     `json:"email"`
	Role        string     `json:"role"`
	TokenHash   string     `json:"token_hash"`
	InvitedBy   *uuid.UUID `json:"invited_by"`
	ExpiresAt   time.Time  `json:"expires_at"`
	AcceptedAt  *time.Time `json:"accepted_at"`
	CreatedAt   time.Time  `json:"created_at"`
}
