// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_channels.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimPendingDeliveries = `-- name: ClaimPendingDeliveries :many
UPDATE notification_deliveries
SET status = 'sending', attempts = attempts + 1, updated_at = now()
WHERE id IN (
    SELECT id FROM notification_deliveries
    WHERE status = 'pending' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, notification_id, channel_id, status, attempts, last_error, next_attempt_at, created_at, updated_at
`

// ClaimPendingDeliveries atomically grabs up to $1 due pending rows, marking them
// 'sending' and bumping the attempt counter, so concurrent/queued workers never
// pick the same row (FOR UPDATE SKIP LOCKED).
func (q *Queries) ClaimPendingDeliveries(ctx context.Context, limit int32) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, claimPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDelivery
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.ChannelID,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one


INSERT INTO notification_channels (user_id, type, label, config, secret_enc, enabled, template)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, type, label, config, secret_enc, enabled, verified, created_at, updated_at, template
`

type CreateNotificationChannelParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	Label     string    `json:"label"`
	Config    []byte    `json:"config"`
	SecretEnc string    `json:"secret_enc"`
	Enabled   bool      `json:"enabled"`
	Template  string    `json:"template"`
}

// Notification channels, routing rules and the delivery outbox (Phase A).
// ── Channels (per-user) ────────────────────────────────────
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.UserID,
		arg.Type,
		arg.Label,
		arg.Config,
		arg.SecretEnc,
		arg.Enabled,
		arg.Template,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.SecretEnc,
		&i.Enabled,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Template,
	)
	return i, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :exec

INSERT INTO notification_deliveries (notification_id, channel_id)
VALUES ($1, $2)
`

type CreateNotificationDeliveryParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	ChannelID      uuid.UUID `json:"channel_id"`
}

// ── Delivery outbox ────────────────────────────────────────
func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, createNotificationDelivery, arg.NotificationID, arg.ChannelID)
	return err
}

const createNotificationRoute = `-- name: CreateNotificationRoute :one

INSERT INTO notification_routes (user_id, position, matcher, channel_ids, options, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, position, matcher, channel_ids, options, enabled, created_at, updated_at
`

type CreateNotificationRouteParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Position   float64     `json:"position"`
	Matcher    []byte      `json:"matcher"`
	ChannelIds []uuid.UUID `json:"channel_ids"`
	Options    []byte      `json:"options"`
	Enabled    bool        `json:"enabled"`
}

// ── Routes (per-user) ──────────────────────────────────────
func (q *Queries) CreateNotificationRoute(ctx context.Context, arg CreateNotificationRouteParams) (NotificationRoute, error) {
	row := q.db.QueryRow(ctx, createNotificationRoute,
		arg.UserID,
		arg.Position,
		arg.Matcher,
		arg.ChannelIds,
		arg.Options,
		arg.Enabled,
	)
	var i NotificationRoute
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.Matcher,
		&i.ChannelIds,
		&i.Options,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = $1 AND user_id = $2
`

type DeleteNotificationChannelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.UserID)
	return err
}

const deleteNotificationRoute = `-- name: DeleteNotificationRoute :exec
DELETE FROM notification_routes WHERE id = $1 AND user_id = $2
`

type DeleteNotificationRouteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteNotificationRoute(ctx context.Context, arg DeleteNotificationRouteParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationRoute, arg.ID, arg.UserID)
	return err
}

const getNotification = `-- name: GetNotification :one

SELECT id, user_id, workspace_id, task_id, actor_id, kind, text, read_at, created_at FROM notifications WHERE id = $1
`

// ── Notification fetch (for delivery) ──────────────────────
func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.TaskID,
		&i.ActorID,
		&i.Kind,
		&i.Text,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, user_id, type, label, config, secret_enc, enabled, verified, created_at, updated_at, template FROM notification_channels WHERE id = $1 AND user_id = $2
`

type GetNotificationChannelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.UserID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.SecretEnc,
		&i.Enabled,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Template,
	)
	return i, err
}

const getNotificationChannelByID = `-- name: GetNotificationChannelByID :one
SELECT id, user_id, type, label, config, secret_enc, enabled, verified, created_at, updated_at, template FROM notification_channels WHERE id = $1
`

// GetNotificationChannelByID fetches a channel without the owner check — used by
// the delivery worker, which operates off the request path.
func (q *Queries) GetNotificationChannelByID(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.SecretEnc,
		&i.Enabled,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Template,
	)
	return i, err
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, user_id, type, label, config, secret_enc, enabled, verified, created_at, updated_at, template FROM notification_channels WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListNotificationChannels(ctx context.Context, userID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Label,
			&i.Config,
			&i.SecretEnc,
			&i.Enabled,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Template,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationRoutes = `-- name: ListNotificationRoutes :many
SELECT id, user_id, position, matcher, channel_ids, options, enabled, created_at, updated_at FROM notification_routes WHERE user_id = $1 ORDER BY position, created_at
`

// ListNotificationRoutes returns every route for a user, ordered (the UI shows
// all of them; the dispatcher filters to enabled ones in code).
func (q *Queries) ListNotificationRoutes(ctx context.Context, userID uuid.UUID) ([]NotificationRoute, error) {
	rows, err := q.db.Query(ctx, listNotificationRoutes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationRoute
	for rows.Next() {
		var i NotificationRoute
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Position,
			&i.Matcher,
			&i.ChannelIds,
			&i.Options,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE notification_deliveries SET status = 'failed', last_error = $2, updated_at = now() WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.LastError)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE notification_deliveries
SET status = 'pending', last_error = $2, next_attempt_at = $3, updated_at = now()
WHERE id = $1
`

type MarkDeliveryRetryParams struct {
	ID            uuid.UUID `json:"id"`
	LastError     string    `json:"last_error"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

// MarkDeliveryRetry reschedules a transient failure (back to pending, with a
// backed-off next_attempt_at).
func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, markDeliveryRetry, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE notification_deliveries SET status = 'sent', last_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkDeliverySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDeliverySent, id)
	return err
}

const setNotificationChannelVerified = `-- name: SetNotificationChannelVerified :exec
UPDATE notification_channels SET verified = $3, updated_at = now() WHERE id = $1 AND user_id = $2
`

type SetNotificationChannelVerifiedParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Verified bool      `json:"verified"`
}

func (q *Queries) SetNotificationChannelVerified(ctx context.Context, arg SetNotificationChannelVerifiedParams) error {
	_, err := q.db.Exec(ctx, setNotificationChannelVerified, arg.ID, arg.UserID, arg.Verified)
	return err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET label = $3, config = $4, secret_enc = $5, enabled = $6, template = $7, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, label, config, secret_enc, enabled, verified, created_at, updated_at, template
`

type UpdateNotificationChannelParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Label     string    `json:"label"`
	Config    []byte    `json:"config"`
	SecretEnc string    `json:"secret_enc"`
	Enabled   bool      `json:"enabled"`
	Template  string    `json:"template"`
}

// UpdateNotificationChannel updates a channel in place. secret_enc is replaced
// only when a new secret was supplied (the handler passes the existing value
// otherwise, so an edit that doesn't touch the secret keeps it).
func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.Config,
		arg.SecretEnc,
		arg.Enabled,
		arg.Template,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.SecretEnc,
		&i.Enabled,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Template,
	)
	return i, err
}

const updateNotificationRoute = `-- name: UpdateNotificationRoute :one
UPDATE notification_routes
SET position = $3, matcher = $4, channel_ids = $5, options = $6, enabled = $7, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, position, matcher, channel_ids, options, enabled, created_at, updated_at
`

type UpdateNotificationRouteParams struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	Position   float64     `json:"position"`
	Matcher    []byte      `json:"matcher"`
	ChannelIds []uuid.UUID `json:"channel_ids"`
	Options    []byte      `json:"options"`
	Enabled    bool        `json:"enabled"`
}

func (q *Queries) UpdateNotificationRoute(ctx context.Context, arg UpdateNotificationRouteParams) (NotificationRoute, error) {
	row := q.db.QueryRow(ctx, updateNotificationRoute,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.Matcher,
		arg.ChannelIds,
		arg.Options,
		arg.Enabled,
	)
	var i NotificationRoute
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Position,
		&i.Matcher,
		&i.ChannelIds,
		&i.Options,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
