// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_prefs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDueNotificationState = `-- name: GetDueNotificationState :one
SELECT task_id, user_id, fired_due, last_fired_at FROM due_notification_state WHERE task_id = $1 AND user_id = $2
`

type GetDueNotificationStateParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDueNotificationState(ctx context.Context, arg GetDueNotificationStateParams) (DueNotificationState, error) {
	row := q.db.QueryRow(ctx, getDueNotificationState, arg.TaskID, arg.UserID)
	var i DueNotificationState
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.FiredDue,
		&i.LastFiredAt,
	)
	return i, err
}

const getNotificationPrefs = `-- name: GetNotificationPrefs :one

SELECT user_id, due_enabled, due_lead_minutes, due_repeat_minutes, reminder_enabled, updated_at, quiet_enabled, quiet_start_minutes, quiet_end_minutes, quiet_tz, digest_minutes FROM notification_prefs WHERE user_id = $1
`

// Per-user scheduling prefs + the due/reminder scanner's queries (Phase B).
func (q *Queries) GetNotificationPrefs(ctx context.Context, userID uuid.UUID) (NotificationPref, error) {
	row := q.db.QueryRow(ctx, getNotificationPrefs, userID)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.DueEnabled,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.ReminderEnabled,
		&i.UpdatedAt,
		&i.QuietEnabled,
		&i.QuietStartMinutes,
		&i.QuietEndMinutes,
		&i.QuietTz,
		&i.DigestMinutes,
	)
	return i, err
}

const listDueReminders = `-- name: ListDueReminders :many
SELECT id, user_id, task_id, remind_at, message, done, created_at, notified_at FROM reminders WHERE NOT done AND notified_at IS NULL AND remind_at <= now()
`

func (q *Queries) ListDueReminders(ctx context.Context) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listDueReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.RemindAt,
			&i.Message,
			&i.Done,
			&i.CreatedAt,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueTasksForScan = `-- name: ListDueTasksForScan :many
SELECT id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate FROM tasks
WHERE due_date IS NOT NULL
  AND completed_at IS NULL
  AND archived_at IS NULL
  AND due_date <= now() + interval '31 days'
  AND due_date >= now() - interval '7 days'
`

// ListDueTasksForScan returns incomplete, non-archived tasks with a due date in a
// bounded window around now (covers leads up to ~31 days and caps overdue nagging
// at 7 days), so the scanner doesn't walk the whole table.
func (q *Queries) ListDueTasksForScan(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listDueTasksForScan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderNotified = `-- name: MarkReminderNotified :exec
UPDATE reminders SET notified_at = now() WHERE id = $1
`

func (q *Queries) MarkReminderNotified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReminderNotified, id)
	return err
}

const upsertDueNotificationState = `-- name: UpsertDueNotificationState :exec
INSERT INTO due_notification_state (task_id, user_id, fired_due, last_fired_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (task_id, user_id) DO UPDATE
SET fired_due = EXCLUDED.fired_due, last_fired_at = now()
`

type UpsertDueNotificationStateParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	UserID   uuid.UUID `json:"user_id"`
	FiredDue time.Time `json:"fired_due"`
}

func (q *Queries) UpsertDueNotificationState(ctx context.Context, arg UpsertDueNotificationStateParams) error {
	_, err := q.db.Exec(ctx, upsertDueNotificationState, arg.TaskID, arg.UserID, arg.FiredDue)
	return err
}

const upsertNotificationPrefs = `-- name: UpsertNotificationPrefs :one
INSERT INTO notification_prefs (
    user_id, due_enabled, due_lead_minutes, due_repeat_minutes, reminder_enabled,
    quiet_enabled, quiet_start_minutes, quiet_end_minutes, quiet_tz, digest_minutes, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (user_id) DO UPDATE
SET due_enabled = EXCLUDED.due_enabled,
    due_lead_minutes = EXCLUDED.due_lead_minutes,
    due_repeat_minutes = EXCLUDED.due_repeat_minutes,
    reminder_enabled = EXCLUDED.reminder_enabled,
    quiet_enabled = EXCLUDED.quiet_enabled,
    quiet_start_minutes = EXCLUDED.quiet_start_minutes,
    quiet_end_minutes = EXCLUDED.quiet_end_minutes,
    quiet_tz = EXCLUDED.quiet_tz,
    digest_minutes = EXCLUDED.digest_minutes,
    updated_at = now()
RETURNING user_id, due_enabled, due_lead_minutes, due_repeat_minutes, reminder_enabled, updated_at, quiet_enabled, quiet_start_minutes, quiet_end_minutes, quiet_tz, digest_minutes
`

type UpsertNotificationPrefsParams struct {
	UserID            uuid.UUID `json:"user_id"`
	DueEnabled        bool      `json:"due_enabled"`
	DueLeadMinutes    int32     `json:"due_lead_minutes"`
	DueRepeatMinutes  int32     `json:"due_repeat_minutes"`
	ReminderEnabled   bool      `json:"reminder_enabled"`
	QuietEnabled      bool      `json:"quiet_enabled"`
	QuietStartMinutes int32     `json:"quiet_start_minutes"`
	QuietEndMinutes   int32     `json:"quiet_end_minutes"`
	QuietTz           string    `json:"quiet_tz"`
	DigestMinutes     int32     `json:"digest_minutes"`
}

func (q *Queries) UpsertNotificationPrefs(ctx context.Context, arg UpsertNotificationPrefsParams) (NotificationPref, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPrefs,
		arg.UserID,
		arg.DueEnabled,
		arg.DueLeadMinutes,
		arg.DueRepeatMinutes,
		arg.ReminderEnabled,
		arg.QuietEnabled,
		arg.QuietStartMinutes,
		arg.QuietEndMinutes,
		arg.QuietTz,
		arg.DigestMinutes,
	)
	var i NotificationPref
	err := row.Scan(
		&i.UserID,
		&i.DueEnabled,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.ReminderEnabled,
		&i.UpdatedAt,
		&i.QuietEnabled,
		&i.QuietStartMinutes,
		&i.QuietEndMinutes,
		&i.QuietTz,
		&i.DigestMinutes,
	)
	return i, err
}
