// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthUser = `-- name: CreateOAuthUser :one
INSERT INTO users (email, name, password_hash, is_admin, provider, email_verified)
VALUES ($1, $2, '', $3, $4, true)
RETURNING id, email, name, password_hash, is_admin, created_at, updated_at, provider, active, email_verified, last_name, first_name, middle_name, bio, company, job_title
`

type CreateOAuthUserParams struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	IsAdmin  bool   `json:"is_admin"`
	Provider string `json:"provider"`
}

// CreateOAuthUser provisions a GitLab-authenticated account: no password (bcrypt of
// "" never matches), email pre-verified (GitLab vouches for it), provider marked.
func (q *Queries) CreateOAuthUser(ctx context.Context, arg CreateOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOAuthUser,
		arg.Email,
		arg.Name,
		arg.IsAdmin,
		arg.Provider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.Active,
		&i.EmailVerified,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Bio,
		&i.Company,
		&i.JobTitle,
	)
	return i, err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, provider_username, provider_email, gl_base_url, created_at, updated_at FROM oauth_identities WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.GlBaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthProvider = `-- name: GetOAuthProvider :one

SELECT provider, client_id, client_secret_enc, gl_base_url, enabled, org_map, created_at, updated_at FROM oauth_providers WHERE provider = $1
`

// OAuth provider config + external identities (see migration 0042).
func (q *Queries) GetOAuthProvider(ctx context.Context, provider string) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProvider, provider)
	var i OauthProvider
	err := row.Scan(
		&i.Provider,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.GlBaseUrl,
		&i.Enabled,
		&i.OrgMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIDByOAuthUsername = `-- name: GetUserIDByOAuthUsername :one
SELECT user_id FROM oauth_identities WHERE provider = 'gitlab' AND provider_username = $1
`

// GetUserIDByOAuthUsername resolves a GitLab username to a Tessera user via a
// recorded OAuth identity (login-grade link, complements gitlab_credentials).
func (q *Queries) GetUserIDByOAuthUsername(ctx context.Context, providerUsername string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByOAuthUsername, providerUsername)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const upsertOAuthIdentity = `-- name: UpsertOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_user_id, provider_username, provider_email, gl_base_url, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (provider, provider_user_id) DO UPDATE
SET user_id = EXCLUDED.user_id,
    provider_username = EXCLUDED.provider_username,
    provider_email = EXCLUDED.provider_email,
    gl_base_url = EXCLUDED.gl_base_url,
    updated_at = now()
RETURNING id, user_id, provider, provider_user_id, provider_username, provider_email, gl_base_url, created_at, updated_at
`

type UpsertOAuthIdentityParams struct {
	UserID           uuid.UUID `json:"user_id"`
	Provider         string    `json:"provider"`
	ProviderUserID   string    `json:"provider_user_id"`
	ProviderUsername string    `json:"provider_username"`
	ProviderEmail    string    `json:"provider_email"`
	GlBaseUrl        string    `json:"gl_base_url"`
}

// UpsertOAuthIdentity records/refreshes a user's external identity.
func (q *Queries) UpsertOAuthIdentity(ctx context.Context, arg UpsertOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, upsertOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderUsername,
		arg.ProviderEmail,
		arg.GlBaseUrl,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.GlBaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthProvider = `-- name: UpsertOAuthProvider :one
INSERT INTO oauth_providers (provider, client_id, client_secret_enc, gl_base_url, enabled, org_map, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (provider) DO UPDATE
SET client_id = EXCLUDED.client_id,
    client_secret_enc = EXCLUDED.client_secret_enc,
    gl_base_url = EXCLUDED.gl_base_url,
    enabled = EXCLUDED.enabled,
    org_map = EXCLUDED.org_map,
    updated_at = now()
RETURNING provider, client_id, client_secret_enc, gl_base_url, enabled, org_map, created_at, updated_at
`

type UpsertOAuthProviderParams struct {
	Provider        string `json:"provider"`
	ClientID        string `json:"client_id"`
	ClientSecretEnc string `json:"client_secret_enc"`
	GlBaseUrl       string `json:"gl_base_url"`
	Enabled         bool   `json:"enabled"`
	OrgMap          []byte `json:"org_map"`
}

// UpsertOAuthProvider stores the admin-configured OAuth app for a provider.
func (q *Queries) UpsertOAuthProvider(ctx context.Context, arg UpsertOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, upsertOAuthProvider,
		arg.Provider,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.GlBaseUrl,
		arg.Enabled,
		arg.OrgMap,
	)
	var i OauthProvider
	err := row.Scan(
		&i.Provider,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.GlBaseUrl,
		&i.Enabled,
		&i.OrgMap,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
