// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_access_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPAT = `-- name: CreatePAT :one
INSERT INTO personal_access_tokens (user_id, name, token_hash, last_four, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, last_four, expires_at, revoked_at, last_used_at, created_at
`

type CreatePATParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	Name      string     `json:"name"`
	TokenHash string     `json:"token_hash"`
	LastFour  string     `json:"last_four"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreatePAT(ctx context.Context, arg CreatePATParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPAT,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.LastFour,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.LastFour,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPATByHash = `-- name: GetPATByHash :one
SELECT id, user_id, name, token_hash, last_four, expires_at, revoked_at, last_used_at, created_at FROM personal_access_tokens WHERE token_hash = $1
`

func (q *Queries) GetPATByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPATByHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.LastFour,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPATsByUser = `-- name: ListPATsByUser :many
SELECT id, user_id, name, last_four, expires_at, revoked_at, last_used_at, created_at
FROM personal_access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListPATsByUserRow struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	Name       string     `json:"name"`
	LastFour   string     `json:"last_four"`
	ExpiresAt  *time.Time `json:"expires_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

func (q *Queries) ListPATsByUser(ctx context.Context, userID uuid.UUID) ([]ListPATsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPATsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPATsByUserRow
	for rows.Next() {
		var i ListPATsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LastFour,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePAT = `-- name: RevokePAT :exec
UPDATE personal_access_tokens
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokePATParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokePAT(ctx context.Context, arg RevokePATParams) error {
	_, err := q.db.Exec(ctx, revokePAT, arg.ID, arg.UserID)
	return err
}

const touchPATLastUsed = `-- name: TouchPATLastUsed :exec
UPDATE personal_access_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchPATLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPATLastUsed, id)
	return err
}
