// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, group_id, name, color, icon, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon
`

type CreateProjectParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	GroupID     *uuid.UUID `json:"group_id"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	Icon        string     `json:"icon"`
	Position    float64    `json:"position"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.GroupID,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.Position,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, group_id, name, color, position, created_at, updated_at, icon FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, group_id, name, color, position, created_at, updated_at, icon FROM projects WHERE workspace_id = $1 ORDER BY position
`

func (q *Queries) ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GroupID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxProjectPosition = `-- name: MaxProjectPosition :one
SELECT coalesce(max(position), 0)::double precision FROM projects WHERE workspace_id = $1
`

func (q *Queries) MaxProjectPosition(ctx context.Context, workspaceID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxProjectPosition, workspaceID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const moveProject = `-- name: MoveProject :one
UPDATE projects
SET group_id = $2, position = $3, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon
`

type MoveProjectParams struct {
	ID       uuid.UUID  `json:"id"`
	GroupID  *uuid.UUID `json:"group_id"`
	Position float64    `json:"position"`
}

func (q *Queries) MoveProject(ctx context.Context, arg MoveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, moveProject, arg.ID, arg.GroupID, arg.Position)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, color = $3, icon = $4, group_id = $5, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon
`

type UpdateProjectParams struct {
	ID      uuid.UUID  `json:"id"`
	Name    string     `json:"name"`
	Color   string     `json:"color"`
	Icon    string     `json:"icon"`
	GroupID *uuid.UUID `json:"group_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.GroupID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}
