// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProjectGroup = `-- name: CreateProjectGroup :one
INSERT INTO project_groups (workspace_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, position, created_at, updated_at
`

type CreateProjectGroupParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Position    float64   `json:"position"`
}

func (q *Queries) CreateProjectGroup(ctx context.Context, arg CreateProjectGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRow(ctx, createProjectGroup, arg.WorkspaceID, arg.Name, arg.Position)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectGroup = `-- name: DeleteProjectGroup :exec
DELETE FROM project_groups WHERE id = $1
`

func (q *Queries) DeleteProjectGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectGroup, id)
	return err
}

const getProjectGroup = `-- name: GetProjectGroup :one
SELECT id, workspace_id, name, position, created_at, updated_at FROM project_groups WHERE id = $1
`

func (q *Queries) GetProjectGroup(ctx context.Context, id uuid.UUID) (ProjectGroup, error) {
	row := q.db.QueryRow(ctx, getProjectGroup, id)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectGroups = `-- name: ListProjectGroups :many
SELECT id, workspace_id, name, position, created_at, updated_at FROM project_groups WHERE workspace_id = $1 ORDER BY position
`

func (q *Queries) ListProjectGroups(ctx context.Context, workspaceID uuid.UUID) ([]ProjectGroup, error) {
	rows, err := q.db.Query(ctx, listProjectGroups, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectGroup
	for rows.Next() {
		var i ProjectGroup
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxProjectGroupPosition = `-- name: MaxProjectGroupPosition :one
SELECT coalesce(max(position), 0)::double precision FROM project_groups WHERE workspace_id = $1
`

func (q *Queries) MaxProjectGroupPosition(ctx context.Context, workspaceID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxProjectGroupPosition, workspaceID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProjectGroup = `-- name: UpdateProjectGroup :one
UPDATE project_groups
SET name = $2, position = $3, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, name, position, created_at, updated_at
`

type UpdateProjectGroupParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Position float64   `json:"position"`
}

func (q *Queries) UpdateProjectGroup(ctx context.Context, arg UpdateProjectGroupParams) (ProjectGroup, error) {
	row := q.db.QueryRow(ctx, updateProjectGroup, arg.ID, arg.Name, arg.Position)
	var i ProjectGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
