// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, group_id, name, color, icon, slug, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode
`

type CreateProjectParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	GroupID     *uuid.UUID `json:"group_id"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	Icon        string     `json:"icon"`
	Slug        string     `json:"slug"`
	Position    float64    `json:"position"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.GroupID,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.Slug,
		arg.Position,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
		&i.Slug,
		&i.Estimation,
		&i.IconMode,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
		&i.Slug,
		&i.Estimation,
		&i.IconMode,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode FROM projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
		&i.Slug,
		&i.Estimation,
		&i.IconMode,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode FROM projects WHERE workspace_id = $1 ORDER BY position
`

func (q *Queries) ListProjects(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GroupID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
			&i.Slug,
			&i.Estimation,
			&i.IconMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxProjectPosition = `-- name: MaxProjectPosition :one
SELECT coalesce(max(position), 0)::double precision FROM projects WHERE workspace_id = $1
`

func (q *Queries) MaxProjectPosition(ctx context.Context, workspaceID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxProjectPosition, workspaceID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const moveProject = `-- name: MoveProject :one
UPDATE projects
SET group_id = $2, position = $3, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode
`

type MoveProjectParams struct {
	ID       uuid.UUID  `json:"id"`
	GroupID  *uuid.UUID `json:"group_id"`
	Position float64    `json:"position"`
}

func (q *Queries) MoveProject(ctx context.Context, arg MoveProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, moveProject, arg.ID, arg.GroupID, arg.Position)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
		&i.Slug,
		&i.Estimation,
		&i.IconMode,
	)
	return i, err
}

const projectSlugExists = `-- name: ProjectSlugExists :one
SELECT EXISTS(SELECT 1 FROM projects WHERE slug = $1)
`

func (q *Queries) ProjectSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, projectSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectsMissingSlug = `-- name: ProjectsMissingSlug :many
SELECT id, name FROM projects WHERE slug = ''
`

type ProjectsMissingSlugRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ProjectsMissingSlug(ctx context.Context) ([]ProjectsMissingSlugRow, error) {
	rows, err := q.db.Query(ctx, projectsMissingSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectsMissingSlugRow
	for rows.Next() {
		var i ProjectsMissingSlugRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectEstimation = `-- name: SetProjectEstimation :one
UPDATE projects
SET estimation = $2, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode
`

type SetProjectEstimationParams struct {
	ID         uuid.UUID        `json:"id"`
	Estimation *json.RawMessage `json:"estimation"`
}

// SetProjectEstimation stores a project's estimation-config override (NULL =
// inherit the workspace default). Own endpoint, like the workspace one.
func (q *Queries) SetProjectEstimation(ctx context.Context, arg SetProjectEstimationParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectEstimation, arg.ID, arg.Estimation)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
		&i.Slug,
		&i.Estimation,
		&i.IconMode,
	)
	return i, err
}

const setProjectSlug = `-- name: SetProjectSlug :exec
UPDATE projects SET slug = $2 WHERE id = $1
`

type SetProjectSlugParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

func (q *Queries) SetProjectSlug(ctx context.Context, arg SetProjectSlugParams) error {
	_, err := q.db.Exec(ctx, setProjectSlug, arg.ID, arg.Slug)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, color = $3, icon = $4, group_id = $5, icon_mode = $6, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, group_id, name, color, position, created_at, updated_at, icon, slug, estimation, icon_mode
`

type UpdateProjectParams struct {
	ID       uuid.UUID  `json:"id"`
	Name     string     `json:"name"`
	Color    string     `json:"color"`
	Icon     string     `json:"icon"`
	GroupID  *uuid.UUID `json:"group_id"`
	IconMode string     `json:"icon_mode"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.GroupID,
		arg.IconMode,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
		&i.Slug,
		&i.Estimation,
		&i.IconMode,
	)
	return i, err
}
