// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const projectIDForBoard = `-- name: ProjectIDForBoard :one
SELECT project_id FROM boards WHERE id = $1
`

func (q *Queries) ProjectIDForBoard(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, projectIDForBoard, id)
	var project_id uuid.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const workspaceIDForBoard = `-- name: WorkspaceIDForBoard :one
SELECT p.workspace_id
FROM boards b JOIN projects p ON p.id = b.project_id
WHERE b.id = $1
`

func (q *Queries) WorkspaceIDForBoard(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, workspaceIDForBoard, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const workspaceIDForColumn = `-- name: WorkspaceIDForColumn :one
SELECT p.workspace_id
FROM board_columns c
JOIN boards b ON b.id = c.board_id
JOIN projects p ON p.id = b.project_id
WHERE c.id = $1
`

func (q *Queries) WorkspaceIDForColumn(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, workspaceIDForColumn, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const workspaceIDForProject = `-- name: WorkspaceIDForProject :one

SELECT workspace_id FROM projects WHERE id = $1
`

// Scope resolvers: map a nested resource back to its owning workspace so
// handlers can authorize via workspace membership.
func (q *Queries) WorkspaceIDForProject(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, workspaceIDForProject, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const workspaceIDForTask = `-- name: WorkspaceIDForTask :one
SELECT p.workspace_id
FROM tasks t
JOIN boards b ON b.id = t.board_id
JOIN projects p ON p.id = b.project_id
WHERE t.id = $1
`

func (q *Queries) WorkspaceIDForTask(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, workspaceIDForTask, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}
