// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchNotes = `-- name: SearchNotes :many
SELECT id, title, slug
FROM notes
WHERE workspace_id = $1
  AND (title ILIKE '%' || $2 || '%' OR body ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC
LIMIT 25
`

type SearchNotesParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Column2     *string   `json:"column_2"`
}

type SearchNotesRow struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
	Slug  string    `json:"slug"`
}

func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error) {
	rows, err := q.db.Query(ctx, searchNotes, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNotesRow
	for rows.Next() {
		var i SearchNotesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT t.id, t.board_id, b.slug AS board_slug, t.number, t.title, t.parent_id, t.completed_at
FROM tasks t
JOIN boards b ON b.id = t.board_id
JOIN projects p ON p.id = b.project_id
WHERE p.workspace_id = $1
  AND t.archived_at IS NULL
  AND (t.title ILIKE '%' || $2 || '%' OR t.description ILIKE '%' || $2 || '%')
ORDER BY t.number DESC
LIMIT 25
`

type SearchTasksParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Column2     *string   `json:"column_2"`
}

type SearchTasksRow struct {
	ID          uuid.UUID  `json:"id"`
	BoardID     uuid.UUID  `json:"board_id"`
	BoardSlug   string     `json:"board_slug"`
	Number      *int64     `json:"number"`
	Title       string     `json:"title"`
	ParentID    *uuid.UUID `json:"parent_id"`
	CompletedAt *time.Time `json:"completed_at"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]SearchTasksRow, error) {
	rows, err := q.db.Query(ctx, searchTasks, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTasksRow
	for rows.Next() {
		var i SearchTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.BoardSlug,
			&i.Number,
			&i.Title,
			&i.ParentID,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
