// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag_prefixes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteTagPrefixesForProject = `-- name: DeleteTagPrefixesForProject :exec
DELETE FROM tag_prefixes WHERE project_id = $1
`

func (q *Queries) DeleteTagPrefixesForProject(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagPrefixesForProject, projectID)
	return err
}

const listTagPrefixes = `-- name: ListTagPrefixes :many
SELECT project_id, workspace_id, prefix, label, created_at, updated_at FROM tag_prefixes WHERE project_id = $1 ORDER BY prefix
`

func (q *Queries) ListTagPrefixes(ctx context.Context, projectID uuid.UUID) ([]TagPrefix, error) {
	rows, err := q.db.Query(ctx, listTagPrefixes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagPrefix
	for rows.Next() {
		var i TagPrefix
		if err := rows.Scan(
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTagPrefixes = `-- name: ListWorkspaceTagPrefixes :many
SELECT project_id, workspace_id, prefix, label, created_at, updated_at FROM tag_prefixes WHERE workspace_id = $1 ORDER BY prefix
`

// ListWorkspaceTagPrefixes returns prefix names across all projects in a
// workspace, for cross-project views (Home). Same prefix may repeat per project.
func (q *Queries) ListWorkspaceTagPrefixes(ctx context.Context, workspaceID uuid.UUID) ([]TagPrefix, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTagPrefixes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagPrefix
	for rows.Next() {
		var i TagPrefix
		if err := rows.Scan(
			&i.ProjectID,
			&i.WorkspaceID,
			&i.Prefix,
			&i.Label,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTagPrefix = `-- name: UpsertTagPrefix :one
INSERT INTO tag_prefixes (project_id, workspace_id, prefix, label)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, prefix) DO UPDATE
SET label = EXCLUDED.label, updated_at = now()
RETURNING project_id, workspace_id, prefix, label, created_at, updated_at
`

type UpsertTagPrefixParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Prefix      string    `json:"prefix"`
	Label       string    `json:"label"`
}

func (q *Queries) UpsertTagPrefix(ctx context.Context, arg UpsertTagPrefixParams) (TagPrefix, error) {
	row := q.db.QueryRow(ctx, upsertTagPrefix,
		arg.ProjectID,
		arg.WorkspaceID,
		arg.Prefix,
		arg.Label,
	)
	var i TagPrefix
	err := row.Scan(
		&i.ProjectID,
		&i.WorkspaceID,
		&i.Prefix,
		&i.Label,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
