// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTaskAssignee = `-- name: AddTaskAssignee :exec
INSERT INTO task_assignees (task_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, addTaskAssignee, arg.TaskID, arg.UserID)
	return err
}

const addTaskTag = `-- name: AddTaskTag :exec
INSERT INTO task_tags (task_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTaskTagParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTaskTag(ctx context.Context, arg AddTaskTagParams) error {
	_, err := q.db.Exec(ctx, addTaskTag, arg.TaskID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (workspace_id, project_id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, color, created_at, project_id
`

type CreateTagParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.ProjectID,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const ensureTag = `-- name: EnsureTag :one
INSERT INTO tags (workspace_id, project_id, name, color)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, name) DO UPDATE
SET color = COALESCE(NULLIF(EXCLUDED.color, ''), tags.color)
RETURNING id, workspace_id, name, color, created_at, project_id
`

type EnsureTagParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Color       string    `json:"color"`
}

// EnsureTag returns the project tag with this name, creating it (with the given
// color) if absent. On conflict it refreshes the colour only when a non-empty
// one is supplied, so the GitLab sync keeps label colours current without wiping
// a colour set elsewhere. Used by the GitLab sync.
func (q *Queries) EnsureTag(ctx context.Context, arg EnsureTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, ensureTag,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.ProjectID,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, workspace_id, name, color, created_at, project_id FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.ProjectID,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, workspace_id, name, color, created_at, project_id FROM tags WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, projectID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT u.id, u.email, u.name
FROM users u
JOIN task_assignees ta ON ta.user_id = u.id
WHERE ta.task_id = $1
ORDER BY u.name
`

type ListTaskAssigneesRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
}

func (q *Queries) ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskAssigneesRow
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTags = `-- name: ListTaskTags :many
SELECT t.id, t.workspace_id, t.name, t.color, t.created_at, t.project_id
FROM tags t
JOIN task_tags tt ON tt.tag_id = t.id
WHERE tt.task_id = $1
ORDER BY t.name
`

func (q *Queries) ListTaskTags(ctx context.Context, taskID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTaskTags, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTags = `-- name: ListWorkspaceTags :many
SELECT id, workspace_id, name, color, created_at, project_id FROM tags WHERE workspace_id = $1 ORDER BY name
`

// ListWorkspaceTags returns every tag across all projects in a workspace, for
// read-only views that span projects (Home, cross-project task lists).
func (q *Queries) ListWorkspaceTags(ctx context.Context, workspaceID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTags, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignProjectTagsWorkspace = `-- name: ReassignProjectTagsWorkspace :exec
UPDATE tags SET workspace_id = $2 WHERE project_id = $1
`

type ReassignProjectTagsWorkspaceParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// ReassignProjectTagsWorkspace re-stamps the denormalized workspace_id on all of
// a project's tags. Used when a project is transferred between workspaces.
func (q *Queries) ReassignProjectTagsWorkspace(ctx context.Context, arg ReassignProjectTagsWorkspaceParams) error {
	_, err := q.db.Exec(ctx, reassignProjectTagsWorkspace, arg.ProjectID, arg.WorkspaceID)
	return err
}

const removeTaskAssignee = `-- name: RemoveTaskAssignee :exec
DELETE FROM task_assignees WHERE task_id = $1 AND user_id = $2
`

type RemoveTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeTaskAssignee, arg.TaskID, arg.UserID)
	return err
}

const removeTaskTag = `-- name: RemoveTaskTag :exec
DELETE FROM task_tags WHERE task_id = $1 AND tag_id = $2
`

type RemoveTaskTagParams struct {
	TaskID uuid.UUID `json:"task_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTaskTag(ctx context.Context, arg RemoveTaskTagParams) error {
	_, err := q.db.Exec(ctx, removeTaskTag, arg.TaskID, arg.TagID)
	return err
}

const stripNonMemberAssignees = `-- name: StripNonMemberAssignees :execrows
DELETE FROM task_assignees ta
USING tasks t, boards b
WHERE ta.task_id = t.id
  AND t.board_id = b.id
  AND b.project_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM memberships m
    WHERE m.workspace_id = $2 AND m.user_id = ta.user_id
  )
`

type StripNonMemberAssigneesParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

// StripNonMemberAssignees removes assignees from a project's tasks who are not
// members of the given (target) workspace. Used after a project is transferred so
// no dangling assignments remain. Returns the number of rows removed.
func (q *Queries) StripNonMemberAssignees(ctx context.Context, arg StripNonMemberAssigneesParams) (int64, error) {
	result, err := q.db.Exec(ctx, stripNonMemberAssignees, arg.ProjectID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $2, color = $3 WHERE id = $1 RETURNING id, workspace_id, name, color, created_at, project_id
`

type UpdateTagParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color string    `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.ProjectID,
	)
	return i, err
}
