// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_relations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTaskRelation = `-- name: AddTaskRelation :one
INSERT INTO task_relations (task_id, related_task_id, kind)
VALUES ($1, $2, $3)
ON CONFLICT (task_id, related_task_id, kind) DO NOTHING
RETURNING id, task_id, related_task_id, kind, created_at
`

type AddTaskRelationParams struct {
	TaskID        uuid.UUID `json:"task_id"`
	RelatedTaskID uuid.UUID `json:"related_task_id"`
	Kind          string    `json:"kind"`
}

func (q *Queries) AddTaskRelation(ctx context.Context, arg AddTaskRelationParams) (TaskRelation, error) {
	row := q.db.QueryRow(ctx, addTaskRelation, arg.TaskID, arg.RelatedTaskID, arg.Kind)
	var i TaskRelation
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.RelatedTaskID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskRelation = `-- name: DeleteTaskRelation :exec
DELETE FROM task_relations WHERE id = $1
`

func (q *Queries) DeleteTaskRelation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskRelation, id)
	return err
}

const getTaskByNumber = `-- name: GetTaskByNumber :one
SELECT t.id, t.board_id, t.column_id, t.parent_id, t.title, t.description, t.priority, t.due_date, t.position, t.created_by, t.completed_at, t.created_at, t.updated_at, t.archived_at, t.number, t.due_lead_minutes, t.due_repeat_minutes, t.due_notify_enabled, t.recurrence, t.eisenhower_quadrant, t.start_date
FROM tasks t
JOIN boards b ON b.id = t.board_id
JOIN projects p ON p.id = b.project_id
WHERE p.workspace_id = $1 AND t.number = $2
`

type GetTaskByNumberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Number      *int64    `json:"number"`
}

func (q *Queries) GetTaskByNumber(ctx context.Context, arg GetTaskByNumberParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByNumber, arg.WorkspaceID, arg.Number)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
	)
	return i, err
}

const getTaskRelation = `-- name: GetTaskRelation :one
SELECT id, task_id, related_task_id, kind, created_at FROM task_relations WHERE id = $1
`

func (q *Queries) GetTaskRelation(ctx context.Context, id uuid.UUID) (TaskRelation, error) {
	row := q.db.QueryRow(ctx, getTaskRelation, id)
	var i TaskRelation
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.RelatedTaskID,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listBoardDependencies = `-- name: ListBoardDependencies :many
SELECT r.id, r.task_id, r.related_task_id, r.kind
FROM task_relations r
JOIN tasks t  ON t.id  = r.task_id
JOIN tasks rt ON rt.id = r.related_task_id
WHERE t.board_id = $1 AND rt.board_id = $1
  AND r.kind IN ('blocks', 'blocked_by')
`

type ListBoardDependenciesRow struct {
	ID            uuid.UUID `json:"id"`
	TaskID        uuid.UUID `json:"task_id"`
	RelatedTaskID uuid.UUID `json:"related_task_id"`
	Kind          string    `json:"kind"`
}

// Every blocking dependency where BOTH endpoints live on the given board — the
// Gantt view's whole-board edge graph (drawn as arrows). Rows are returned raw
// (task_id/related_task_id/kind); the client normalises to blocker→blocked
// (kind='blocks' → task_id blocks related_task_id; 'blocked_by' → the reverse).
// The relation id lets the client delete an edge directly.
func (q *Queries) ListBoardDependencies(ctx context.Context, boardID uuid.UUID) ([]ListBoardDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listBoardDependencies, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardDependenciesRow
	for rows.Next() {
		var i ListBoardDependenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RelatedTaskID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRelations = `-- name: ListTaskRelations :many
SELECT
    r.id, r.task_id, r.related_task_id, r.kind, r.created_at,
    t.number AS related_number,
    t.title  AS related_title,
    t.board_id AS related_board_id,
    t.completed_at AS related_completed_at,
    t.archived_at  AS related_archived_at
FROM task_relations r
JOIN tasks t ON t.id = r.related_task_id
WHERE r.task_id = $1
ORDER BY r.created_at
`

type ListTaskRelationsRow struct {
	ID                 uuid.UUID  `json:"id"`
	TaskID             uuid.UUID  `json:"task_id"`
	RelatedTaskID      uuid.UUID  `json:"related_task_id"`
	Kind               string     `json:"kind"`
	CreatedAt          time.Time  `json:"created_at"`
	RelatedNumber      *int64     `json:"related_number"`
	RelatedTitle       string     `json:"related_title"`
	RelatedBoardID     uuid.UUID  `json:"related_board_id"`
	RelatedCompletedAt *time.Time `json:"related_completed_at"`
	RelatedArchivedAt  *time.Time `json:"related_archived_at"`
}

func (q *Queries) ListTaskRelations(ctx context.Context, taskID uuid.UUID) ([]ListTaskRelationsRow, error) {
	rows, err := q.db.Query(ctx, listTaskRelations, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskRelationsRow
	for rows.Next() {
		var i ListTaskRelationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.RelatedTaskID,
			&i.Kind,
			&i.CreatedAt,
			&i.RelatedNumber,
			&i.RelatedTitle,
			&i.RelatedBoardID,
			&i.RelatedCompletedAt,
			&i.RelatedArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
