// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const archiveTask = `-- name: ArchiveTask :exec
UPDATE tasks SET archived_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveTask, id)
	return err
}

const archiveTaskCascade = `-- name: ArchiveTaskCascade :exec
UPDATE tasks SET archived_at = now(), updated_at = now() WHERE id = $1 OR parent_id = $1
`

func (q *Queries) ArchiveTaskCascade(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveTaskCascade, id)
	return err
}

const archiveTaskIfActive = `-- name: ArchiveTaskIfActive :exec
UPDATE tasks SET archived_at = now(), updated_at = now() WHERE id = $1 AND archived_at IS NULL
`

// ArchiveTaskIfActive/RestoreTaskIfArchived are idempotent single-task variants for
// the GitLab sync (closed_policy=archive_closed_sprints): no-op + no updated_at churn
// when the task is already in the target state.
func (q *Queries) ArchiveTaskIfActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveTaskIfActive, id)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    board_id, column_id, parent_id, title, description, priority, due_date, start_date, estimate, position, created_by, number
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type CreateTaskParams struct {
	BoardID     uuid.UUID  `json:"board_id"`
	ColumnID    uuid.UUID  `json:"column_id"`
	ParentID    *uuid.UUID `json:"parent_id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Priority    int32      `json:"priority"`
	DueDate     *time.Time `json:"due_date"`
	StartDate   *time.Time `json:"start_date"`
	Estimate    *float64   `json:"estimate"`
	Position    float64    `json:"position"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	Number      *int64     `json:"number"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.BoardID,
		arg.ColumnID,
		arg.ParentID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.StartDate,
		arg.Estimate,
		arg.Position,
		arg.CreatedBy,
		arg.Number,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const detachChildren = `-- name: DetachChildren :exec
UPDATE tasks SET parent_id = NULL, updated_at = now() WHERE parent_id = $1
`

func (q *Queries) DetachChildren(ctx context.Context, parentID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachChildren, parentID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const listBoardArchivedWithMeta = `-- name: ListBoardArchivedWithMeta :many
SELECT
    t.id, t.board_id, t.column_id, t.parent_id, t.title, t.description, t.priority, t.due_date, t.position, t.created_by, t.completed_at, t.created_at, t.updated_at, t.archived_at, t.number, t.due_lead_minutes, t.due_repeat_minutes, t.due_notify_enabled, t.recurrence, t.eisenhower_quadrant, t.start_date, t.estimate, t.milestone_id,
    COALESCE(array_agg(DISTINCT tt.tag_id) FILTER (WHERE tt.tag_id IS NOT NULL), '{}')::uuid[] AS tag_ids,
    COALESCE(array_agg(DISTINCT ta.user_id) FILTER (WHERE ta.user_id IS NOT NULL), '{}')::uuid[] AS assignee_ids
FROM tasks t
LEFT JOIN task_tags tt ON tt.task_id = t.id
LEFT JOIN task_assignees ta ON ta.task_id = t.id
WHERE t.board_id = $1
  AND t.archived_at IS NOT NULL
  AND (
    t.parent_id IS NULL
    OR NOT EXISTS (SELECT 1 FROM tasks p WHERE p.id = t.parent_id AND p.archived_at IS NOT NULL)
  )
GROUP BY t.id
ORDER BY t.archived_at DESC
`

type ListBoardArchivedWithMetaRow struct {
	ID                 uuid.UUID        `json:"id"`
	BoardID            uuid.UUID        `json:"board_id"`
	ColumnID           uuid.UUID        `json:"column_id"`
	ParentID           *uuid.UUID       `json:"parent_id"`
	Title              string           `json:"title"`
	Description        string           `json:"description"`
	Priority           int32            `json:"priority"`
	DueDate            *time.Time       `json:"due_date"`
	Position           float64          `json:"position"`
	CreatedBy          *uuid.UUID       `json:"created_by"`
	CompletedAt        *time.Time       `json:"completed_at"`
	CreatedAt          time.Time        `json:"created_at"`
	UpdatedAt          time.Time        `json:"updated_at"`
	ArchivedAt         *time.Time       `json:"archived_at"`
	Number             *int64           `json:"number"`
	DueLeadMinutes     *int32           `json:"due_lead_minutes"`
	DueRepeatMinutes   *int32           `json:"due_repeat_minutes"`
	DueNotifyEnabled   *bool            `json:"due_notify_enabled"`
	Recurrence         *json.RawMessage `json:"recurrence"`
	EisenhowerQuadrant *int16           `json:"eisenhower_quadrant"`
	StartDate          *time.Time       `json:"start_date"`
	Estimate           *float64         `json:"estimate"`
	MilestoneID        *uuid.UUID       `json:"milestone_id"`
	TagIds             []uuid.UUID      `json:"tag_ids"`
	AssigneeIds        []uuid.UUID      `json:"assignee_ids"`
}

// ListBoardArchivedWithMeta returns a board's archived tasks: top-level ones
// and individually-archived subtasks (whose parent is still active). Children
// archived together with their parent are hidden (they restore with it).
func (q *Queries) ListBoardArchivedWithMeta(ctx context.Context, boardID uuid.UUID) ([]ListBoardArchivedWithMetaRow, error) {
	rows, err := q.db.Query(ctx, listBoardArchivedWithMeta, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardArchivedWithMetaRow
	for rows.Next() {
		var i ListBoardArchivedWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
			&i.TagIds,
			&i.AssigneeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardSubtasksWithMeta = `-- name: ListBoardSubtasksWithMeta :many
SELECT
    t.id, t.board_id, t.column_id, t.parent_id, t.title, t.description, t.priority, t.due_date, t.position, t.created_by, t.completed_at, t.created_at, t.updated_at, t.archived_at, t.number, t.due_lead_minutes, t.due_repeat_minutes, t.due_notify_enabled, t.recurrence, t.eisenhower_quadrant, t.start_date, t.estimate, t.milestone_id,
    tg.tag_ids,
    asg.assignee_ids,
    ga.gitlab_assignee_logins
FROM tasks t
LEFT JOIN LATERAL (
    SELECT COALESCE(array_agg(DISTINCT tt.tag_id), '{}')::uuid[] AS tag_ids
    FROM task_tags tt WHERE tt.task_id = t.id
) tg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(array_agg(DISTINCT ta.user_id), '{}')::uuid[] AS assignee_ids
    FROM task_assignees ta WHERE ta.task_id = t.id
) asg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(array_agg(DISTINCT tga.gl_username), '{}')::text[] AS gitlab_assignee_logins
    FROM task_gitlab_assignees tga WHERE tga.task_id = t.id
) ga ON true
WHERE t.board_id = $1 AND t.parent_id IS NOT NULL AND t.archived_at IS NULL
ORDER BY t.position
`

type ListBoardSubtasksWithMetaRow struct {
	ID                   uuid.UUID        `json:"id"`
	BoardID              uuid.UUID        `json:"board_id"`
	ColumnID             uuid.UUID        `json:"column_id"`
	ParentID             *uuid.UUID       `json:"parent_id"`
	Title                string           `json:"title"`
	Description          string           `json:"description"`
	Priority             int32            `json:"priority"`
	DueDate              *time.Time       `json:"due_date"`
	Position             float64          `json:"position"`
	CreatedBy            *uuid.UUID       `json:"created_by"`
	CompletedAt          *time.Time       `json:"completed_at"`
	CreatedAt            time.Time        `json:"created_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
	ArchivedAt           *time.Time       `json:"archived_at"`
	Number               *int64           `json:"number"`
	DueLeadMinutes       *int32           `json:"due_lead_minutes"`
	DueRepeatMinutes     *int32           `json:"due_repeat_minutes"`
	DueNotifyEnabled     *bool            `json:"due_notify_enabled"`
	Recurrence           *json.RawMessage `json:"recurrence"`
	EisenhowerQuadrant   *int16           `json:"eisenhower_quadrant"`
	StartDate            *time.Time       `json:"start_date"`
	Estimate             *float64         `json:"estimate"`
	MilestoneID          *uuid.UUID       `json:"milestone_id"`
	TagIds               []uuid.UUID      `json:"tag_ids"`
	AssigneeIds          []uuid.UUID      `json:"assignee_ids"`
	GitlabAssigneeLogins []string         `json:"gitlab_assignee_logins"`
}

// ListBoardSubtasksWithMeta returns every subtask on a board (parent_id set)
// with tag/assignee ids, so the kanban can render them under their parents.
// gitlab_assignee_logins mirrors the top-level query so the composer's
// "gl:<login>" assignee filter matches subtasks too.
//
// LATERAL for the same reason as ListBoardTasksWithMeta: this fires on the same
// board render, so joining the three M:N sets multiplied rows here too.
func (q *Queries) ListBoardSubtasksWithMeta(ctx context.Context, boardID uuid.UUID) ([]ListBoardSubtasksWithMetaRow, error) {
	rows, err := q.db.Query(ctx, listBoardSubtasksWithMeta, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardSubtasksWithMetaRow
	for rows.Next() {
		var i ListBoardSubtasksWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
			&i.TagIds,
			&i.AssigneeIds,
			&i.GitlabAssigneeLogins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardTasksWithMeta = `-- name: ListBoardTasksWithMeta :many
SELECT
    t.id, t.board_id, t.column_id, t.parent_id, t.title, t.description, t.priority, t.due_date, t.position, t.created_by, t.completed_at, t.created_at, t.updated_at, t.archived_at, t.number, t.due_lead_minutes, t.due_repeat_minutes, t.due_notify_enabled, t.recurrence, t.eisenhower_quadrant, t.start_date, t.estimate, t.milestone_id,
    tg.tag_ids,
    asg.assignee_ids,
    ga.gitlab_assignees,
    ga.gitlab_assignee_logins,
    gl.gl_iid AS gitlab_iid,
    gl.gl_web_url AS gitlab_url,
    gl.gl_author AS gitlab_author,
    gl.gl_author_name AS gitlab_author_name,
    gl.gl_author_avatar_url AS gitlab_author_avatar_url
FROM tasks t
LEFT JOIN LATERAL (
    SELECT COALESCE(array_agg(DISTINCT tt.tag_id), '{}')::uuid[] AS tag_ids
    FROM task_tags tt WHERE tt.task_id = t.id
) tg ON true
LEFT JOIN LATERAL (
    SELECT COALESCE(array_agg(DISTINCT ta.user_id), '{}')::uuid[] AS assignee_ids
    FROM task_assignees ta WHERE ta.task_id = t.id
) asg ON true
LEFT JOIN LATERAL (
    SELECT
        COALESCE(array_agg(DISTINCT tga.gl_name), '{}')::text[] AS gitlab_assignees,
        COALESCE(array_agg(DISTINCT tga.gl_username), '{}')::text[] AS gitlab_assignee_logins
    FROM task_gitlab_assignees tga WHERE tga.task_id = t.id
) ga ON true
LEFT JOIN gitlab_links gl ON gl.task_id = t.id
WHERE t.board_id = $1 AND t.parent_id IS NULL
  -- Active board (archived_at IS NULL) or the read-only archive view (IS NOT NULL).
  AND (($2::boolean AND t.archived_at IS NOT NULL) OR (NOT $2::boolean AND t.archived_at IS NULL))
  AND (
    (NOT $3::boolean AND $4::uuid IS NULL)             -- all (no scope)
    OR ($3::boolean AND t.milestone_id IS NULL)                               -- backlog (no milestone)
    OR ($4::uuid IS NOT NULL AND t.milestone_id = $4) -- one milestone
  )
ORDER BY CASE WHEN $2::boolean THEN t.archived_at END DESC NULLS LAST, t.position
`

type ListBoardTasksWithMetaParams struct {
	BoardID     uuid.UUID  `json:"board_id"`
	Archived    bool       `json:"archived"`
	Backlog     bool       `json:"backlog"`
	MilestoneID *uuid.UUID `json:"milestone_id"`
}

type ListBoardTasksWithMetaRow struct {
	ID                    uuid.UUID        `json:"id"`
	BoardID               uuid.UUID        `json:"board_id"`
	ColumnID              uuid.UUID        `json:"column_id"`
	ParentID              *uuid.UUID       `json:"parent_id"`
	Title                 string           `json:"title"`
	Description           string           `json:"description"`
	Priority              int32            `json:"priority"`
	DueDate               *time.Time       `json:"due_date"`
	Position              float64          `json:"position"`
	CreatedBy             *uuid.UUID       `json:"created_by"`
	CompletedAt           *time.Time       `json:"completed_at"`
	CreatedAt             time.Time        `json:"created_at"`
	UpdatedAt             time.Time        `json:"updated_at"`
	ArchivedAt            *time.Time       `json:"archived_at"`
	Number                *int64           `json:"number"`
	DueLeadMinutes        *int32           `json:"due_lead_minutes"`
	DueRepeatMinutes      *int32           `json:"due_repeat_minutes"`
	DueNotifyEnabled      *bool            `json:"due_notify_enabled"`
	Recurrence            *json.RawMessage `json:"recurrence"`
	EisenhowerQuadrant    *int16           `json:"eisenhower_quadrant"`
	StartDate             *time.Time       `json:"start_date"`
	Estimate              *float64         `json:"estimate"`
	MilestoneID           *uuid.UUID       `json:"milestone_id"`
	TagIds                []uuid.UUID      `json:"tag_ids"`
	AssigneeIds           []uuid.UUID      `json:"assignee_ids"`
	GitlabAssignees       []string         `json:"gitlab_assignees"`
	GitlabAssigneeLogins  []string         `json:"gitlab_assignee_logins"`
	GitlabIid             *int64           `json:"gitlab_iid"`
	GitlabUrl             *string          `json:"gitlab_url"`
	GitlabAuthor          *string          `json:"gitlab_author"`
	GitlabAuthorName      *string          `json:"gitlab_author_name"`
	GitlabAuthorAvatarUrl *string          `json:"gitlab_author_avatar_url"`
}

// ListBoardTasksWithMeta returns top-level board tasks with their tag and
// assignee ids aggregated, so the kanban can render chips and group by tag
// without an extra round-trip per card.
//
// The three M:N sets are gathered in LATERAL subqueries rather than joined. Joining
// them produced a row per *combination* — a task with 4 tags, 3 assignees and 2 GitLab
// assignees expanded to 24 rows, 23 of which array_agg(DISTINCT …) threw away — and
// this is the board's hot query. Each LATERAL is an index scan on the table's
// (task_id, …) primary key, and the output is one row per task. gitlab_links stays a
// plain LEFT JOIN: task_id is its primary key, so it is 1:1 and never multiplied rows.
// DISTINCT is kept inside the aggregates so the arrays are ordered and deduplicated
// exactly as before (gl_name and gl_username are each sorted on their own value).
// Newest-archived first in the archive; board position otherwise.
func (q *Queries) ListBoardTasksWithMeta(ctx context.Context, arg ListBoardTasksWithMetaParams) ([]ListBoardTasksWithMetaRow, error) {
	rows, err := q.db.Query(ctx, listBoardTasksWithMeta,
		arg.BoardID,
		arg.Archived,
		arg.Backlog,
		arg.MilestoneID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardTasksWithMetaRow
	for rows.Next() {
		var i ListBoardTasksWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
			&i.TagIds,
			&i.AssigneeIds,
			&i.GitlabAssignees,
			&i.GitlabAssigneeLogins,
			&i.GitlabIid,
			&i.GitlabUrl,
			&i.GitlabAuthor,
			&i.GitlabAuthorName,
			&i.GitlabAuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRecurDue = `-- name: ListScheduleRecurDue :many
SELECT id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id FROM tasks
WHERE archived_at IS NULL
  AND completed_at IS NULL
  AND due_date IS NOT NULL
  AND due_date <= now()
  AND recurrence->>'trigger' = 'schedule'
ORDER BY due_date
`

// ListScheduleRecurDue returns active tasks whose recurrence fires on a schedule
// and whose due date has passed — the schedule worker advances each one.
func (q *Queries) ListScheduleRecurDue(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listScheduleRecurDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id FROM tasks WHERE parent_id = $1 ORDER BY position
`

func (q *Queries) ListSubtasks(ctx context.Context, parentID *uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSubtasks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasksWithMeta = `-- name: ListSubtasksWithMeta :many
SELECT
    t.id, t.board_id, t.column_id, t.parent_id, t.title, t.description, t.priority, t.due_date, t.position, t.created_by, t.completed_at, t.created_at, t.updated_at, t.archived_at, t.number, t.due_lead_minutes, t.due_repeat_minutes, t.due_notify_enabled, t.recurrence, t.eisenhower_quadrant, t.start_date, t.estimate, t.milestone_id,
    COALESCE(array_agg(DISTINCT tt.tag_id) FILTER (WHERE tt.tag_id IS NOT NULL), '{}')::uuid[] AS tag_ids,
    COALESCE(array_agg(DISTINCT ta.user_id) FILTER (WHERE ta.user_id IS NOT NULL), '{}')::uuid[] AS assignee_ids,
    gl.gl_iid,
    gl.gl_web_url,
    gl.gl_parent_global_id
FROM tasks t
LEFT JOIN task_tags tt ON tt.task_id = t.id
LEFT JOIN task_assignees ta ON ta.task_id = t.id
LEFT JOIN gitlab_links gl ON gl.task_id = t.id
WHERE t.parent_id = $1
GROUP BY t.id, gl.task_id
ORDER BY t.position
`

type ListSubtasksWithMetaRow struct {
	ID                 uuid.UUID        `json:"id"`
	BoardID            uuid.UUID        `json:"board_id"`
	ColumnID           uuid.UUID        `json:"column_id"`
	ParentID           *uuid.UUID       `json:"parent_id"`
	Title              string           `json:"title"`
	Description        string           `json:"description"`
	Priority           int32            `json:"priority"`
	DueDate            *time.Time       `json:"due_date"`
	Position           float64          `json:"position"`
	CreatedBy          *uuid.UUID       `json:"created_by"`
	CompletedAt        *time.Time       `json:"completed_at"`
	CreatedAt          time.Time        `json:"created_at"`
	UpdatedAt          time.Time        `json:"updated_at"`
	ArchivedAt         *time.Time       `json:"archived_at"`
	Number             *int64           `json:"number"`
	DueLeadMinutes     *int32           `json:"due_lead_minutes"`
	DueRepeatMinutes   *int32           `json:"due_repeat_minutes"`
	DueNotifyEnabled   *bool            `json:"due_notify_enabled"`
	Recurrence         *json.RawMessage `json:"recurrence"`
	EisenhowerQuadrant *int16           `json:"eisenhower_quadrant"`
	StartDate          *time.Time       `json:"start_date"`
	Estimate           *float64         `json:"estimate"`
	MilestoneID        *uuid.UUID       `json:"milestone_id"`
	TagIds             []uuid.UUID      `json:"tag_ids"`
	AssigneeIds        []uuid.UUID      `json:"assignee_ids"`
	GlIid              *int64           `json:"gl_iid"`
	GlWebUrl           *string          `json:"gl_web_url"`
	GlParentGlobalID   *string          `json:"gl_parent_global_id"`
}

// ListSubtasksWithMeta returns a parent's subtasks with tag/assignee ids, so the
// task modal can render a kanban-style hover card for each one.
//
// The three gl_* columns are the subtask's GitLab hierarchy state (#2592), which the
// subtasks tab renders per row: gl_iid non-null means the subtask has its own issue,
// and an EMPTY gl_parent_global_id on top of that is precisely "created and linked,
// but GitLab did not accept it into the hierarchy" — the state that offers a retry.
// Joined here rather than fetched per row because the tab renders the whole list at
// once; gitlab_links is keyed by task_id, so this cannot multiply rows.
func (q *Queries) ListSubtasksWithMeta(ctx context.Context, parentID *uuid.UUID) ([]ListSubtasksWithMetaRow, error) {
	rows, err := q.db.Query(ctx, listSubtasksWithMeta, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubtasksWithMetaRow
	for rows.Next() {
		var i ListSubtasksWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
			&i.TagIds,
			&i.AssigneeIds,
			&i.GlIid,
			&i.GlWebUrl,
			&i.GlParentGlobalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByBoard = `-- name: ListTasksByBoard :many
SELECT id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id FROM tasks WHERE board_id = $1 AND parent_id IS NULL ORDER BY position
`

func (q *Queries) ListTasksByBoard(ctx context.Context, boardID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.Estimate,
			&i.MilestoneID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTaskPositionInColumn = `-- name: MaxTaskPositionInColumn :one
SELECT coalesce(max(position), 0)::double precision
FROM tasks WHERE column_id = $1 AND parent_id IS NULL
`

func (q *Queries) MaxTaskPositionInColumn(ctx context.Context, columnID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxTaskPositionInColumn, columnID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const moveSubtasksToBoard = `-- name: MoveSubtasksToBoard :exec
UPDATE tasks SET board_id = $2, column_id = $3, updated_at = now() WHERE parent_id = $1
`

type MoveSubtasksToBoardParams struct {
	ParentID *uuid.UUID `json:"parent_id"`
	BoardID  uuid.UUID  `json:"board_id"`
	ColumnID uuid.UUID  `json:"column_id"`
}

func (q *Queries) MoveSubtasksToBoard(ctx context.Context, arg MoveSubtasksToBoardParams) error {
	_, err := q.db.Exec(ctx, moveSubtasksToBoard, arg.ParentID, arg.BoardID, arg.ColumnID)
	return err
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks
SET column_id = $2, position = $3, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type MoveTaskParams struct {
	ID       uuid.UUID `json:"id"`
	ColumnID uuid.UUID `json:"column_id"`
	Position float64   `json:"position"`
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, moveTask, arg.ID, arg.ColumnID, arg.Position)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const reopenSubtasks = `-- name: ReopenSubtasks :exec
UPDATE tasks SET completed_at = NULL, updated_at = now()
WHERE parent_id = $1 AND completed_at IS NOT NULL
`

// ReopenSubtasks clears the completion of a recurring task's direct subtasks when
// the parent recurs, so a checklist starts fresh for the next occurrence.
func (q *Queries) ReopenSubtasks(ctx context.Context, parentID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, reopenSubtasks, parentID)
	return err
}

const restoreTask = `-- name: RestoreTask :exec
UPDATE tasks SET archived_at = NULL, updated_at = now() WHERE id = $1 OR parent_id = $1
`

func (q *Queries) RestoreTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreTask, id)
	return err
}

const restoreTaskIfArchived = `-- name: RestoreTaskIfArchived :exec
UPDATE tasks SET archived_at = NULL, updated_at = now() WHERE id = $1 AND archived_at IS NOT NULL
`

func (q *Queries) RestoreTaskIfArchived(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreTaskIfArchived, id)
	return err
}

const setTaskColumnCompleted = `-- name: SetTaskColumnCompleted :exec
UPDATE tasks SET column_id = $2, completed_at = $3, updated_at = now() WHERE id = $1
`

type SetTaskColumnCompletedParams struct {
	ID          uuid.UUID  `json:"id"`
	ColumnID    uuid.UUID  `json:"column_id"`
	CompletedAt *time.Time `json:"completed_at"`
}

// SetTaskColumnCompleted applies a resolved state conflict: move the task to a
// column and set/clear its completion (used when accepting GitLab's open/closed).
func (q *Queries) SetTaskColumnCompleted(ctx context.Context, arg SetTaskColumnCompletedParams) error {
	_, err := q.db.Exec(ctx, setTaskColumnCompleted, arg.ID, arg.ColumnID, arg.CompletedAt)
	return err
}

const setTaskDescription = `-- name: SetTaskDescription :exec
UPDATE tasks SET description = $2, updated_at = now() WHERE id = $1
`

type SetTaskDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
}

func (q *Queries) SetTaskDescription(ctx context.Context, arg SetTaskDescriptionParams) error {
	_, err := q.db.Exec(ctx, setTaskDescription, arg.ID, arg.Description)
	return err
}

const setTaskDueNotify = `-- name: SetTaskDueNotify :one
UPDATE tasks
SET due_lead_minutes = $2, due_repeat_minutes = $3, due_notify_enabled = $4, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type SetTaskDueNotifyParams struct {
	ID               uuid.UUID `json:"id"`
	DueLeadMinutes   *int32    `json:"due_lead_minutes"`
	DueRepeatMinutes *int32    `json:"due_repeat_minutes"`
	DueNotifyEnabled *bool     `json:"due_notify_enabled"`
}

// SetTaskDueNotify sets a task's per-task due-notification overrides (NULL = inherit
// the user default). Used by the card's due popover.
func (q *Queries) SetTaskDueNotify(ctx context.Context, arg SetTaskDueNotifyParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskDueNotify,
		arg.ID,
		arg.DueLeadMinutes,
		arg.DueRepeatMinutes,
		arg.DueNotifyEnabled,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const setTaskEisenhower = `-- name: SetTaskEisenhower :one
UPDATE tasks
SET eisenhower_quadrant = $2, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type SetTaskEisenhowerParams struct {
	ID                 uuid.UUID `json:"id"`
	EisenhowerQuadrant *int16    `json:"eisenhower_quadrant"`
}

// SetTaskEisenhower pins a task to an Eisenhower-matrix quadrant (NULL = derive the
// quadrant automatically from priority + due-date). Used by the matrix view's drag.
func (q *Queries) SetTaskEisenhower(ctx context.Context, arg SetTaskEisenhowerParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskEisenhower, arg.ID, arg.EisenhowerQuadrant)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const setTaskParent = `-- name: SetTaskParent :one
UPDATE tasks
SET parent_id = $2, board_id = $3, column_id = $4, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type SetTaskParentParams struct {
	ID       uuid.UUID  `json:"id"`
	ParentID *uuid.UUID `json:"parent_id"`
	BoardID  uuid.UUID  `json:"board_id"`
	ColumnID uuid.UUID  `json:"column_id"`
}

func (q *Queries) SetTaskParent(ctx context.Context, arg SetTaskParentParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskParent,
		arg.ID,
		arg.ParentID,
		arg.BoardID,
		arg.ColumnID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const setTaskPriority = `-- name: SetTaskPriority :exec
UPDATE tasks SET priority = $2, updated_at = now() WHERE id = $1
`

type SetTaskPriorityParams struct {
	ID       uuid.UUID `json:"id"`
	Priority int32     `json:"priority"`
}

func (q *Queries) SetTaskPriority(ctx context.Context, arg SetTaskPriorityParams) error {
	_, err := q.db.Exec(ctx, setTaskPriority, arg.ID, arg.Priority)
	return err
}

const setTaskTitle = `-- name: SetTaskTitle :exec
UPDATE tasks SET title = $2, updated_at = now() WHERE id = $1
`

type SetTaskTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

// SetTaskTitle / SetTaskDescription apply a single resolved field from a write-back
// conflict resolution (theirs/manual) without disturbing the other columns.
func (q *Queries) SetTaskTitle(ctx context.Context, arg SetTaskTitleParams) error {
	_, err := q.db.Exec(ctx, setTaskTitle, arg.ID, arg.Title)
	return err
}

const transferTask = `-- name: TransferTask :one
UPDATE tasks
SET board_id = $2, column_id = $3, parent_id = NULL, position = $4, updated_at = now()
WHERE id = $1
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type TransferTaskParams struct {
	ID       uuid.UUID `json:"id"`
	BoardID  uuid.UUID `json:"board_id"`
	ColumnID uuid.UUID `json:"column_id"`
	Position float64   `json:"position"`
}

func (q *Queries) TransferTask(ctx context.Context, arg TransferTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, transferTask,
		arg.ID,
		arg.BoardID,
		arg.ColumnID,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, description = $3, priority = $4, due_date = $5, completed_at = $6,
    recurrence = $7, start_date = $8, estimate = $9, updated_at = now()
WHERE id = $1
  AND ($10::timestamptz IS NULL
       OR date_trunc('milliseconds', updated_at)
          = date_trunc('milliseconds', $10::timestamptz))
RETURNING id, board_id, column_id, parent_id, title, description, priority, due_date, position, created_by, completed_at, created_at, updated_at, archived_at, number, due_lead_minutes, due_repeat_minutes, due_notify_enabled, recurrence, eisenhower_quadrant, start_date, estimate, milestone_id
`

type UpdateTaskParams struct {
	ID                uuid.UUID        `json:"id"`
	Title             string           `json:"title"`
	Description       string           `json:"description"`
	Priority          int32            `json:"priority"`
	DueDate           *time.Time       `json:"due_date"`
	CompletedAt       *time.Time       `json:"completed_at"`
	Recurrence        *json.RawMessage `json:"recurrence"`
	StartDate         *time.Time       `json:"start_date"`
	Estimate          *float64         `json:"estimate"`
	ExpectedUpdatedAt *time.Time       `json:"expected_updated_at"`
}

// UpdateTask writes a task's editable fields, optionally under an optimistic
// lock: pass expected_updated_at with the updated_at the client read, and the
// write only lands if nobody touched the row since — no row comes back
// otherwise, so check and write stay in one statement with no gap to race in.
// NULL (the default) means no check, which is how every internal caller writes.
// The comparison is truncated to milliseconds because clients round-trip the
// timestamp through JS Date, which drops the microseconds Postgres stores.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.CompletedAt,
		arg.Recurrence,
		arg.StartDate,
		arg.Estimate,
		arg.ExpectedUpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.ParentID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.Number,
		&i.DueLeadMinutes,
		&i.DueRepeatMinutes,
		&i.DueNotifyEnabled,
		&i.Recurrence,
		&i.EisenhowerQuadrant,
		&i.StartDate,
		&i.Estimate,
		&i.MilestoneID,
	)
	return i, err
}

const updateTaskDueDate = `-- name: UpdateTaskDueDate :exec
UPDATE tasks SET due_date = $2, updated_at = now() WHERE id = $1
`

type UpdateTaskDueDateParams struct {
	ID      uuid.UUID  `json:"id"`
	DueDate *time.Time `json:"due_date"`
}

func (q *Queries) UpdateTaskDueDate(ctx context.Context, arg UpdateTaskDueDateParams) error {
	_, err := q.db.Exec(ctx, updateTaskDueDate, arg.ID, arg.DueDate)
	return err
}

const updateTaskEstimate = `-- name: UpdateTaskEstimate :exec
UPDATE tasks SET estimate = $2, updated_at = now() WHERE id = $1
`

type UpdateTaskEstimateParams struct {
	ID       uuid.UUID `json:"id"`
	Estimate *float64  `json:"estimate"`
}

func (q *Queries) UpdateTaskEstimate(ctx context.Context, arg UpdateTaskEstimateParams) error {
	_, err := q.db.Exec(ctx, updateTaskEstimate, arg.ID, arg.Estimate)
	return err
}

const updateTaskStartDate = `-- name: UpdateTaskStartDate :exec
UPDATE tasks SET start_date = $2, updated_at = now() WHERE id = $1
`

type UpdateTaskStartDateParams struct {
	ID        uuid.UUID  `json:"id"`
	StartDate *time.Time `json:"start_date"`
}

func (q *Queries) UpdateTaskStartDate(ctx context.Context, arg UpdateTaskStartDateParams) error {
	_, err := q.db.Exec(ctx, updateTaskStartDate, arg.ID, arg.StartDate)
	return err
}
