// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO task_comments (task_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, task_id, author_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID   uuid.UUID  `json:"task_id"`
	AuthorID *uuid.UUID `json:"author_id"`
	Body     string     `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TaskID, arg.AuthorID, arg.Body)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM task_comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, task_id, author_id, body, created_at, updated_at FROM task_comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id uuid.UUID) (TaskComment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT c.id, c.task_id, c.author_id, c.body, c.created_at, c.updated_at, u.name AS author_name, u.email AS author_email
FROM task_comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.task_id = $1
ORDER BY c.created_at
`

type ListTaskCommentsRow struct {
	ID          uuid.UUID  `json:"id"`
	TaskID      uuid.UUID  `json:"task_id"`
	AuthorID    *uuid.UUID `json:"author_id"`
	Body        string     `json:"body"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	AuthorName  *string    `json:"author_name"`
	AuthorEmail *string    `json:"author_email"`
}

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCommentsRow
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE task_comments SET body = $2, updated_at = now() WHERE id = $1 RETURNING id, task_id, author_id, body, created_at, updated_at
`

type UpdateCommentParams struct {
	ID   uuid.UUID `json:"id"`
	Body string    `json:"body"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Body)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
