// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listTaskEvents = `-- name: ListTaskEvents :many
SELECT e.id, e.task_id, e.actor_id, e.kind, e.data, e.created_at, u.name AS actor_name, u.email AS actor_email
FROM task_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.task_id = $1
ORDER BY e.created_at
`

type ListTaskEventsRow struct {
	ID         uuid.UUID  `json:"id"`
	TaskID     uuid.UUID  `json:"task_id"`
	ActorID    *uuid.UUID `json:"actor_id"`
	Kind       string     `json:"kind"`
	Data       []byte     `json:"data"`
	CreatedAt  time.Time  `json:"created_at"`
	ActorName  *string    `json:"actor_name"`
	ActorEmail *string    `json:"actor_email"`
}

func (q *Queries) ListTaskEvents(ctx context.Context, taskID uuid.UUID) ([]ListTaskEventsRow, error) {
	rows, err := q.db.Query(ctx, listTaskEvents, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskEventsRow
	for rows.Next() {
		var i ListTaskEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorID,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logTaskEvent = `-- name: LogTaskEvent :one
INSERT INTO task_events (task_id, actor_id, kind, data)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, actor_id, kind, data, created_at
`

type LogTaskEventParams struct {
	TaskID  uuid.UUID  `json:"task_id"`
	ActorID *uuid.UUID `json:"actor_id"`
	Kind    string     `json:"kind"`
	Data    []byte     `json:"data"`
}

func (q *Queries) LogTaskEvent(ctx context.Context, arg LogTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRow(ctx, logTaskEvent,
		arg.TaskID,
		arg.ActorID,
		arg.Kind,
		arg.Data,
	)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ActorID,
		&i.Kind,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}
