// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_attachments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO task_attachments (task_id, uploader_id, filename, content_type, size, storage_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task_id, uploader_id, filename, content_type, size, storage_path, created_at
`

type CreateAttachmentParams struct {
	TaskID      uuid.UUID  `json:"task_id"`
	UploaderID  *uuid.UUID `json:"uploader_id"`
	Filename    string     `json:"filename"`
	ContentType string     `json:"content_type"`
	Size        int64      `json:"size"`
	StoragePath string     `json:"storage_path"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (TaskAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.TaskID,
		arg.UploaderID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.StoragePath,
	)
	var i TaskAttachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM task_attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, task_id, uploader_id, filename, content_type, size, storage_path, created_at FROM task_attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (TaskAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i TaskAttachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UploaderID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const listTaskAttachments = `-- name: ListTaskAttachments :many
SELECT a.id, a.task_id, a.uploader_id, a.filename, a.content_type, a.size, a.storage_path, a.created_at, u.name AS uploader_name
FROM task_attachments a
LEFT JOIN users u ON u.id = a.uploader_id
WHERE a.task_id = $1
ORDER BY a.created_at
`

type ListTaskAttachmentsRow struct {
	ID           uuid.UUID  `json:"id"`
	TaskID       uuid.UUID  `json:"task_id"`
	UploaderID   *uuid.UUID `json:"uploader_id"`
	Filename     string     `json:"filename"`
	ContentType  string     `json:"content_type"`
	Size         int64      `json:"size"`
	StoragePath  string     `json:"storage_path"`
	CreatedAt    time.Time  `json:"created_at"`
	UploaderName *string    `json:"uploader_name"`
}

func (q *Queries) ListTaskAttachments(ctx context.Context, taskID uuid.UUID) ([]ListTaskAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskAttachmentsRow
	for rows.Next() {
		var i ListTaskAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UploaderID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
