// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_acknowledgements.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listUserAcknowledgements = `-- name: ListUserAcknowledgements :many
SELECT key, ack_at FROM user_acknowledgements
WHERE user_id = $1
ORDER BY ack_at
`

type ListUserAcknowledgementsRow struct {
	Key   string    `json:"key"`
	AckAt time.Time `json:"ack_at"`
}

func (q *Queries) ListUserAcknowledgements(ctx context.Context, userID uuid.UUID) ([]ListUserAcknowledgementsRow, error) {
	rows, err := q.db.Query(ctx, listUserAcknowledgements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserAcknowledgementsRow
	for rows.Next() {
		var i ListUserAcknowledgementsRow
		if err := rows.Scan(&i.Key, &i.AckAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAcknowledgement = `-- name: UpsertUserAcknowledgement :one
INSERT INTO user_acknowledgements (user_id, key)
VALUES ($1, $2)
ON CONFLICT (user_id, key) DO UPDATE SET ack_at = user_acknowledgements.ack_at
RETURNING key, ack_at
`

type UpsertUserAcknowledgementParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

type UpsertUserAcknowledgementRow struct {
	Key   string    `json:"key"`
	AckAt time.Time `json:"ack_at"`
}

// Idempotent: a repeated ack keeps the original ack_at (first-seen wins) and
// still returns the row, so the caller can treat the endpoint as "mark seen".
func (q *Queries) UpsertUserAcknowledgement(ctx context.Context, arg UpsertUserAcknowledgementParams) (UpsertUserAcknowledgementRow, error) {
	row := q.db.QueryRow(ctx, upsertUserAcknowledgement, arg.UserID, arg.Key)
	var i UpsertUserAcknowledgementRow
	err := row.Scan(&i.Key, &i.AckAt)
	return i, err
}
