// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserAvatar = `-- name: DeleteUserAvatar :exec
DELETE FROM user_avatars WHERE user_id = $1
`

func (q *Queries) DeleteUserAvatar(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAvatar, userID)
	return err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT content_type, bytes FROM user_avatars WHERE user_id = $1
`

type GetUserAvatarRow struct {
	ContentType string `json:"content_type"`
	Bytes       []byte `json:"bytes"`
}

func (q *Queries) GetUserAvatar(ctx context.Context, userID uuid.UUID) (GetUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserAvatar, userID)
	var i GetUserAvatarRow
	err := row.Scan(&i.ContentType, &i.Bytes)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, language, timezone, country, time_format, date_format, week_start, theme, accent, board_background, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.Timezone,
		&i.Country,
		&i.TimeFormat,
		&i.DateFormat,
		&i.WeekStart,
		&i.Theme,
		&i.Accent,
		&i.BoardBackground,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAvatar = `-- name: UpsertUserAvatar :exec
INSERT INTO user_avatars (user_id, content_type, bytes, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE SET
    content_type = EXCLUDED.content_type,
    bytes        = EXCLUDED.bytes,
    updated_at   = now()
`

type UpsertUserAvatarParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ContentType string    `json:"content_type"`
	Bytes       []byte    `json:"bytes"`
}

func (q *Queries) UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertUserAvatar, arg.UserID, arg.ContentType, arg.Bytes)
	return err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (
    user_id, language, timezone, country, time_format, date_format,
    week_start, theme, accent, board_background, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
ON CONFLICT (user_id) DO UPDATE SET
    language         = EXCLUDED.language,
    timezone         = EXCLUDED.timezone,
    country          = EXCLUDED.country,
    time_format      = EXCLUDED.time_format,
    date_format      = EXCLUDED.date_format,
    week_start       = EXCLUDED.week_start,
    theme            = EXCLUDED.theme,
    accent           = EXCLUDED.accent,
    board_background = EXCLUDED.board_background,
    updated_at       = now()
RETURNING user_id, language, timezone, country, time_format, date_format, week_start, theme, accent, board_background, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Language        string    `json:"language"`
	Timezone        string    `json:"timezone"`
	Country         string    `json:"country"`
	TimeFormat      string    `json:"time_format"`
	DateFormat      string    `json:"date_format"`
	WeekStart       int16     `json:"week_start"`
	Theme           string    `json:"theme"`
	Accent          string    `json:"accent"`
	BoardBackground string    `json:"board_background"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Language,
		arg.Timezone,
		arg.Country,
		arg.TimeFormat,
		arg.DateFormat,
		arg.WeekStart,
		arg.Theme,
		arg.Accent,
		arg.BoardBackground,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Language,
		&i.Timezone,
		&i.Country,
		&i.TimeFormat,
		&i.DateFormat,
		&i.WeekStart,
		&i.Theme,
		&i.Accent,
		&i.BoardBackground,
		&i.UpdatedAt,
	)
	return i, err
}

const userHasAvatar = `-- name: UserHasAvatar :one
SELECT EXISTS(SELECT 1 FROM user_avatars WHERE user_id = $1)
`

func (q *Queries) UserHasAvatar(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userHasAvatar, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
