// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, password_hash, is_admin, created_at, updated_at, provider, active, email_verified, last_name, first_name, middle_name, bio, company, job_title
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.Active,
		&i.EmailVerified,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Bio,
		&i.Company,
		&i.JobTitle,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, is_admin, created_at, updated_at, provider, active, email_verified, last_name, first_name, middle_name, bio, company, job_title FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.Active,
		&i.EmailVerified,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Bio,
		&i.Company,
		&i.JobTitle,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, is_admin, created_at, updated_at, provider, active, email_verified, last_name, first_name, middle_name, bio, company, job_title FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.Active,
		&i.EmailVerified,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Bio,
		&i.Company,
		&i.JobTitle,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, is_admin, active, email_verified, created_at, updated_at
FROM users
ORDER BY name
`

type ListUsersRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	Name          string    `json:"name"`
	IsAdmin       bool      `json:"is_admin"`
	Active        bool      `json:"active"`
	EmailVerified bool      `json:"email_verified"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.IsAdmin,
			&i.Active,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET active = $2, updated_at = now() WHERE id = $1
`

type SetUserActiveParams struct {
	ID     uuid.UUID `json:"id"`
	Active bool      `json:"active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	return err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = $2, updated_at = now() WHERE id = $1
`

type SetUserAdminParams struct {
	ID      uuid.UUID `json:"id"`
	IsAdmin bool      `json:"is_admin"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.Exec(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    name        = $2,
    last_name   = $3,
    first_name  = $4,
    middle_name = $5,
    bio         = $6,
    company     = $7,
    job_title   = $8,
    updated_at  = now()
WHERE id = $1
RETURNING id, email, name, password_hash, is_admin, created_at, updated_at, provider, active, email_verified, last_name, first_name, middle_name, bio, company, job_title
`

type UpdateUserProfileParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	LastName   string    `json:"last_name"`
	FirstName  string    `json:"first_name"`
	MiddleName string    `json:"middle_name"`
	Bio        string    `json:"bio"`
	Company    string    `json:"company"`
	JobTitle   string    `json:"job_title"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.LastName,
		arg.FirstName,
		arg.MiddleName,
		arg.Bio,
		arg.Company,
		arg.JobTitle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.Active,
		&i.EmailVerified,
		&i.LastName,
		&i.FirstName,
		&i.MiddleName,
		&i.Bio,
		&i.Company,
		&i.JobTitle,
	)
	return i, err
}
