// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_commands.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteWorkspaceCommands = `-- name: DeleteWorkspaceCommands :exec
DELETE FROM workspace_commands WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceCommands(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceCommands, workspaceID)
	return err
}

const listWorkspaceCommands = `-- name: ListWorkspaceCommands :many
SELECT workspace_id, key, description, position, created_at, updated_at FROM workspace_commands
WHERE workspace_id = $1
ORDER BY position, key
`

func (q *Queries) ListWorkspaceCommands(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceCommand, error) {
	rows, err := q.db.Query(ctx, listWorkspaceCommands, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceCommand
	for rows.Next() {
		var i WorkspaceCommand
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspaceCommand = `-- name: UpsertWorkspaceCommand :one
INSERT INTO workspace_commands (workspace_id, key, description, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, key) DO UPDATE
SET description = EXCLUDED.description, position = EXCLUDED.position, updated_at = now()
RETURNING workspace_id, key, description, position, created_at, updated_at
`

type UpsertWorkspaceCommandParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Key         string    `json:"key"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
}

func (q *Queries) UpsertWorkspaceCommand(ctx context.Context, arg UpsertWorkspaceCommandParams) (WorkspaceCommand, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceCommand,
		arg.WorkspaceID,
		arg.Key,
		arg.Description,
		arg.Position,
	)
	var i WorkspaceCommand
	err := row.Scan(
		&i.WorkspaceID,
		&i.Key,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
