// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_tasks.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const listWorkspaceTasks = `-- name: ListWorkspaceTasks :many
SELECT
    t.id, t.board_id, t.column_id, t.parent_id, t.title, t.description, t.priority, t.due_date, t.position, t.created_by, t.completed_at, t.created_at, t.updated_at, t.archived_at, t.number, t.due_lead_minutes, t.due_repeat_minutes, t.due_notify_enabled, t.recurrence, t.eisenhower_quadrant, t.start_date,
    b.name AS board_name,
    p.name AS project_name,
    p.color AS project_color,
    c.name AS column_name,
    c.color AS column_color,
    COALESCE(array_agg(DISTINCT tt.tag_id) FILTER (WHERE tt.tag_id IS NOT NULL), '{}')::uuid[] AS tag_ids,
    COALESCE(array_agg(DISTINCT ta.user_id) FILTER (WHERE ta.user_id IS NOT NULL), '{}')::uuid[] AS assignee_ids
FROM tasks t
JOIN boards b ON b.id = t.board_id
JOIN projects p ON p.id = b.project_id
JOIN board_columns c ON c.id = t.column_id
LEFT JOIN task_tags tt ON tt.task_id = t.id
LEFT JOIN task_assignees ta ON ta.task_id = t.id
WHERE p.workspace_id = $1 AND t.parent_id IS NULL AND t.archived_at IS NULL
GROUP BY t.id, b.name, p.name, p.color, c.name, c.color
ORDER BY t.due_date NULLS LAST, t.created_at DESC
`

type ListWorkspaceTasksRow struct {
	ID                 uuid.UUID        `json:"id"`
	BoardID            uuid.UUID        `json:"board_id"`
	ColumnID           uuid.UUID        `json:"column_id"`
	ParentID           *uuid.UUID       `json:"parent_id"`
	Title              string           `json:"title"`
	Description        string           `json:"description"`
	Priority           int32            `json:"priority"`
	DueDate            *time.Time       `json:"due_date"`
	Position           float64          `json:"position"`
	CreatedBy          *uuid.UUID       `json:"created_by"`
	CompletedAt        *time.Time       `json:"completed_at"`
	CreatedAt          time.Time        `json:"created_at"`
	UpdatedAt          time.Time        `json:"updated_at"`
	ArchivedAt         *time.Time       `json:"archived_at"`
	Number             *int64           `json:"number"`
	DueLeadMinutes     *int32           `json:"due_lead_minutes"`
	DueRepeatMinutes   *int32           `json:"due_repeat_minutes"`
	DueNotifyEnabled   *bool            `json:"due_notify_enabled"`
	Recurrence         *json.RawMessage `json:"recurrence"`
	EisenhowerQuadrant *int16           `json:"eisenhower_quadrant"`
	StartDate          *time.Time       `json:"start_date"`
	BoardName          string           `json:"board_name"`
	ProjectName        string           `json:"project_name"`
	ProjectColor       string           `json:"project_color"`
	ColumnName         string           `json:"column_name"`
	ColumnColor        string           `json:"column_color"`
	TagIds             []uuid.UUID      `json:"tag_ids"`
	AssigneeIds        []uuid.UUID      `json:"assignee_ids"`
}

// ListWorkspaceTasks returns every active top-level task across a workspace's
// boards, with location names and tag/assignee ids — backs "My tasks" / "All
// tasks" and the home summary (feature #1).
func (q *Queries) ListWorkspaceTasks(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceTasksRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceTasksRow
	for rows.Next() {
		var i ListWorkspaceTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.ParentID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.DueDate,
			&i.Position,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Number,
			&i.DueLeadMinutes,
			&i.DueRepeatMinutes,
			&i.DueNotifyEnabled,
			&i.Recurrence,
			&i.EisenhowerQuadrant,
			&i.StartDate,
			&i.BoardName,
			&i.ProjectName,
			&i.ProjectColor,
			&i.ColumnName,
			&i.ColumnColor,
			&i.TagIds,
			&i.AssigneeIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
