// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO workspace_invitations (workspace_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Email       string     `json:"email"`
	Role        string     `json:"role"`
	TokenHash   string     `json:"token_hash"`
	InvitedBy   *uuid.UUID `json:"invited_by"`
	ExpiresAt   time.Time  `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM workspace_invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByHash = `-- name: GetInvitationByHash :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByHash(ctx context.Context, tokenHash string) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByHash, tokenHash)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invitations
WHERE workspace_id = $1 AND accepted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInvitations(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceInvitation
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByEmail = `-- name: ListPendingInvitationsByEmail :many
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invitations
WHERE lower(email) = lower($1) AND accepted_at IS NULL AND expires_at > now()
`

func (q *Queries) ListPendingInvitationsByEmail(ctx context.Context, lower string) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceInvitation
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE workspace_invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}
