// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING id, workspace_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.WorkspaceID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, updated_at, task_counter, estimation
`

type CreateWorkspaceParams struct {
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskCounter,
		&i.Estimation,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.WorkspaceID, arg.UserID)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, workspace_id, user_id, role, created_at FROM memberships WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.WorkspaceID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipRole = `-- name: GetMembershipRole :one
SELECT role FROM memberships WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipRole(ctx context.Context, arg GetMembershipRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMembershipRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, owner_id, created_at, updated_at, task_counter, estimation FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskCounter,
		&i.Estimation,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, m.role, u.email, u.name
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY u.name
`

type ListMembersRow struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
	Email  string    `json:"email"`
	Name   string    `json:"name"`
}

func (q *Queries) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.owner_id, w.created_at, w.updated_at, w.task_counter, w.estimation
FROM workspaces w
JOIN memberships m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskCounter,
			&i.Estimation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextWorkspaceTaskNumber = `-- name: NextWorkspaceTaskNumber :one
UPDATE workspaces SET task_counter = task_counter + 1 WHERE id = $1 RETURNING task_counter
`

func (q *Queries) NextWorkspaceTaskNumber(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextWorkspaceTaskNumber, id)
	var task_counter int64
	err := row.Scan(&task_counter)
	return task_counter, err
}

const setWorkspaceEstimation = `-- name: SetWorkspaceEstimation :one
UPDATE workspaces
SET estimation = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, task_counter, estimation
`

type SetWorkspaceEstimationParams struct {
	ID         uuid.UUID        `json:"id"`
	Estimation *json.RawMessage `json:"estimation"`
}

// SetWorkspaceEstimation stores the workspace-wide default estimation config
// (NULL clears it back to the built-in default). Provider-neutral; its own
// endpoint so a name edit never clobbers it.
func (q *Queries) SetWorkspaceEstimation(ctx context.Context, arg SetWorkspaceEstimationParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceEstimation, arg.ID, arg.Estimation)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskCounter,
		&i.Estimation,
	)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships SET role = $3
WHERE workspace_id = $1 AND user_id = $2
RETURNING id, workspace_id, user_id, role, created_at
`

type UpdateMembershipRoleParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	UserID      uuid.UUID `json:"user_id"`
	Role        string    `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.WorkspaceID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, owner_id, created_at, updated_at, task_counter, estimation
`

type UpdateWorkspaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskCounter,
		&i.Estimation,
	)
	return i, err
}
